Repository dlang/druntime, pull requests merged in 2018-05, with the labels that each got.

#2171 [trivial] added missing setgroups to posix
  src/core/sys/posix/unistd.d
Labels: Trivial, auto-merge

#2160 config.d: use enums instead of structs for __c_long, etc.
  src/core/stdc/config.d
Labels: Vision, auto-merge

#2163 Add missing declarations to Mach-O interface
  changelog/getsect.dd
  src/core/sys/darwin/mach/getsect.d
  src/core/sys/darwin/mach/loader.d
Labels: auto-merge

#2174 benchmark: Add option to avoid (re) compiling
  benchmark/runbench.d
Labels: auto-merge

#2173 Musl: add missing declarations needed for vibe.d
  src/core/sys/posix/netdb.d
  src/core/sys/posix/netinet/in_.d
  src/core/sys/posix/signal.d
  src/core/sys/posix/sys/socket.d
Labels: auto-merge

#2183 set core.stdc.stdint types so mangling matches C++
  src/core/stdc/config.d
  src/core/stdc/stdint.d
Labels: Blocking Other Work, Vision, auto-merge

#2176 Fix issue 14536 - destroy() works on extern(C++) classes
  changelog/cpp_destroy.dd
  src/object.d
Labels: Bug Fix, auto-merge

#2177 Add 'lib' Makefile target
  posix.mak
Labels: Trivial, auto-merge

#2182 Android: update core.stdc.math with real declarations
  src/core/stdc/math.d
Labels: auto-merge

#2185 Make statvfs nothrow and @nogc
  src/core/sys/posix/sys/statvfs.d
Labels: auto-merge

#2166 Fix Issue 18768 - object.getArrayHash with custom toHash shouldn't just sum hashes of array elements
  src/object.d
Labels: Enhancement, auto-merge

#2147 Move DMD's object.d members to druntime
  src/object.d
Labels: auto-merge

#2082 Use REF1 for references to object
  src/core/memory.d
Labels: Trivial, auto-merge

#2186 core.stdc.stdint: fix mistake with int_fast16_t
  src/core/stdc/stdint.d
Labels: auto-merge

#2188 core.stdc.stdint: fix mistake with intmax_t on OSX
  src/core/stdc/stdint.d
Labels: Blocking Other Work

#2189 Important to clean up aggregates too!
  src/object.d
Labels: auto-merge

#2187 core.stdc.config: Add cpp_(u)longlong aliases
  src/core/stdc/config.d
Labels: auto-merge

#2178 Fix Issue 18828 - [-betterC] helpless error in object.d
  posix.mak
  src/object.d
  test/betterc/Makefile
  test/betterc/src/test18828.d
Labels: Bug Fix, Vision, auto-merge

#2191 [Trivial] OS X: Make core.stdc.stdint independent of D `long` C++-mangling
  src/core/stdc/stdint.d
Labels: Trivial, auto-merge

#2192 Fix issue 18904 - remove possibility of infinite loop or crashes from
  src/core/internal/string.d
Labels: Bug Fix

#2197 Fix Issue 18920 - core.internal.hash of array of scalars should be `@safe`
  src/core/internal/hash.d
Labels: Enhancement, auto-merge
