Repository dlang/druntime, pull requests merged in 2018-03, with the labels that each got.

#2122 fix Issue 17188 - qsort predicate requires scope parameters
  src/core/stdc/stdlib.d
Labels: Bug Fix, auto-merge

#2127 Merge remote-tracking branch 'upstream/stable' into merge_stable
  changelog/core-memory-__delete.dd
  changelog/lazy-gc-init.dd
  src/core/demangle.d
  src/core/internal/arrayop.d
  src/core/stdc/stdlib.d
  src/core/thread.d
Labels: Bug Fix, auto-merge

#2130 uClibc remove conflicting enum definitions in core.sys.posix.time
  src/core/sys/posix/time.d
Labels: auto-merge

#2074 add aio.d for linux x64
  mak/COPY
  src/core/sys/posix/aio.d
  win32.mak
  win64.mak
Labels: auto-merge

#2131 object.d: no 0 size structs for AAs
  src/object.d
Labels: Blocking Other Work, auto-merge

#2132 uClibc fix core.stdc.math to use the wrapping variants for long double
  src/core/stdc/math.d
Labels: auto-merge

#2129 fix issue 18547 - Win32: throwing exception in fiber crashes application
  src/core/thread.d
Labels: Bug Fix, auto-merge

#2120 fix Issue 18537 - Cannot pass absolute path to coverage options
  src/core/internal/parseoptions.d
Labels: Bug Fix

#2125 Musl: Move IPV6 constant that breaks Bionic
  src/core/sys/posix/netinet/in_.d
Labels: auto-merge

#2136 Add website link to author name for Jonathan M Davis.
  src/core/exception.d
  src/core/sys/darwin/netinet/in_.d
  src/core/sys/dragonflybsd/netinet/in_.d
  src/core/sys/dragonflybsd/time.d
  src/core/sys/freebsd/netinet/in_.d
  src/core/sys/freebsd/time.d
  src/core/sys/linux/netinet/in_.d
  src/core/sys/linux/time.d
  src/core/sys/netbsd/time.d
  src/core/time.d
Labels: Trivial, auto-merge, documentation

#2137 Add badge to Bugzilla
  README.md
Labels: auto-merge

#2139 TypeInfo.getHash(): use const scope
  src/object.d
  src/rt/typeinfo/ti_Acdouble.d
  src/rt/typeinfo/ti_Acfloat.d
  src/rt/typeinfo/ti_Acreal.d
  src/rt/typeinfo/ti_Adouble.d
  src/rt/typeinfo/ti_Afloat.d
  src/rt/typeinfo/ti_Ag.d
  src/rt/typeinfo/ti_Aint.d
  src/rt/typeinfo/ti_Along.d
  src/rt/typeinfo/ti_Areal.d
  src/rt/typeinfo/ti_Ashort.d
  src/rt/typeinfo/ti_C.d
  src/rt/typeinfo/ti_byte.d
  src/rt/typeinfo/ti_cdouble.d
  src/rt/typeinfo/ti_cent.d
  src/rt/typeinfo/ti_cfloat.d
  src/rt/typeinfo/ti_char.d
  src/rt/typeinfo/ti_creal.d
  src/rt/typeinfo/ti_dchar.d
  src/rt/typeinfo/ti_delegate.d
  src/rt/typeinfo/ti_double.d
  src/rt/typeinfo/ti_float.d
  src/rt/typeinfo/ti_int.d
  src/rt/typeinfo/ti_long.d
  src/rt/typeinfo/ti_n.d
  src/rt/typeinfo/ti_ptr.d
  src/rt/typeinfo/ti_real.d
  src/rt/typeinfo/ti_short.d
  src/rt/typeinfo/ti_ubyte.d
  src/rt/typeinfo/ti_ucent.d
  src/rt/typeinfo/ti_uint.d
  src/rt/typeinfo/ti_ulong.d
  src/rt/typeinfo/ti_ushort.d
  src/rt/typeinfo/ti_void.d
  src/rt/typeinfo/ti_wchar.d
Labels: auto-merge

#2144 [Trivial] Delete -@disable this(this) const- in object.d
  src/object.d
Labels: Trivial

#2143 [uClibc] include config definitions
  src/core/sys/posix/config.d
Labels: auto-merge

#2134 [uClibc] extend `core.sys.linux.netinet.in_` definitions
  src/core/sys/linux/netinet/in_.d
Labels: auto-merge

#2142 object: fix escaping p
  src/object.d
Labels: Blocking Other Work, Trivial

#2153 Remove myself as code owner
  CODEOWNERS
Labels: auto-merge

#2076 Fix deprecated rwm operation in core.sync.mutex
  src/core/sync/mutex.d
Labels: Blocking Other Work, auto-merge

#2154 [uClibc] core.stdc.fenv add mips32 architecture
  src/core/stdc/fenv.d
Labels: auto-merge

#1937 Added statfs for FreeBSD
  src/core/sys/posix/sys/statvfs.d
Labels: auto-merge
