Repository dlang/druntime, pull requests merged in 2018-11, with the labels that each got.

#2344 Add druntime bindings for Solaris/SPARC
  src/core/stdc/fenv.d
  src/core/sys/posix/aio.d
  src/core/sys/posix/ucontext.d
Labels: System Headers, Trivial, auto-merge

#2345 Don't use Pascal calling convention in Windows headers
  src/core/sys/windows/httpext.d
  src/core/sys/windows/mapi.d
  src/core/sys/windows/winnetwk.d
Labels: System Headers, auto-merge

#2309 Added std::string_view<>
  changelog/string_view.dd
  mak/COPY
  mak/DOCS
  mak/SRCS
  mak/WINDOWS
  src/core/stdcpp/string_view.d
  test/stdcpp/src/string_view.cpp
  test/stdcpp/src/string_view_test.d
Labels: auto-merge

#2325 Bionic: Add x64 declarations, switch to single TLS function, and define __USE_GNU
  src/core/stdc/fenv.d
  src/core/sys/posix/config.d
  src/core/sys/posix/fcntl.d
  src/core/sys/posix/setjmp.d
  src/core/sys/posix/signal.d
  src/core/sys/posix/sys/ipc.d
  src/core/sys/posix/sys/mman.d
  src/core/sys/posix/sys/socket.d
  src/core/sys/posix/sys/stat.d
  src/core/sys/posix/sys/types.d
  src/rt/sections_android.d
Labels: auto-merge

#2340 Remove deprecated core.sys.osx package
  CODEOWNERS
  mak/COPY
  mak/WINDOWS
  src/core/sys/osx/execinfo.d
  src/core/sys/osx/mach/dyld.d
  src/core/sys/osx/mach/getsect.d
  src/core/sys/osx/mach/kern_return.d
  src/core/sys/osx/mach/loader.d
  src/core/sys/osx/mach/port.d
  src/core/sys/osx/mach/semaphore.d
  src/core/sys/osx/mach/thread_act.d
  src/core/sys/osx/pthread.d
  src/core/sys/osx/sys/cdefs.d
  src/core/sys/osx/sys/event.d
  src/core/sys/osx/sys/mman.d
  src/rt/sections_osx_x86_64.d
Labels: Trivial, auto-merge

#2350 Fix Issue 19398 - Document meaning of core.atomic.MemoryOrder
  src/core/atomic.d
Labels: Enhancement, auto-merge, documentation

#2295 core.internal.hash prefer FNV to MurmurHash3 for short sequences of statically known length
  src/core/internal/hash.d
Labels: auto-merge

#2352 Fix hasElaborateDestructor & hasElaborateCopyConstructor for struct with static array alias & for nested structs/unions
  src/core/internal/traits.d
Labels: Blocking Other Work, Bug Fix, auto-merge

#2353 Make allSatisfy public so it can be unified with std.meta
  src/core/internal/traits.d
Labels: auto-merge

#2252 Fix Issue 19090 - core.internal.hash.bytesHash unit test uses incorrect test vector on BigEndian machines
  src/core/internal/hash.d
Labels: Bug Fix, Trivial, auto-merge

#2343 core.sys.posix.aio: Add musl bindings
  src/core/sys/posix/aio.d
Labels: auto-merge

#2354 rt.sections_elf_shared: Fix struct tls_index definition on x32
  src/rt/sections_elf_shared.d
Labels: GC, Regression, auto-merge

#2356 [GDC] Do not include padding when hashing floating point types
  src/core/internal/convert.d
  src/core/internal/hash.d
Labels: auto-merge

#2357 Version duplicate multilib definition blocks using ARCH_Any
  src/core/stdc/errno.d
  src/core/stdc/fenv.d
  src/core/stdc/math.d
  src/core/sys/linux/dlfcn.d
  src/core/sys/linux/epoll.d
  src/core/sys/linux/link.d
  src/core/sys/linux/sys/auxv.d
  src/core/sys/linux/sys/eventfd.d
  src/core/sys/linux/sys/inotify.d
  src/core/sys/linux/sys/mman.d
  src/core/sys/posix/dlfcn.d
  src/core/sys/posix/fcntl.d
  src/core/sys/posix/signal.d
  src/core/sys/posix/sys/mman.d
  src/core/sys/posix/sys/socket.d
Labels: auto-merge

#2360 Update core.atomic.MemoryOrder docs to mention relation to C++11/C11
  src/core/atomic.d
Labels: documentation

#2359 Fix Issue 19414 - object.__cmp(T[]) on big-endian architectures can use memcmp for unsigned integers of any size
  src/object.d
Labels: Enhancement

#2358 Remove references to `extern(Pascal)`
  src/core/demangle.d
Labels: auto-merge

#2361 Make core.exception.onOutOfMemoryError work in betterC
  src/core/exception.d
  test/betterc/Makefile
  test/betterc/src/test19416.d
Labels: Enhancement, auto-merge

#2355 Add support for RISCV{32,64} to glibc bindings
  src/core/stdc/fenv.d
  src/core/stdc/math.d
  src/core/sys/linux/dlfcn.d
  src/core/sys/linux/epoll.d
  src/core/sys/linux/link.d
  src/core/sys/linux/sys/eventfd.d
  src/core/sys/linux/sys/inotify.d
  src/core/sys/linux/sys/mman.d
  src/core/sys/posix/dlfcn.d
  src/core/sys/posix/fcntl.d
  src/core/sys/posix/setjmp.d
  src/core/sys/posix/signal.d
  src/core/sys/posix/sys/mman.d
  src/core/sys/posix/sys/msg.d
  src/core/sys/posix/sys/socket.d
  src/core/sys/posix/sys/stat.d
  src/core/sys/posix/ucontext.d
  src/rt/sections_elf_shared.d
Labels: auto-merge

#2362 [refactor] core.sys.posix.msg: Genericize msqid_ds definition
  src/core/sys/posix/sys/msg.d
Labels: Refactoring, auto-merge

#2364 Fix Issue 19421: Make pureMalloc, etc. usable in BetterC
  src/core/memory.d
  test/betterc/Makefile
  test/betterc/src/test19421.d
Labels: Enhancement, auto-merge

#2367 Remove static initializer from struct `destroy`.
  src/object.d
Labels: auto-merge

#2365 Make TempStringNoAlloc zero-init + avoid unnecessary init
  src/core/demangle.d
  src/core/internal/abort.d
  src/core/internal/string.d
Labels: auto-merge

#2363 Fix Issue 19370 - AA require() and update() can't be used in @safe code
  src/object.d
Labels: Bug Fix, auto-merge

#2373 Make `assumeSafeAppend` explicitly `@system`
  src/object.d
Labels: auto-merge

#2375 Fix Issue 19433 - Don't consume --DRT-* options if rt_cmdline_enabled is false
  posix.mak
  src/rt/config.d
  src/rt/dmain2.d
  test/config/Makefile
  test/config/src/test19433.d
  test/exceptions/Makefile
Labels: Bug Fix, auto-merge

#2366 Fix Issue 11294 - Object destruction with alias this
  src/object.d
Labels: Bug Fix, auto-merge

#2381 core.sys.linux.sys.mman: Group all CPU versions together
  src/core/sys/linux/sys/mman.d
Labels: Trivial, auto-merge

#2372 Fix Issue 11168: attributes for functions in core.stdc.time.
  src/core/stdc/time.d
Labels: Bug Fix

#2378 Remove unnecessary workaround
  src/object.d
Labels: auto-merge

#2376 destroy() receives initialize argument
  changelog/destroy_noinit.dd
  src/object.d
Labels: Enhancement, auto-merge
