Repository dlang/druntime, pull requests merged in 2018-08, with the labels that each got.

#2261 Remove non-supported Windows documentation build
  win32.mak
  win64.mak
Labels: auto-merge

#2265 Fix FreeBSD's statvfs
  mak/COPY
  mak/SRCS
  src/core/sys/freebsd/sys/mount.d
  src/core/sys/posix/sys/statvfs.d
  win32.mak
  win64.mak
Labels: System Headers, auto-merge

#2266 Merge remote-tracking branch 'upstream/stable' into merge_stable
  src/core/memory.d
Labels: Bug Fix

#2264 Convert _d_arraycast to template
  src/core/internal/string.d
  src/object.d
Labels: Blocking Other Work, auto-merge

#2270 Add a DUB receipt
  dub.sdl
Labels: auto-merge

#2269 Add setjmp/ucontext definitions for FreeBSD/aarch64
  src/core/sys/posix/setjmp.d
  src/core/sys/posix/ucontext.d
Labels: auto-merge

#2263 Move common parts of win{32,64} into mak
  mak/WINDOWS
  win32.mak
  win64.mak
Labels: 72h no objection -> merge, auto-merge

#2146 Expose DRuntime config module header to the docs
  src/rt/config.d
Labels: Trivial, auto-merge, documentation

#1900 Add overrides for __simd intrinsics
  src/core/simd.d
Labels: auto-merge

#2246 Fix Issue 19071 - core.internal.hash should have non-chained toHash overloads
  src/core/internal/hash.d
  src/object.d
  src/rt/aaA.d
  src/rt/typeinfo/ti_Aint.d
  src/rt/typeinfo/ti_Along.d
  src/rt/typeinfo/ti_Ashort.d
  src/rt/typeinfo/ti_C.d
  src/rt/typeinfo/ti_byte.d
  src/rt/typeinfo/ti_cent.d
  src/rt/typeinfo/ti_char.d
  src/rt/typeinfo/ti_dchar.d
  src/rt/typeinfo/ti_int.d
  src/rt/typeinfo/ti_long.d
  src/rt/typeinfo/ti_n.d
  src/rt/typeinfo/ti_ptr.d
  src/rt/typeinfo/ti_short.d
  src/rt/typeinfo/ti_ubyte.d
  src/rt/typeinfo/ti_uint.d
  src/rt/typeinfo/ti_ulong.d
  src/rt/typeinfo/ti_ushort.d
  src/rt/typeinfo/ti_wchar.d
  src/rt/util/typeinfo.d
Labels: 72h no objection -> merge, Enhancement, auto-merge

#2273 [Trivial] Update comment about current state of float/nan coalescing
  src/core/internal/hash.d
Labels: Trivial, auto-merge

#2275 Fix signature of getfsstat to use c_long instead of long.
  src/core/sys/freebsd/sys/mount.d
Labels: System Headers, auto-merge

#2279 add SO_REUSEPORT for AArch64 and ARM
  src/core/sys/posix/sys/socket.d
Labels: System Headers, auto-merge

#2278 Fix Issue 18068 - No file names and line numbers in stack trace - Again
  src/rt/backtrace/elf.d
Labels: Bug Fix, auto-merge

#2281 [stable] core.stdc.config: Don't define cpp_[u]long as special enum on 64-bit Posix
  src/core/stdc/config.d
Labels: auto-merge

#2282 Add buildkite-test target
  posix.mak
Labels: auto-merge

#2283 [stable] Add buildkite-test target
  posix.mak
Labels: auto-merge

#2284 Merge remote-tracking branch 'upstream/stable' into merge_stable
  src/core/stdc/config.d
  src/rt/backtrace/elf.d
Labels: Bug Fix, auto-merge

#2285 core.sys.windows: Add enums required for virtual terminal processing
  src/core/sys/windows/wincon.d
Labels: auto-merge

#2288 Fix issue 19177: add clock() and CLOCKS_PER_SEC for Solaris
  src/core/stdc/time.d
Labels: Bug Fix, auto-merge

#2290 Merge remote-tracking branch 'upstream/stable' into merge_stable
  src/core/stdc/time.d
Labels: Bug Fix, auto-merge
