Repository dlang/druntime, pull requests merged in 2018-06, with the labels that each got.

#2201 Fix typo in changelog
  changelog/cpp_destroy.dd
Labels: Trivial, auto-merge

#2194 Don't needlessly import everything in object.d when compiling with -betterC
  src/object.d
Labels: Vision, auto-merge

#2199 Fix Issue 18924 - Use addition rather than XOR for order-independent hash combination
  src/core/internal/hash.d
  src/rt/aaA.d
Labels: Enhancement

#2202 Fix Issue 18932 - core.internal.hash.hashOf(val, seed) ignores `seed` when val is a raw pointer
  src/core/internal/hash.d
Labels: Bug Fix, auto-merge

#2148 Bionic bindings for AArch64 and a Glibc/AArch64 fix
  src/core/stdc/fenv.d
  src/core/stdc/stdlib.d
  src/core/sys/posix/fcntl.d
  src/core/sys/posix/setjmp.d
  src/core/sys/posix/signal.d
  src/core/sys/posix/sys/ipc.d
  src/core/sys/posix/sys/mman.d
  src/core/sys/posix/sys/socket.d
  src/core/sys/posix/sys/stat.d
  src/core/sys/posix/sys/types.d
  src/core/sys/posix/sys/uio.d
  src/core/sys/posix/time.d
Labels: auto-merge

#2206 Merge remote-tracking branch 'upstream/stable' into merge_stable
  src/core/internal/string.d
  src/object.d
Labels: Bug Fix

#2207 Fix RAND_MAX for freebsd (trivial)
  src/core/stdc/stdlib.d
Labels: auto-merge

#2208 Revert PR 2194 - Don't needlessly import everything in object.d when compiling with -betterC
  src/object.d
Labels: auto-merge

#2210 Fix Issue 18943 - core.internal.hash remove outdated special case for DMD unaligned reads
  src/core/internal/hash.d
Labels: Enhancement, auto-merge

#2204 Fix linker error in destroy under -betterC
  src/object.d
  test/betterc/Makefile
  test/betterc/src/test18828.d
Labels: Vision, auto-merge

#2212 Clarify why we are doing a postblit when setting array length
  src/rt/lifetime.d
Labels: Trivial, auto-merge

#2184 Fix Issue 18493 - [betterC] Can't use aggregated type with postblit
  src/core/stdc/stdlib.d
  src/rt/profilegc.d
  src/rt/trace.d
Labels: Bug Fix, Vision, auto-merge

#2179 BetterC: use templates in core.stdc.stdio instead of functions
  src/core/stdc/stdio.d
Labels: auto-merge

#2200 Fix Issue 18925 - core.internal.hash auto-hash for structs of scalar fields should be `@safe`
  src/core/internal/hash.d
Labels: 72h no objection -> merge, Enhancement

#2213 refactor _d_arraysetlengthT()
  src/rt/lifetime.d
Labels: auto-merge

#2216 fix Issue 18989 - On OSX32, core.stdc.time.clock() should resolve to …
  src/core/stdc/time.d
Labels: Blocking Other Work, Bug Fix, auto-merge

#2196 Set the semaphore handle `protected` instead of `private`
  src/core/sync/semaphore.d
Labels: @andralex, Enhancement

#2220 Fix issue 18996 - ProtoGC should support removing roots and ranges that were not originally added
  src/gc/impl/proto/gc.d
  test/init_fini/Makefile
  test/init_fini/src/test18996.d
Labels: Bug Fix, Regression, auto-merge

#2221 Fix the backtrace changelog entry
  changelog/backtrace_debug_info_macos.dd
Labels: Trivial, auto-merge

#2140 core.internal: add scope
  src/core/internal/arrayop.d
  src/core/internal/hash.d
  src/core/internal/string.d
Labels: Trivial, auto-merge

#2227 Fix Issue 19005 - [REG2.081-b1] object.hashOf no longer works for std.datetime.date.Date
  src/core/internal/hash.d
Labels: Bug Fix

#2226 Fix Issue 19008 - core.internal.convert.toUbyte doesn't work on enums
  src/core/internal/convert.d
Labels: Bug Fix, Enhancement

#2228 Fix Issue 19009 - core.internal.hash.hashOf default hash (absent `toHash`) should be `@nogc`
  src/core/internal/convert.d
  src/core/internal/hash.d
Labels: Enhancement, auto-merge

#2133 Added aio.h implementations for FreeBSD, NetBSD and DragonFly
  src/core/sys/posix/aio.d
Labels: auto-merge

#2232 Fix: 0x is not valid integer literal
  src/rt/sections_elf_shared.d
Labels: auto-merge

#2231 core.sys.posix.aio: Update CRuntime_Glibc bindings to be LARGEFILE64 aware
  src/core/sys/posix/aio.d
Labels: Blocking Other Work, System Headers, auto-merge

#2233 Merge remote-tracking branch 'upstream/stable' into merge_stable
  changelog/backtrace_debug_info_macos.dd
  src/core/internal/convert.d
  src/core/internal/hash.d
  src/core/sys/darwin/mach/getsect.d
  src/gc/impl/proto/gc.d
  test/init_fini/Makefile
  test/init_fini/src/test18996.d
Labels: Bug Fix, auto-merge

#2230 Fix Issue 18068 - No file names and line numbers in stack trace
  src/rt/backtrace/dwarf.d
  src/rt/backtrace/elf.d
  src/rt/backtrace/macho.d
Labels: Bug Fix, auto-merge

#2235 Fix Source path for DRuntime rt package
  src/core/internal/string.d
  src/rt/aApply.d
  src/rt/adi.d
  src/rt/alloca.d
  src/rt/arrayassign.d
  src/rt/arraycast.d
  src/rt/arraycat.d
  src/rt/backtrace/dwarf.d
  src/rt/backtrace/elf.d
  src/rt/backtrace/macho.d
  src/rt/config.d
  src/rt/cover.d
  src/rt/deh.d
  src/rt/deh_win32.d
  src/rt/deh_win64_posix.d
  src/rt/dwarfeh.d
  src/rt/ehalloc.d
  src/rt/lifetime.d
  src/rt/llmath.d
  src/rt/memory.d
  src/rt/minfo.d
  src/rt/profilegc.d
  src/rt/sections.d
  src/rt/sections_android.d
  src/rt/sections_elf_shared.d
  src/rt/sections_osx_x86.d
  src/rt/sections_osx_x86_64.d
  src/rt/sections_solaris.d
  src/rt/sections_win32.d
  src/rt/sections_win64.d
  src/rt/trace.d
  src/rt/tracegc.d
  src/rt/unwind.d
  src/rt/util/array.d
  src/rt/util/hash.d
  src/rt/util/utf.d
Labels: auto-merge

#2236 Merge remote-tracking branch 'upstream/stable' into merge_stable
  src/core/internal/string.d
  src/rt/aApply.d
  src/rt/adi.d
  src/rt/alloca.d
  src/rt/arrayassign.d
  src/rt/arraycast.d
  src/rt/arraycat.d
  src/rt/backtrace/dwarf.d
  src/rt/backtrace/elf.d
  src/rt/backtrace/macho.d
  src/rt/config.d
  src/rt/cover.d
  src/rt/deh.d
  src/rt/deh_win32.d
  src/rt/deh_win64_posix.d
  src/rt/dwarfeh.d
  src/rt/ehalloc.d
  src/rt/lifetime.d
  src/rt/llmath.d
  src/rt/memory.d
  src/rt/minfo.d
  src/rt/profilegc.d
  src/rt/sections.d
  src/rt/sections_android.d
  src/rt/sections_elf_shared.d
  src/rt/sections_osx_x86.d
  src/rt/sections_osx_x86_64.d
  src/rt/sections_solaris.d
  src/rt/sections_win32.d
  src/rt/sections_win64.d
  src/rt/trace.d
  src/rt/tracegc.d
  src/rt/unwind.d
  src/rt/util/array.d
  src/rt/util/hash.d
  src/rt/util/utf.d
Labels: Bug Fix
