Repository dlang/druntime, pull requests merged in 2018-07, with the labels that each got.

#2237 fix Issue 19046 - OSX: bad value for core.stdc.time.CLOCKS_PER_SEC
  src/core/stdc/time.d
Labels: Bug Fix, auto-merge

#2195 Fix Issue 18918 - core.internal.hash should perform memberwise hashing of structs with references
  src/core/internal/convert.d
  src/core/internal/hash.d
Labels: 72h no objection -> merge, Enhancement, auto-merge

#2209 Fix Issue 18942 - core.internal.hash can take advantage of alignment info on non-x86
  src/core/internal/hash.d
Labels: 72h no objection -> merge, Enhancement, auto-merge

#2238 Fix Issue 19048 - In core.internal.hash.hashOf reduce template bloat: remove `auto ref` where unneeded and add `const` where possible
  src/core/internal/convert.d
  src/core/internal/hash.d
Labels: Enhancement, auto-merge

#2241 Merge remote-tracking branch 'upstream/stable' into merge_stable
  changelog/backtrace_debug_info_macos.dd
  changelog/cpp_destroy.dd
  changelog/getsect.dd
Labels: auto-merge

#2242 Add fixes to get Android/AArch64 working
  src/core/stdc/stdlib.d
  src/core/sys/posix/sys/types.d
  src/rt/sections_android.d
Labels: auto-merge

#2245 rt.dwarfeh: Free current inflight exception before calling _d_print_throwable()
  src/rt/dwarfeh.d
  test/exceptions/Makefile
Labels: Blocking Other Work, Bug Fix, auto-merge

#2035 Fix Issue 18220 - Allow `rt_trapexceptions` to be set from the CLI
  .circleci/run.sh
  changelog/exceptions-opt.dd
  src/core/internal/parseoptions.d
  src/rt/dmain2.d
  src/rt/dwarfeh.d
  test/exceptions/Makefile
  test/exceptions/src/rt_trap_exceptions_drt.d
Labels: Enhancement, auto-merge

#2251 Fix typo + remove duplicate rt_configOption declaration
  src/core/internal/parseoptions.d
  src/core/runtime.d
  src/rt/config.d
Labels: auto-merge

#2244 core.sys.posix.signal: Fix size of sigevent and siginfo_t on 64bit.
  src/core/sys/posix/signal.d
Labels: System Headers, Trivial, auto-merge

#2253 Fix Issue 19092 - __delete doesn't work with immutable
  src/core/memory.d
Labels: Bug Fix, Enhancement, auto-merge

#2254 CircleCi: run setup repos before installing dependencies
  .circleci/config.yml
Labels: auto-merge

#2247 Fix Issue 19072 - Object.toHash and typeid(void*).getHash(&ptr) should be more varied in their low bits
  src/object.d
Labels: 72h no objection -> merge, Enhancement, auto-merge

#2243 use core.internal.hash for TypeInfo.getHash
  mak/DOCS
  mak/SRCS
  src/core/internal/hash.d
  src/object.d
  src/rt/aaA.d
  src/rt/typeinfo/ti_Ag.d
  src/rt/typeinfo/ti_Aint.d
  src/rt/typeinfo/ti_Along.d
  src/rt/typeinfo/ti_Ashort.d
  src/rt/typeinfo/ti_C.d
  src/rt/typeinfo/ti_byte.d
  src/rt/typeinfo/ti_cent.d
  src/rt/typeinfo/ti_char.d
  src/rt/typeinfo/ti_dchar.d
  src/rt/typeinfo/ti_delegate.d
  src/rt/typeinfo/ti_int.d
  src/rt/typeinfo/ti_long.d
  src/rt/typeinfo/ti_n.d
  src/rt/typeinfo/ti_ptr.d
  src/rt/typeinfo/ti_short.d
  src/rt/typeinfo/ti_ubyte.d
  src/rt/typeinfo/ti_ucent.d
  src/rt/typeinfo/ti_uint.d
  src/rt/typeinfo/ti_ulong.d
  src/rt/typeinfo/ti_ushort.d
  src/rt/typeinfo/ti_wchar.d
  src/rt/util/container/hashtab.d
  src/rt/util/hash.d
  src/rt/util/typeinfo.d
Labels: 72h no objection -> merge

#2240 Fix Issue 19073 - core.internal.hash should not bitwise hash representations of floating point numbers, plus minor improvements and refactoring
  src/core/internal/hash.d
  src/core/internal/traits.d
Labels: 72h no objection -> merge, Bug Fix, auto-merge

#2256 add changelog for PR #2243
  changelog/typeinfo-gethash.dd
Labels: auto-merge

#2260 CircleCi status badge: only use the master branch
  README.md
Labels: Trivial, auto-merge
