Repository dlang/druntime, pull requests merged in 2018-02, with the labels that each got.

#2071 Some missing parts for musl
  src/core/stdc/errno.d
  src/core/stdc/math.d
  src/core/sync/mutex.d
  src/core/sys/posix/pthread.d
  src/core/sys/posix/signal.d
  src/core/sys/posix/stdlib.d
  src/core/sys/posix/sys/stat.d
  src/core/sys/posix/sys/time.d
  src/core/sys/posix/sys/utsname.d
  src/core/sys/posix/time.d
  src/rt/sections_elf_shared.d
Labels: auto-merge

#2085 posix.mak: Add check for trailing whitespace from phobos
  posix.mak
Labels: auto-merge

#2078 Add uClibc definitions to core.stdc.*
  src/core/stdc/assert_.d
  src/core/stdc/errno.d
  src/core/stdc/fenv.d
  src/core/stdc/locale.d
  src/core/stdc/math.d
  src/core/stdc/stdio.d
  src/core/stdc/stdlib.d
  src/core/stdc/string.d
  src/core/stdc/time.d
  src/core/stdc/wchar_.d
Labels: auto-merge

#1999 Add DragonFlyBSD support for druntime
  src/core/runtime.d
  src/core/stdc/assert_.d
  src/core/stdc/config.d
  src/core/stdc/errno.d
  src/core/stdc/fenv.d
  src/core/stdc/locale.d
  src/core/stdc/math.d
  src/core/stdc/stdio.d
  src/core/stdc/stdlib.d
  src/core/stdc/string.d
  src/core/stdc/time.d
  src/core/sync/mutex.d
  src/core/sys/linux/elf.d
  src/core/sys/netbsd/sys/elf_common.d
  src/core/sys/osx/sys/mman.d
  src/core/sys/solaris/sys/elf.d
  src/core/thread.d
  src/core/threadasm.S
  src/core/time.d
  src/gc/os.d
  src/rt/backtrace/dwarf.d
  src/rt/backtrace/elf.d
  src/rt/dmain2.d
  src/rt/qsort.d
  src/rt/sections.d
  src/rt/sections_elf_shared.d
  src/rt/util/typeinfo.d
  test/exceptions/Makefile
  test/shared/Makefile
  test/shared/src/host.c
  test/shared/src/load.d
Labels: 72h no objection -> merge, auto-merge

#2002 Add DragonFlyBSD support : Split PR : src/core/sys/dragonflybsd related changes
  CODEOWNERS
  mak/COPY
  mak/SRCS
  posix.mak
  src/core/sys/dragonflybsd/dlfcn.d
  src/core/sys/dragonflybsd/execinfo.d
  src/core/sys/dragonflybsd/netinet/in_.d
  src/core/sys/dragonflybsd/pthread_np.d
  src/core/sys/dragonflybsd/sys/_bitset.d
  src/core/sys/dragonflybsd/sys/_cpuset.d
  src/core/sys/dragonflybsd/sys/cdefs.d
  src/core/sys/dragonflybsd/sys/elf.d
  src/core/sys/dragonflybsd/sys/elf32.d
  src/core/sys/dragonflybsd/sys/elf64.d
  src/core/sys/dragonflybsd/sys/elf_common.d
  src/core/sys/dragonflybsd/sys/event.d
  src/core/sys/dragonflybsd/sys/link_elf.d
  src/core/sys/dragonflybsd/sys/mman.d
  src/core/sys/dragonflybsd/time.d
  win32.mak
  win64.mak
Labels: 72h no objection -> merge, auto-merge

#2088 Solaris: fix errno.
  src/core/stdc/errno.d
Labels: auto-merge

#2086 Duration examples fail to run on dlang.org without import.
  src/core/time.d
Labels: Trivial, auto-merge

#2057 GC Initialized on First Alloc
  changelog/lazy-gc-init.dd
  mak/SRCS
  src/gc/impl/proto/gc.d
  src/gc/proxy.d
  src/rt/dmain2.d
  test/exceptions/src/unknown_gc.d
  test/nogc.d
Labels: auto-merge

#2051 Add missing types for cruntime bionic.
  src/core/sys/posix/sys/types.d
Labels: auto-merge

#2092 Add uClibc definitions to core.sys.posix.*
  src/core/sys/posix/arpa/inet.d
  src/core/sys/posix/config.d
  src/core/sys/posix/dirent.d
  src/core/sys/posix/dlfcn.d
  src/core/sys/posix/fcntl.d
  src/core/sys/posix/net/if_.d
  src/core/sys/posix/netdb.d
  src/core/sys/posix/netinet/in_.d
  src/core/sys/posix/poll.d
  src/core/sys/posix/pthread.d
  src/core/sys/posix/pwd.d
  src/core/sys/posix/sched.d
  src/core/sys/posix/semaphore.d
  src/core/sys/posix/setjmp.d
  src/core/sys/posix/signal.d
  src/core/sys/posix/stdio.d
  src/core/sys/posix/stdlib.d
  src/core/sys/posix/sys/ioctl.d
  src/core/sys/posix/sys/ipc.d
  src/core/sys/posix/sys/mman.d
  src/core/sys/posix/sys/resource.d
  src/core/sys/posix/sys/select.d
  src/core/sys/posix/sys/shm.d
  src/core/sys/posix/sys/socket.d
  src/core/sys/posix/sys/stat.d
  src/core/sys/posix/sys/time.d
  src/core/sys/posix/sys/types.d
  src/core/sys/posix/sys/uio.d
  src/core/sys/posix/sys/utsname.d
  src/core/sys/posix/sys/wait.d
  src/core/sys/posix/syslog.d
  src/core/sys/posix/termios.d
  src/core/sys/posix/time.d
  src/core/sys/posix/ucontext.d
  src/core/sys/posix/unistd.d
  src/core/sys/posix/utime.d
Labels: auto-merge

#2096 Last remaining Musl declarations needed for Phobos
  src/core/sys/posix/fcntl.d
  src/core/sys/posix/sys/socket.d
  src/core/sys/posix/sys/stat.d
Labels: auto-merge

#2100 Add rest of core.*, rt.* and gc.os of uClibc definitions.
  src/core/runtime.d
  src/core/thread.d
  src/gc/os.d
  src/rt/backtrace/dwarf.d
  src/rt/qsort.d
  src/rt/sections.d
  src/rt/sections_elf_shared.d
Labels: auto-merge

#2101 Fix recursive reserve call in ProtoGC
  src/gc/impl/proto/gc.d
Labels: Trivial

#2102 Fix recursive reserve call in ProtoGC. Also added global scope operator to all gc_* calls from ProtoGC to clarify that they are the global functions.
  src/gc/impl/proto/gc.d
Labels: auto-merge

#2090 Solaris: add idtype_t visibility.
  src/core/sys/solaris/sys/priocntl.d
  src/core/thread.d
Labels: auto-merge

#2103 Fix Issue 18482 - wincrypt functions should be `@nogc` `nothrow`
  src/core/sys/windows/wincrypt.d
Labels: Bug Fix, auto-merge

#2098 Remove unused and unreferenced function in rt.cast_
  src/rt/cast_.d
Labels: auto-merge

#2097 Use upper-casing for the GC init changelog entry
  changelog/lazy-gc-init.dd
Labels: Trivial, auto-merge

#2095 Improve string switch code, removing extra test for -1.
  src/object.d
Labels: auto-merge

#2106 [Trivial] Add dragonfly implementation for shared memory
  src/core/sys/posix/sys/shm.d
Labels: Bug Fix, Trivial, auto-merge

#2108 __delete shouldn't segfault for null
  src/core/memory.d
Labels: auto-merge

#2110 add FreeBSD github URLs
  src/core/sys/posix/dirent.d
  src/core/sys/posix/sys/stat.d
  src/core/sys/posix/sys/types.d
Labels: Trivial, auto-merge

#2062 fix issue 18300: range error demangling long symbol
  src/core/demangle.d
Labels: Bug Fix, auto-merge

#2121 Issue 17964 - [CTFE] If array is large enough it hits __simd at CTFE
  src/core/internal/arrayop.d
Labels: auto-merge

#2107 [Trivial] Match the module name to the file name (pthread_np)
  src/core/sys/dragonflybsd/pthread_np.d
Labels: Bug Fix, Trivial, auto-merge

#2119 fix issue 18536 - Bad stack traces when building with -m32mscoff
  src/core/sys/windows/stacktrace.d
Labels: Bug Fix, auto-merge
