Repository dlang/druntime, pull requests merged in 2018-12, with the labels that each got.

#2385 add appveyor test for VS2017
  appveyor.yml
Labels: auto-merge

#2387 [dmd-cxx] Disable auto-tester-test from running
  posix.mak
  win32.mak
  win64.mak
Labels: Trivial

#2389 use WCHAR instead of wchar_t when interfacing to Windows API
  src/rt/dmain2.d
Labels: auto-merge

#2392 core/runtime.d: use WCHAR to interface to Windows
  src/core/runtime.d
Labels: auto-merge

#2396 [Trivial] Fix core.stdc.errno for dragonflybsd
  src/core/stdc/errno.d
Labels: Trivial, auto-merge

#2397 Fix issue 19468: improve cyclic dependency error message.
  src/rt/minfo.d
Labels: Enhancement, Trivial, auto-merge

#2401 rt/sections.d: Update SectionGroup signatures to match on all targets
  src/rt/sections_osx_x86.d
  src/rt/sections_osx_x86_64.d
  src/rt/sections_solaris.d
  src/rt/sections_win32.d
  src/rt/sections_win64.d
Labels: Trivial, auto-merge

#2405 Remove private isnan function with only one caller
  src/object.d
Labels: Trivial, auto-merge

#2403 Make rt utf publicly available
  mak/COPY
  mak/DOCS
  mak/SRCS
  mak/WINDOWS
  src/core/internal/utf.d
  src/rt/aApply.d
  src/rt/aApplyR.d
  src/rt/adi.d
  src/rt/cover.d
Labels: auto-merge

#2406 Add a few public examples to object.d
  src/object.d
Labels: 72h no objection -> merge

#2410 core/thread: Support StackGrowsUp in getStackBottom()
  src/core/thread.d
  src/gc/impl/conservative/gc.d
Labels: Bug Fix

#2412 Add some traits
  src/core/internal/traits.d
Labels: auto-merge

#2409 Fix issue 19128 - argument to alloca may be too large
  src/rt/arrayassign.d
Labels: Enhancement

#2416 [trivial] Add EPOLLEXCLUSIVE flag that is added in Linux 4.5
  src/core/sys/linux/epoll.d
Labels: Trivial, auto-merge

#2384 fix issue 19455 - GC wastes too much memory
  src/gc/impl/conservative/gc.d
Labels: Enhancement, GC, auto-merge

#2423 fix issue 12843 again: Unit tests fail when GC is compiled with SENTINEL
  posix.mak
  src/gc/impl/conservative/gc.d
  test/gc/Makefile
  test/gc/win64.mak
  win64.mak
Labels: Bug Fix, auto-merge

#2422 generate pointer bitmap as RTInfo for TypeInfo.rtInfo()
  src/object.d
  src/rt/typeinfo/ti_byte.d
  src/rt/typeinfo/ti_cdouble.d
  src/rt/typeinfo/ti_cent.d
  src/rt/typeinfo/ti_cfloat.d
  src/rt/typeinfo/ti_char.d
  src/rt/typeinfo/ti_creal.d
  src/rt/typeinfo/ti_dchar.d
  src/rt/typeinfo/ti_delegate.d
  src/rt/typeinfo/ti_double.d
  src/rt/typeinfo/ti_float.d
  src/rt/typeinfo/ti_int.d
  src/rt/typeinfo/ti_long.d
  src/rt/typeinfo/ti_n.d
  src/rt/typeinfo/ti_ptr.d
  src/rt/typeinfo/ti_real.d
  src/rt/typeinfo/ti_short.d
  src/rt/typeinfo/ti_ubyte.d
  src/rt/typeinfo/ti_ucent.d
  src/rt/typeinfo/ti_uint.d
  src/rt/typeinfo/ti_ulong.d
  src/rt/typeinfo/ti_ushort.d
  src/rt/typeinfo/ti_wchar.d
Labels: auto-merge

#2420 fix issue 19281 - GC mishandles allocations >= 4GB
  src/gc/impl/conservative/gc.d
  src/gc/os.d
Labels: Bug Fix, GC, auto-merge

#2425 fix issue 19498 - undefined identifier rt_loadLibraryW
  src/core/runtime.d
  test/shared/src/loadlibwin.d
  win64.mak
Labels: Bug Fix, auto-merge

#2421 add range operations to GCBits to help copying bitmaps in a precise GC
  src/gc/bits.d
Labels: GC, auto-merge

#2426 Fix Issue 19524 - Make core.checkedint work in betterC
  src/core/checkedint.d
Labels: Enhancement, auto-merge

#2429 fix Issue 19522 - [GC] GC.query/addrOf/sizeOf fail for freed memory
  src/core/memory.d
  src/gc/impl/conservative/gc.d
Labels: Bug Fix, auto-merge
