Repository dlang/druntime, pull requests merged in 2018-09, with the labels that each got.

#2291 Merge remote-tracking branch 'upstream/stable' into merge_stable
  changelog/exceptions-opt.dd
  changelog/require_update.dd
  changelog/typeinfo-gethash.dd
  changelog/utsname_version.dd
Labels: auto-merge

#2293 [Trivial] remove 2 empty statements
  src/object.d
Labels: Trivial, auto-merge

#2299 Moving Fiber example into unittest
  src/core/thread.d
Labels: auto-merge, documentation

#2300 Fix newlines in .editorconfig
  .editorconfig
Labels: auto-merge

#2257 core.internal.convert: add IEEE Quadruple support
  src/core/internal/convert.d
Labels: auto-merge

#2298 Fix out of bounds buffer access in backtrace
  src/rt/backtrace/dwarf.d
  test/exceptions/Makefile
  test/exceptions/long_backtrace_trunc.exp
  test/exceptions/src/long_backtrace_trunc.d
Labels: Bug Fix, auto-merge

#2302 [stable] core.stdc.stdint: Fix some aliases for Windows/MSVC
  src/core/stdc/stdint.d
Labels: auto-merge

#2304 Fix use of std.json in gcbench.conmsg
  benchmark/gcbench/conmsg.d
Labels: auto-merge

#2311 Move hashOf non-documentation unittests to tests/hash
  posix.mak
  src/core/internal/hash.d
  src/object.d
  test/hash/Makefile
  test/hash/src/test_hash.d
  win32.mak
  win64.mak
Labels: auto-merge

#2307 [stable] core.stdc.stdint: Fix some [u]int_fast<N>_t aliases for Win64 and FreeBSD
  src/core/stdc/stdint.d
Labels: auto-merge
