Repository dlang/druntime, pull requests merged in 2018-10, with the labels that each got.

#2315 Fix Issue 19280 - Remove unnecessary error checks in core.time.currSystemTick
  src/core/time.d
Labels: Enhancement, auto-merge

#2320 Slightly refactor rt.sections_elf_shared [NFC]
  src/rt/sections_elf_shared.d
Labels: auto-merge

#2318 Fix Issue 19282 - hashOf segfaults for non-null C++ objects
  src/core/internal/hash.d
  test/hash/src/test_hash.d
Labels: Blocking Other Work, Bug Fix, auto-merge

#2308 [AArch64] [GDC] AArch64: Fix backtraces in Fibers
  src/core/thread.d
  src/core/threadasm.S
Labels: 72h no objection -> merge, auto-merge

#1678 Ensure that the writable data segment is aligned.
  src/rt/sections_elf_shared.d
Labels: auto-merge

#2317 Fix Issue 19280 - Remove unnecessary error checks in core.time, Part 2
  src/core/time.d
Labels: Enhancement, auto-merge

#2328 Add binding for FreeBSD's getosreldate.
  mak/COPY
  mak/SRCS
  mak/WINDOWS
  src/core/sys/freebsd/unistd.d
Labels: auto-merge

#2329 Add bindings for POSIX's spawn.h
  mak/COPY
  mak/SRCS
  mak/WINDOWS
  src/core/sys/posix/spawn.d
Labels: auto-merge

#2335 [testsuite] Replace issue numbers with bugzilla urls
  test/aa/src/test_aa.d
  test/exceptions/src/static_dtor.d
  test/hash/src/test_hash.d
Labels: Trivial, auto-merge

#2303 Refactor core.stdcpp to use extern(C++, string) and CppRuntime_* versions
  src/core/stdcpp/exception.d
  src/core/stdcpp/typeinfo.d
Labels: auto-merge, stdcpp

#2336 don't include windows.d in stdio.d
  src/core/stdc/stdio.d
Labels: auto-merge

#2333 Fix crash on attaching external threads
  src/gc/impl/conservative/gc.d
  test/thread/Makefile
  test/thread/src/external_threads.d
Labels: auto-merge

#2274 [RFC] Issue 19087 - final switch cannot be used in -betterC
  src/core/exception.d
Labels: Bug Fix, auto-merge

#2289 Fix Issue 19204 - hashOf doesn't accept SIMD vectors
  src/core/internal/convert.d
  src/core/internal/hash.d
  test/hash/src/test_hash.d
Labels: Blocking Other Work, Bug Fix, auto-merge

#2334 Fix crash in destructor of detached thread
  src/core/thread.d
  test/thread/src/external_threads.d
Labels: Bug Fix, auto-merge

#2338 Port more efficient allSatisfy/anySatisfy from dlang/phobos#6402
  src/core/internal/traits.d
Labels: auto-merge

#2339 Merge remote-tracking branch 'upstream/stable' into merge_stable
  src/core/thread.d
  src/gc/impl/conservative/gc.d
  test/thread/Makefile
  test/thread/src/external_threads.d
Labels: Bug Fix

#2341 Dwarf EH: explicitly remove our reference to caught Throwable
  src/rt/dwarfeh.d
Labels: auto-merge

#2337 hashOf fails to compile for const struct that has non-const toHash & has all fields bitwise-hashable
  src/core/internal/hash.d
  test/hash/src/test_hash.d
Labels: 72h no objection -> merge, Bug Fix, auto-merge
