Repository dlang/druntime, pull requests merged in 2019-05, with the labels that each got.

#2595 Merge remote-tracking branch 'upstream/stable' into merge_stable
  changelog/core_sync_event.dd
Labels: auto-merge, stable -> master

#2597 vdparser benchmark: fix typo for version=EXTENDED
  benchmark/gcbench/vdparser.d
Labels: Trivial, auto-merge

#2599 GC: fix wrong profile result if more than 4GB used
  src/gc/impl/conservative/gc.d
Labels: Bug Fix, Trivial, auto-merge

#2594 [netbsd] core.stdc.fenv: Fix error undefined uint32_t
  src/core/stdc/fenv.d
  src/core/sys/posix/signal.d
  src/core/sys/posix/ucontext.d
Labels: auto-merge

#2598 Add memmem to core.sys
  mak/COPY
  mak/SRCS
  mak/WINDOWS
  src/core/sys/bionic/string.d
  src/core/sys/darwin/string.d
  src/core/sys/dragonflybsd/string.d
  src/core/sys/freebsd/string.d
  src/core/sys/linux/string.d
  src/core/sys/netbsd/string.d
  src/core/sys/netbsd/sys/featuretest.d
  src/core/sys/openbsd/string.d
Labels: System Headers, auto-merge

#2600 [trivial][aio][uclibc] Add missing `else` from version checks
  src/core/sys/posix/aio.d
Labels: auto-merge

#2605 [musl] Add ports for targets other than x86_64
  src/core/stdc/fenv.d
  src/core/sys/posix/signal.d
  src/core/sys/posix/sys/types.d
  src/core/sys/posix/ucontext.d
Labels: System Headers, auto-merge

#2606 Improve public core.bitop.rol/ror tests
  src/core/bitop.d
Labels: auto-merge, documentation

#2601 Move deprecation along for FracSec.
  src/core/time.d
Labels: auto-merge

#2602 Try to fix issue 19831 without understanding by copying the behavior from __dmd_personality_v0
  src/rt/dwarfeh.d
  test/exceptions/Makefile
  test/exceptions/src/catch_in_finally.d
Labels: Bug Fix, auto-merge

#2609 fix Issue 19701 - undefined reference to _D6object__T6hashOf
  src/object.d
Labels: Bug Fix, auto-merge

#2613 Improve rt.util.container.common.initialize!T(ref T) if is(T == struct)
  src/rt/util/container/common.d
Labels: auto-merge

#2612 Add missing enum for FindFirstFileEx.
  src/core/sys/windows/winbase.d
Labels: auto-merge

#2610 Add Hygon Dhyana Processor CPU Vendor ID detection
  src/core/cpuid.d
Labels: auto-merge

#2603 fix ldap bindings, fix issue 17248
  src/core/sys/windows/winldap.d
  src/core/sys/windows/winnt.d
Labels: Bug Fix, auto-merge

#2614 updated _IO_FILE of the glibc version
  src/core/stdc/stdio.d
Labels: auto-merge

#2617 Align fibers to 16 bytes on Linux
  src/core/thread.d
Labels: Blocking Other Work, auto-merge

#2618 Align fibers to 16 on x86 targets
  src/core/thread.d
Labels: auto-merge

#2607 Rework of -profile=gc calculations
  src/core/gc/gcinterface.d
  src/core/memory.d
  src/gc/impl/conservative/gc.d
  src/gc/impl/manual/gc.d
  src/gc/impl/proto/gc.d
  src/gc/proxy.d
  src/rt/profilegc.d
  src/rt/tracegc.d
  test/init_fini/src/custom_gc.d
  test/profile/Makefile
  test/profile/bothgc.log.exp
  test/profile/myprofilegc.log.exp
  test/profile/myprofilegc.log.freebsd.32.exp
  test/profile/myprofilegc.log.freebsd.64.exp
  test/profile/myprofilegc.log.linux.32.exp
  test/profile/myprofilegc.log.linux.64.exp
  test/profile/myprofilegc.log.osx.32.exp
  test/profile/myprofilegc.log.osx.64.exp
  test/profile/src/profilegc.d
Labels: auto-merge
