Repository dlang/druntime, pull requests merged in 2019-12, with the labels that each got.

#2853 Fix issue 20354: interface is not supported by cas
  src/core/atomic.d
  src/core/internal/atomic.d
Labels: Bug Fix, auto-merge

#2854 [Musl] add definition for RLIM_INFINITY
  src/core/sys/posix/sys/resource.d
Labels: System Headers, auto-merge

#2856 [Musl] fix SO_* for MIPS
  src/core/sys/posix/sys/socket.d
Labels: auto-merge

#2688 Use MONOTONIC clock with condition if available
  src/core/sync/condition.d
  src/core/sync/config.d
  src/core/sync/event.d
Labels: auto-merge

#2857 Remove _copyRelocSection symbol from druntime
  src/rt/sections_elf_shared.d
Labels: auto-merge

#2860 fix Issue 20364 - [REG2.069] changing length for typeof(null)[] array…
  src/rt/typeinfo/ti_n.d
Labels: Bug Fix, Trivial

#2858 fix issue 20438 - [Reg 2.086] GC: memory not reusable when calling GC…
  src/gc/impl/conservative/gc.d
  test/gc/Makefile
  test/gc/recoverfree.d
  test/gc/win64.mak
Labels: Bug Fix, auto-merge

#2863 core.internal.convert: Implement support for IBM extended float.
  src/core/internal/convert.d
Labels: auto-merge

#2864 core.math: Add templated toPrec.
  changelog/to-prec.dd
  src/core/math.d
Labels: auto-merge

#2865 Fix comment for global constructors
  src/rt/sections_elf_shared.d
Labels: auto-merge

#2869 Fix Issue 20440 - Associative arrays with values whose opAssign doesn't return a ref don't support require function
  src/object.d
  test/aa/src/test_aa.d
Labels: Bug Fix

#2870 Fix Issue 20355 - undefined identifier U in core.atomic
  src/core/atomic.d
Labels: Bug Fix

#2558 rt.sections_elf_shared.d: Populate _tlsRanges in every thread
  src/rt/sections_elf_shared.d
  test/thread/Makefile
  test/thread/src/tlsgc_sections.d
Labels: Blocking Other Work, Bug Fix, auto-merge

#2872 Merge remote-tracking branch 'upstream/stable' into merge_stable
  src/core/atomic.d
  src/core/internal/atomic.d
  src/gc/impl/conservative/gc.d
  test/gc/Makefile
  test/gc/recoverfree.d
  test/gc/win64.mak
Labels: Bug Fix, auto-merge

#2867 Fix Issue 20303 - Memory leak in core.thread
  src/core/thread/osthread.d
Labels: Bug Fix

#2877 Switch default behavior of tests to only run tests when they are present
  changelog/unittest-default.dd
  src/core/runtime.d
Labels: auto-merge

#2873 Fix issue 17563 - Expose gc_inFinalizer
  changelog/gc_in_finalizer.dd
  src/core/gc/gcinterface.d
  src/core/memory.d
  src/gc/impl/conservative/gc.d
  src/gc/proxy.d
Labels: Enhancement, GC, auto-merge

#2868 core.internal.convert: Use toPrec to force double precision when parsing IBM 128bit floats
  src/core/internal/convert.d
Labels: auto-merge

#2883 Simplify emplaceInitializer
  src/core/internal/lifetime.d
Labels: Refactoring, auto-merge

#2884 Move string concatenation out of _d_assert_fail
  src/core/internal/dassert.d
Labels: auto-merge

#2885 Remove deprecated FracSec
  src/core/time.d
Labels: auto-merge

#2887 [changelog]: Improve GC.inFinalizer changelog entry
  changelog/gc_in_finalizer.dd
Labels: auto-merge

#2882 [stable] core.exception: Align TLS store for static Errors
  src/core/exception.d
Labels: auto-merge

#2881 Fix issue 20459 - Runtime arg parsing should stop at POSIX delimiter
  src/rt/dmain2.d
  test/config/Makefile
  test/config/src/test20459.d
Labels: Bug Fix, auto-merge

#2862 Fix issue 19489 - Null function call results in no stack trace
  src/core/sys/windows/stacktrace.d
  test/exceptions/src/winstack.d
  test/exceptions/win64.mak
  win32.mak
  win64.mak
Labels: Bug Fix, auto-merge

#2876 [Musl] add to syslog.d
  src/core/sys/posix/syslog.d
Labels: auto-merge

#2859 rt.backtrace.elf: Support D_X32 targets
  src/rt/backtrace/elf.d
Labels: auto-merge

#2723 Add std::unique_ptr
  changelog/std_unique_ptr.dd
  src/core/stdcpp/allocator.d
  src/core/stdcpp/memory.d
  src/core/stdcpp/new_.d
  src/core/stdcpp/type_traits.d
  test/stdcpp/Makefile
  test/stdcpp/src/memory.cpp
  test/stdcpp/src/memory_test.d
  test/stdcpp/win64.mak
Labels: auto-merge-squash

#2889 Disable `make install` for the Darwin_64_32 target on the auto-tester
  posix.mak
Labels: auto-merge
