Repository dlang/druntime, pull requests merged in 2019-09, with the labels that each got.

#2781 Replace `in` with `scope const` in `rt.aaA.d`
  src/object.d
  src/rt/aaA.d
Labels: auto-merge

#2783 Remove core.internal documentation that only contain symbols for the compiler
  mak/DOCS
  posix.mak
Labels: auto-merge

#2778 Fix Issue 16380 - no bindings for err.h
  mak/COPY
  mak/SRCS
  mak/WINDOWS
  src/core/sys/bionic/err.d
  src/core/sys/darwin/err.d
  src/core/sys/dragonflybsd/err.d
  src/core/sys/freebsd/err.d
  src/core/sys/linux/err.d
  src/core/sys/netbsd/err.d
  src/core/sys/openbsd/err.d
  src/core/sys/solaris/err.d
Labels: 72h no objection -> merge, Bug Fix, auto-merge

#2727 Serialize rdtsc instruction on x86_64
  src/rt/trace.d
Labels: 72h no objection -> merge, auto-merge

#2755 Issue 20155 - Allocating a struct with dtor on the GC heap can produce false pointers
  src/rt/lifetime.d
Labels: Bug Fix, auto-merge

#2789 POSIX: Add core.sys.posix.{string,strings,locale}
  mak/COPY
  mak/SRCS
  mak/WINDOWS
  src/core/stdc/string.d
  src/core/sys/posix/locale.d
  src/core/sys/posix/string.d
  src/core/sys/posix/strings.d
Labels: auto-merge

#2790 demangle.d: remove use of lazy
  src/core/demangle.d
Labels: Refactoring, auto-merge

#2689 core.thread refactor: osthread module
  mak/COPY
  mak/DOCS
  mak/SRCS
  mak/WINDOWS
  posix.mak
  src/core/internal/spinlock.d
  src/core/thread/fiber.d
  src/core/thread/osthread.d
  src/core/thread/package.d
Labels: auto-merge

#2798 fix Issue 20214 - GC: realloc can result in false pointers if address…
  src/gc/impl/conservative/gc.d
Labels: Bug Fix, auto-merge

#2799 Revert "core.thread refactor: osthread module"
  mak/COPY
  mak/DOCS
  mak/SRCS
  mak/WINDOWS
  posix.mak
  src/core/internal/spinlock.d
  src/core/thread.d
  src/core/thread/fiber.d
  src/core/thread/package.d
Labels: auto-merge

#2801 fix issue 13821 - fiber + exception + win server 2012 failures
  src/core/thread.d
Labels: Bug Fix, auto-merge

#2784 Partially revert some changes to object.d: destroy and array capacity functions
  mak/DOCS
  posix.mak
  src/core/internal/array/capacity.d
  src/core/internal/destruction.d
  src/object.d
Labels: auto-merge

#2807 fix Appveyor build for stable (needs dmd stable)
  appveyor.yml
Labels: auto-merge

#2805 fix Issue 20227 - "Error: phread_mutex_destroy failed." after fork()
  src/core/thread.d
  src/gc/impl/conservative/gc.d
  test/gc/Makefile
  test/gc/forkgc.d
Labels: Bug Fix, auto-merge

#2802 Issue 20219 - Idle D programs keep consuming CPU in Gcx.scanBackground
  src/gc/impl/conservative/gc.d
Labels: Bug Fix, auto-merge

#2808 Make wstatus predicates pure and @safe
  changelog/wait_attributes.dd
  src/core/sys/posix/sys/wait.d
Labels: auto-merge
