Repository dlang/druntime, pull requests merged in 2019-02, with the labels that each got.

#2481 core.sys.posix.sys.stat: Fix stat_t for musl
  src/core/sys/posix/sys/stat.d
Labels: auto-merge

#2484 precisegc.d: copy-pasta bug fix
  test/gc/precisegc.d
Labels: auto-merge

#2487 Add rusage struct for musl
  src/core/sys/posix/sys/resource.d
Labels: System Headers, auto-merge

#2489 [dmd-cxx] Backport NetBSD and mbstate_t patches
  src/core/internal/convert.d
  src/core/stdc/assert_.d
  src/core/stdc/stdio.d
  src/core/stdc/wchar_.d
  src/core/sys/netbsd/dlfcn.d
Labels: System Headers, auto-merge

#2490 [dmd-cxx] GCC bug 88127: qsort_r is not available in old glibc
  src/rt/qsort.d
Labels: System Headers, auto-merge

#1924 implement open GC registry
  changelog/gc_registry.dd
  mak/SRCS
  src/gc/config.d
  src/gc/gcinterface.d
  src/gc/impl/conservative/gc.d
  src/gc/impl/manual/gc.d
  src/gc/proxy.d
  src/gc/registry.d
  test/init_fini/Makefile
  test/init_fini/src/custom_gc.d
  test/init_fini/win64.mak
  win64.mak
Labels: GC, auto-merge

#2466 Replace module-level data with Meyers singletons
  src/rt/sections_elf_shared.d
Labels: 72h no objection -> merge

#2463 Add support for the in operator in dassert
  src/core/internal/dassert.d
  test/exceptions/src/assert_fail.d
Labels: auto-merge

#2488 [uClibc][core.sys.linux.sys.eventfd] Fix definitions for mips and sparc
  src/core/sys/linux/sys/eventfd.d
Labels: auto-merge

#2493 test/shared: Support more platforms in test
  test/shared/src/load.d
Labels: auto-merge

#2496 RISCV: Fix stat_t definition to match AArch64
  src/core/sys/posix/sys/stat.d
Labels: System Headers, auto-merge

#2497 Disable OSX-32 on the auto-tester
  posix.mak
Labels: auto-merge
