Repository dlang/druntime, pull requests merged in 2019-08, with the labels that each got.

#2708 std::vector fixes
  src/core/stdcpp/vector.d
  test/stdcpp/src/vector.cpp
  test/stdcpp/src/vector_test.d
Labels: auto-merge

#2712 std::string improvements
  changelog/std_string.dd
  src/core/stdcpp/string.d
  test/stdcpp/src/string_test.d
Labels: auto-merge

#2713 Fix shared libraries for LDC on macOS
  mak/DOCS
  mak/SRCS
  src/rt/sections_elf_shared.d
  src/rt/sections_osx_x86_64.d
  src/rt/util/utility.d
Labels: auto-merge

#2714 [stable] Follow-up on #2713
  src/rt/sections_osx_x86_64.d
  src/rt/util/utility.d
Labels: auto-merge

#2716 Clang std::string
  src/core/stdcpp/allocator.d
  src/core/stdcpp/array.d
  src/core/stdcpp/string.d
  src/core/stdcpp/string_view.d
  src/core/stdcpp/xutility.d
  test/stdcpp/Makefile
Labels: auto-merge

#2717 std::string GCC tests
  test/stdcpp/Makefile
Labels: auto-merge

#2711 Merge remote-tracking branch 'upstream/stable' into merge_stable
  CODEOWNERS
  changelog/darwin-loader.dd
  posix.mak
  src/core/internal/hash.d
  src/core/runtime.d
  src/core/sync/condition.d
  src/core/sys/darwin/mach/loader.d
  src/object.d
  src/rt/osx_tls.c
  src/rt/sections_osx_x86_64.d
  test/hash/src/test_hash.d
Labels: Bug Fix, auto-merge

#2719 Fix string tests not running
  changelog/std_string.dd
  src/core/stdcpp/string.d
  test/stdcpp/Makefile
  test/stdcpp/src/string_test.d
Labels: auto-merge

#2721 Fix Issue 20066 - Assertion on void[] does not compile with -checkaction=context
  src/core/internal/dassert.d
  test/exceptions/src/assert_fail.d
Labels: Bug Fix, auto-merge

#2386 POSIX `free` purity
  src/core/memory.d
Labels: 72h no objection -> merge, auto-merge

#2725 Merge remote-tracking branch 'upstream/stable' into merge_stable
  changelog/darwin-loader.dd
  mak/DOCS
  mak/SRCS
  src/rt/sections_elf_shared.d
  src/rt/sections_osx_x86_64.d
  src/rt/util/utility.d
Labels: auto-merge

#2705 Make TempStringNoAlloc a template
  src/core/internal/string.d
  test/betterc/Makefile
  test/betterc/src/test20088.d
Labels: Bug Fix

#2728 Merge remote-tracking branch 'upstream/stable' into merge_stable
  src/core/internal/string.d
  test/betterc/Makefile
  test/betterc/src/test20088.d
Labels: Bug Fix

#2672 Add CreateSymbolicLink
  src/core/sys/windows/winbase.d
Labels: auto-merge

#2729 Added atomicExchange to core.atomic
  changelog/atomic_exchange.dd
  src/core/atomic.d
Labels: Enhancement, auto-merge

#2730 Documentation fixes in core.thread.
  src/core/thread.d
Labels: auto-merge

#2731 Allow template opCall for update
  src/object.d
Labels: auto-merge-squash

#2732 Fix typo in update docs
  src/object.d
Labels: auto-merge

#2733 Fixed the cas function not returning the result
  changelog/atomic_cas.dd
  src/core/atomic.d
Labels: Enhancement, auto-merge

#2734 Fix cas register usage
  src/core/atomic.d
Labels: auto-merge

#2737 UnicodeException.this() should be @nogc
  src/core/exception.d
Labels: Blocking Other Work, auto-merge

#2735 Further improve cas functions
  changelog/atomic_fetch_add.dd
  src/core/atomic.d
Labels: auto-merge

#2744 [Musl] Fill in empty version blocks for extern(C) bindings
  src/core/sys/posix/dirent.d
  src/core/sys/posix/pthread.d
  src/core/sys/posix/pwd.d
  src/core/sys/posix/sys/mman.d
  src/core/sys/posix/sys/socket.d
  src/core/sys/posix/sys/wait.d
Labels: System Headers, auto-merge

#2748 [dmd-cxx] [OpenBSD] Updated extern(C) bindings for minimal compilation
  src/core/stdc/assert_.d
  src/core/stdc/math.d
  src/core/stdc/stdio.d
  src/core/sys/openbsd/sys/cdefs.d
  src/core/sys/openbsd/sys/elf.d
  src/core/sys/openbsd/sys/elf32.d
  src/core/sys/openbsd/sys/elf64.d
  src/core/sys/openbsd/sys/elf_common.d
  src/core/sys/openbsd/sys/link_elf.d
  src/core/sys/openbsd/sys/mman.d
  src/core/sys/openbsd/time.d
  src/core/sys/posix/aio.d
  src/core/sys/posix/arpa/inet.d
  src/core/sys/posix/config.d
  src/core/sys/posix/net/if_.d
  src/core/sys/posix/netinet/in_.d
  src/core/sys/posix/netinet/tcp.d
  src/core/sys/posix/signal.d
  src/core/sys/posix/sys/ioctl.d
  src/core/sys/posix/sys/ipc.d
  src/core/sys/posix/sys/mman.d
  src/core/sys/posix/sys/resource.d
  src/core/sys/posix/sys/select.d
  src/core/sys/posix/sys/shm.d
  src/core/sys/posix/sys/socket.d
  src/core/sys/posix/sys/stat.d
  src/core/sys/posix/sys/statvfs.d
  src/core/sys/posix/sys/time.d
  src/core/sys/posix/sys/types.d
  src/core/sys/posix/sys/uio.d
  src/core/sys/posix/sys/un.d
  src/core/sys/posix/sys/utsname.d
  src/core/sys/posix/sys/wait.d
  src/core/sys/posix/syslog.d
  src/core/sys/posix/termios.d
  src/core/sys/posix/time.d
  src/core/sys/posix/ucontext.d
  src/core/sys/posix/unistd.d
  src/core/sys/posix/utime.d
  src/core/thread.d
  src/core/threadasm.S
  src/core/time.d
  src/gc/os.d
Labels: System Headers

#2741 [dmd-cxx] Synchronize extern(C) bindings
  mak/COPY
  mak/SRCS
  mak/WINDOWS
  src/core/stdc/assert_.d
  src/core/stdc/errno.d
  src/core/stdc/fenv.d
  src/core/stdc/stdio.d
  src/core/sys/bionic/string.d
  src/core/sys/darwin/mach/dyld.d
  src/core/sys/darwin/mach/loader.d
  src/core/sys/darwin/string.d
  src/core/sys/dragonflybsd/string.d
  src/core/sys/dragonflybsd/sys/socket.d
  src/core/sys/freebsd/string.d
  src/core/sys/freebsd/sys/elf64.d
  src/core/sys/freebsd/sys/elf_common.d
  src/core/sys/linux/sched.d
  src/core/sys/linux/string.d
  src/core/sys/netbsd/string.d
  src/core/sys/netbsd/sys/featuretest.d
  src/core/sys/openbsd/string.d
  src/core/sys/posix/aio.d
  src/core/sys/posix/dirent.d
  src/core/sys/posix/pthread.d
  src/core/sys/posix/pwd.d
  src/core/sys/posix/setjmp.d
  src/core/sys/posix/signal.d
  src/core/sys/posix/sys/ioccom.d
  src/core/sys/posix/sys/ioctl.d
  src/core/sys/posix/sys/mman.d
  src/core/sys/posix/sys/socket.d
  src/core/sys/posix/sys/ttycom.d
  src/core/sys/posix/sys/types.d
  src/core/sys/posix/sys/wait.d
  src/core/sys/posix/time.d
  src/core/sys/posix/ucontext.d
  src/core/sys/posix/unistd.d
  src/core/sys/windows/winnt.d
Labels: System Headers, Trivial

#2751 [dmd-cxx] [Musl] Remove duplicate definition of SOCK_RAW
  src/core/sys/posix/sys/socket.d
Labels: System Headers

#2750 [Musl] Remove duplicate definition of SOCK_RAW
  src/core/sys/posix/sys/socket.d
Labels: System Headers

#2742 Move some traits to druntime
  src/core/internal/traits.d
Labels: auto-merge

#2756 Remove legacy traits
  src/core/internal/arrayop.d
  src/core/internal/traits.d
  src/core/time.d
  src/rt/lifetime.d
Labels: auto-merge

#2757 Failure test was at the wrong indentation level.
  src/core/internal/atomic.d
Labels: auto-merge

#2759 Add core.internal.entrypoint to move C main generation logic out of the compiler and into druntime
  mak/COPY
  mak/SRCS
  mak/WINDOWS
  src/core/internal/entrypoint.d
  src/object.d
Labels: auto-merge

#2762 Add documentation header to core.internal.entrypoint
  src/core/internal/entrypoint.d
Labels: auto-merge

#2763 Move core.internal.arrayop.d to core.internal.array/operations.d to join other array-related files
  mak/COPY
  mak/DOCS
  mak/SRCS
  mak/WINDOWS
  src/core/internal/array/operations.d
  src/object.d
Labels: auto-merge

#2765 Move compiler switch-related hooks from object.d to core.internal.switch_.d
  mak/COPY
  mak/DOCS
  mak/SRCS
  mak/WINDOWS
  posix.mak
  src/core/internal/switch_.d
  src/object.d
Labels: auto-merge

#2764 Fix Issue 3831 - writeln of a delegate typeid
  src/object.d
Labels: Bug Fix, auto-merge

#2767 Revert "std::optional"
  changelog/std_optional.dd
  mak/COPY
  mak/DOCS
  mak/SRCS
  mak/WINDOWS
  setmscver.bat
  src/core/stdcpp/optional.d
  test/stdcpp/Makefile
  test/stdcpp/src/optional.cpp
  test/stdcpp/src/optional_test.d
Labels: auto-merge

#2766 Move _d_assert_fail from object.d to core.internal.dassert.d
  mak/DOCS
  posix.mak
  src/core/internal/dassert.d
  src/object.d
Labels: auto-merge

#2768 Demphasize runtime hooks in object.d's documentation
  src/object.d
Labels: auto-merge

#2769 Move __move_post_blt from object.d to core.internal.moving.d
  mak/COPY
  mak/DOCS
  mak/SRCS
  mak/WINDOWS
  posix.mak
  src/core/internal/moving.d
  src/object.d
Labels: auto-merge

#2772 Move destroy and postblit features to core.internal
  mak/COPY
  mak/DOCS
  mak/SRCS
  mak/WINDOWS
  posix.mak
  src/core/internal/array/construction.d
  src/core/internal/destruction.d
  src/core/internal/postblit.d
  src/object.d
Labels: auto-merge

#2773 Fix Issue 13826 - Move volatileLoad/Store to core.volatile when the volatile keyword is removed
  mak/COPY
  mak/DOCS
  mak/SRCS
  mak/WINDOWS
  src/core/bitop.d
  src/core/volatile.d
Labels: Enhancement, auto-merge

#2774 Remove some unused code from object.d
  src/object.d
Labels: auto-merge

#2771 Undocument public templates in object.d that are only intended for use by the compiler
  src/object.d
Labels: auto-merge

#2775 Move compiler-support code in object.d to the bottom of the file with the others
  src/object.d
Labels: auto-merge

#2776 Reorganzie a few things in object.d so similar constructs are found next to each other
  src/object.d
Labels: auto-merge

#2745 Renovate core.atomic, improve and simplify the constraints on functions
  src/core/atomic.d
Labels: Enhancement, auto-merge
