Repository dlang/druntime, pull requests merged in 2019-04, with the labels that each got.

#2535 Remove _d_arraycast
  mak/DOCS
  mak/SRCS
  src/rt/arraycast.d
Labels: auto-merge

#2537 Remove no longer needed _adEq
  src/rt/adi.d
Labels: auto-merge

#2534 [dmd-cxx] Fix Issue 19481: mutex.d(95) Error: pthread_mutex_init failed
  src/core/internal/traits.d
  src/core/thread.d
Labels: Bug Fix

#2536 Remove no longer needed src/rt/obj.d
  mak/DOCS
  mak/SRCS
  src/rt/obj.d
Labels: auto-merge

#2494 rt: Remove some unused compiler helpers
  src/object.d
  src/rt/adi.d
Labels: auto-merge

#2538 Add explicit cast in stc/core/stdcpp/array.d
  src/core/stdcpp/array.d
Labels: auto-merge

#2540 Remove no longer needed _d_switch_error
  src/core/exception.d
Labels: auto-merge

#2541 Resolve deprecation warning for 32 byte vectors
  src/core/simd.d
Labels: auto-merge

#2522 [uclibc] add aio defs
  src/core/sys/posix/aio.d
Labels: auto-merge

#2539 Slight simplification in core.internal.hash
  src/core/internal/hash.d
Labels: auto-merge

#2533 allow lowlevel thread creation to fail
  src/core/sys/windows/dll.d
  src/core/thread.d
Labels: auto-merge

#2530 GC: keep list of small pages to recover, defer into malloc
  benchmark/gcbench/vdparser.d
  src/gc/impl/conservative/gc.d
  src/gc/pooltable.d
Labels: auto-merge

#2543 Merge remote-tracking branch 'upstream/stable' into merge_stable
  src/object.d
Labels: auto-merge, stable -> master

#2545 core/stdc/stdio.d: Remove fseeko declaration for Musl.
  src/core/stdc/stdio.d
Labels: System Headers, auto-merge

#2544 core/sync/mutex.d: Solaris is not a well behaved C runtime
  src/core/sync/mutex.d
Labels: auto-merge

#2546 core/sys/posix/stdio.d: Add LARGEFILE support for Solaris i386
  src/core/sys/posix/stdio.d
Labels: System Headers, auto-merge

#2547 hashOf of delegate: allow CTFE when null plus don't need to use bytesHash
  src/core/internal/hash.d
Labels: auto-merge

#2549 core/sys/solaris: Add nogc to dlfcn, fix Elfxx_Dyn declarations.
  src/core/sys/solaris/dlfcn.d
  src/core/sys/solaris/sys/link.d
Labels: System Headers, auto-merge

#1982 Make deprecation warnings compile errors
  posix.mak
  src/core/internal/arrayop.d
  src/core/sync/event.d
  src/core/time.d
  src/rt/lifetime.d
Labels: Bug Fix, Trivial, auto-merge-squash

#2548 Suppress object.RTInfoImpl global if aggregate contains no pointers
  src/object.d
  src/rt/aaA.d
Labels: auto-merge

#2550 Fix Issue 19796 - wrong assumption of integral element type
  src/core/internal/arrayop.d
Labels: Bug Fix, auto-merge

#2551 Fix Windows compile error
  src/core/sys/windows/shlobj.d
Labels: auto-merge

#2553 Fix extern(C) bindings for Solaris 11/SPARC
  src/core/sys/posix/ucontext.d
  src/core/sys/solaris/link.d
  src/core/thread.d
Labels: System Headers, auto-merge

#2556 core.sys.bsd.execinfo: Add version BacktraceExternal for using libexecinfo backtrace
  src/core/runtime.d
  src/core/sys/dragonflybsd/execinfo.d
  src/core/sys/freebsd/execinfo.d
  src/core/sys/netbsd/execinfo.d
Labels: System Headers, auto-merge

#2557 core.stdc.math: Mark all non-extern functions as extern(D)
  src/core/stdc/math.d
Labels: System Headers, auto-merge

#2151 2 fixes for rt.backtrace.dwarf
  src/rt/backtrace/dwarf.d
Labels: Bug Fix

#2555 [dmd-cxx] Fix extern(C) bindings for Solaris 11/SPARC
  src/core/sys/posix/ucontext.d
  src/core/sys/solaris/link.d
  src/core/thread.d
Labels: System Headers

#2560 [dmd-cxx] core.sys.bsd.execinfo: Add version BacktraceExternal for using libexecinfo backtrace
  src/core/runtime.d
  src/core/sys/dragonflybsd/execinfo.d
  src/core/sys/freebsd/execinfo.d
  src/core/sys/netbsd/execinfo.d
Labels: System Headers

#2561 [NetBSD] core.sys.posix.spawn: Add missing aliases
  src/core/sys/posix/spawn.d
Labels: System Headers, auto-merge

#2563 [Mac OS X] core.sys.posix.spawn: Add POSIX_SPAWN_CLOEXEC_DEFAULT
  src/core/sys/posix/spawn.d
Labels: auto-merge

#2564 fix destroy for C++ classes without destructors
  src/object.d
Labels: Bug Fix, auto-merge

#2568 [SystemZ] Fix couple of druntime bindings where mismatch at runtime was found
  src/core/sys/posix/fcntl.d
  src/core/sys/posix/sys/stat.d
Labels: Blocking Other Work, System Headers, auto-merge

#2554 object: Declare private struct AA and fix aaA function signatures
  src/object.d
Labels: Blocking Other Work, Bug Fix, auto-merge

#2569 [dmd-cxx] Backport more port fixes from master
  src/core/runtime.d
  src/core/stdc/math.d
  src/core/sys/posix/fcntl.d
  src/core/sys/posix/spawn.d
  src/core/sys/posix/sys/stat.d
  src/core/thread.d
  src/rt/aApplyR.d
  src/rt/config.d
  src/rt/dmain2.d
  src/rt/monitor_.d
  src/rt/qsort.d
Labels: System Headers, auto-merge

#2571 rt.dmain2: Remove unused _d_main_args
  src/rt/dmain2.d
Labels: auto-merge

#2573 [Trivial] Change suggestion for delete to destroy in core.memory
  src/core/memory.d
Labels: Trivial, auto-merge

#2575 [dmd-cxx] Synchronize rt.backtrace with druntime master
  mak/SRCS
  src/rt/backtrace/dwarf.d
  src/rt/backtrace/elf.d
  src/rt/backtrace/macho.d
Labels: Trivial, auto-merge

#2574 [dmd-cxx] Move DMD's object.d members to druntime
  src/object.d
Labels: Trivial

#2572 [dmd-cxx] object: Declare private struct AA and fix aaA function signatures
  src/object.d
Labels: Trivial

#2577 [trivial] add string_view.toString
  src/core/stdcpp/string_view.d
Labels: Trivial, auto-merge

#2579 [dmd-cxx][AArch64] core.sys.posix.sys.stat: Fix assert for ILP32 ABI
  src/core/sys/posix/sys/stat.d
Labels: System Headers

#2578 [AArch64] core.sys.posix.sys.stat: Fix assert for ILP32 ABI
  src/core/sys/posix/sys/stat.d
Labels: System Headers, auto-merge

#2581 [dmd-cxx] core.time: Assume all clocks are missing on Linux_Pre_2639
  src/core/time.d
Labels: Trivial

#2580 core.time: Assume all clocks are missing on Linux_Pre_2639
  src/core/time.d
Labels: Trivial, auto-merge

#2585 Fix Issue 19830 - core.memory.__delete destructs arrays of structs in the wrong order
  src/core/memory.d
Labels: Bug Fix, auto-merge

#2584 core.sys.darwin.mach.dyld: Add _dyld_get_image_vmaddr_slide
  src/core/sys/darwin/mach/dyld.d
Labels: System Headers, auto-merge

#2582 Convert FreeBSD's sys/ttycom.h into core.sys.posix.sys.ttycom
  changelog/freebsd-ttycom.dd
  src/core/sys/posix/sys/ioccom.d
  src/core/sys/posix/sys/ioctl.d
  src/core/sys/posix/sys/ttycom.d
Labels: auto-merge, auto-merge-squash

#2586 [GDC] GCC9 last-minute fix: MinGW changes to get druntime to build
  src/core/stdc/stdio.d
  src/core/sys/windows/dll.d
  src/core/thread.d
  src/rt/dmain2.d
Labels: Bug Fix, auto-merge

#2589 [S390] Add druntime bindings to fix SystemZ multilib builds
  src/core/sys/linux/link.d
  src/core/sys/posix/setjmp.d
  src/core/sys/posix/sys/stat.d
  src/core/sys/posix/ucontext.d
Labels: Blocking Other Work, System Headers, auto-merge

#2590 [dmd-cxx][S390] Add druntime bindings to fix SystemZ multilib builds
  src/core/sys/linux/link.d
  src/core/sys/posix/setjmp.d
  src/core/sys/posix/sys/stat.d
  src/core/sys/posix/ucontext.d
Labels: Blocking Other Work, System Headers

#2588 Fix broken link in README
  README.md
Labels: auto-merge

#2576 [OpenBSD] Updated extern(C) bindings for minimal compilation passes.
  src/core/stdc/assert_.d
  src/core/stdc/math.d
  src/core/stdc/stdio.d
  src/core/sys/openbsd/sys/cdefs.d
  src/core/sys/openbsd/sys/elf.d
  src/core/sys/openbsd/sys/elf32.d
  src/core/sys/openbsd/sys/elf64.d
  src/core/sys/openbsd/sys/elf_common.d
  src/core/sys/openbsd/sys/link_elf.d
  src/core/sys/openbsd/sys/mman.d
  src/core/sys/openbsd/time.d
  src/core/sys/posix/aio.d
  src/core/sys/posix/arpa/inet.d
  src/core/sys/posix/config.d
  src/core/sys/posix/net/if_.d
  src/core/sys/posix/netinet/in_.d
  src/core/sys/posix/netinet/tcp.d
  src/core/sys/posix/signal.d
  src/core/sys/posix/sys/ioctl.d
  src/core/sys/posix/sys/ipc.d
  src/core/sys/posix/sys/mman.d
  src/core/sys/posix/sys/resource.d
  src/core/sys/posix/sys/select.d
  src/core/sys/posix/sys/shm.d
  src/core/sys/posix/sys/socket.d
  src/core/sys/posix/sys/stat.d
  src/core/sys/posix/sys/statvfs.d
  src/core/sys/posix/sys/time.d
  src/core/sys/posix/sys/types.d
  src/core/sys/posix/sys/uio.d
  src/core/sys/posix/sys/un.d
  src/core/sys/posix/sys/utsname.d
  src/core/sys/posix/sys/wait.d
  src/core/sys/posix/syslog.d
  src/core/sys/posix/termios.d
  src/core/sys/posix/time.d
  src/core/sys/posix/ucontext.d
  src/core/sys/posix/unistd.d
  src/core/sys/posix/utime.d
  src/core/thread.d
  src/core/threadasm.S
  src/core/time.d
  src/gc/os.d
Labels: System Headers, auto-merge

#2592 core.sys.posix.aio: CRuntime_Bionic does not implement AIO
  src/core/sys/posix/aio.d
Labels: auto-merge

#2591 Merge remote-tracking branch 'upstream/stable' into merge_stable
  src/core/memory.d
Labels: Bug Fix, auto-merge
