Repository dlang/druntime, pull requests merged in 2019-10, with the labels that each got.

#2809 Fix parameter table layout (documentation).
  src/core/simd.d
Labels: auto-merge

#2810 [stable] posix.time: Add timezone, daylight definitions for Musl
  src/core/sys/posix/time.d
Labels: auto-merge

#2806 try using dmd's azure-pipeline
  azure-pipelines.yml
Labels: auto-merge

#2813 problem with signal handling and parallel GC on linux
  src/gc/impl/conservative/gc.d
  test/gc/Makefile
  test/gc/sigmaskgc.d
Labels: Bug Fix, auto-merge

#2821 core.thread.refactor Part 1
  mak/COPY
  mak/DOCS
  mak/SRCS
  mak/WINDOWS
  posix.mak
  src/core/internal/spinlock.d
  src/core/thread/fiber.d
  src/core/thread/osthread.d
  src/core/thread/package.d
Labels: auto-merge-squash

#2817 Add fork handling to GC
  src/gc/impl/conservative/gc.d
  test/gc/Makefile
  test/gc/forkgc2.d
Labels: Bug Fix, auto-merge

#2819 Added `pause` to core.atomic
  changelog/atomic_cas.dd
  changelog/atomic_exchange.dd
  changelog/std_string.dd
  changelog/std_vector.dd
  src/core/atomic.d
  src/core/internal/atomic.d
  src/core/internal/spinlock.d
Labels: auto-merge

#2823 fix issue 13821 again
  azure-pipelines.yml
  src/core/thread/fiber.d
Labels: Bug Fix

#2758 Merge remote-tracking branch 'upstream/stable' into merge_stable
  appveyor.yml
  changelog/atomic-msync.dd
  changelog/atomic_cas.dd
  changelog/atomic_exchange.dd
  changelog/clock-monotonic.dd
  changelog/dlfcn-posix.dd
  changelog/exception-hiddenfunc.dd
  changelog/exception-setasserthandler.dd
  changelog/fiber-call.dd
  changelog/netinet-tcp.dd
  changelog/runtime-initerm.dd
  changelog/std_string.dd
  changelog/std_vector.dd
  src/core/runtime.d
  src/core/sys/posix/time.d
  src/core/sys/posix/unistd.d
  src/core/thread/osthread.d
  src/gc/impl/conservative/gc.d
  src/rt/lifetime.d
  src/rt/sections_android.d
  src/rt/sections_elf_shared.d
  test/gc/Makefile
  test/gc/forkgc.d
  test/gc/forkgc2.d
  test/gc/sigmaskgc.d
Labels: Bug Fix

#2827 -checkaction=context: Fix recursive struct formatting
  src/core/internal/dassert.d
  test/exceptions/src/assert_fail.d
Labels: auto-merge

#2411 Fix Issue 19481: mutex.d(95) Error: pthread_mutex_init failed
  src/core/internal/traits.d
  src/core/thread/osthread.d
Labels: Blocking Other Work, Bug Fix

#2829 core/atomic.d: Fix-up both public and internal API
  src/core/atomic.d
  src/core/internal/atomic.d
Labels: auto-merge

#2830 core/thread/fiber.d: Remove pragma(msg) from unittest
  src/core/thread/fiber.d
Labels: auto-merge

#2832 Fix Issue 20299: checkaction=context not working with temporary destr…
  src/core/internal/dassert.d
  test/exceptions/src/assert_fail.d
Labels: Bug Fix

#2839 Add CLONE_VFORK
  src/core/sys/linux/sched.d
Labels: System Headers, auto-merge

#2841 Fix Issue 20323 - checkaction=context fails for non-copyable arguments
  src/core/internal/dassert.d
  test/exceptions/src/assert_fail.d
Labels: Bug Fix

#2835 [stable] core.atomic: Make type repainting in atomicLoad cheaper
  src/core/atomic.d
Labels: auto-merge

#2837 Fix Issue 20315 - checkaction=context fails for const(void[]) argument
  src/core/internal/dassert.d
  test/exceptions/src/assert_fail.d
Labels: Bug Fix, auto-merge

#2840 Fix Issue 20322 - checkaction=context fails for wstring/dstring arguments
  src/core/internal/dassert.d
  test/exceptions/src/assert_fail.d
Labels: Bug Fix, auto-merge

#2816 fix Issue 20270 - [REG2.087] Deadlock in garbage collection when runn…
  src/core/thread/osthread.d
  src/gc/impl/conservative/gc.d
  test/gc/Makefile
  test/gc/startbackgc.d
Labels: Bug Fix, auto-merge
