Repository dlang/druntime, pull requests merged in 2019-07, with the labels that each got.

#2656 Translate _d_arraysetlengthT to template
  src/object.d
  src/rt/array/capacity.d
Labels: auto-merge

#2034 Switch linkage of ___tls_get_addr to extern(C).
  src/rt/sections_osx_x86.d
Labels: auto-merge

#2657 Merge remote-tracking branch 'upstream/stable' into merge_stable
  changelog/freebsd-ttycom.dd
  changelog/gc_parallel.dd
  changelog/linux-clone-unshare.dd
  posix.mak
  src/core/cpuid.d
  test/cpuid/Makefile
  test/cpuid/src/cpuid.d
  test/cpuid/win64.mak
  win32.mak
  win64.mak
Labels: Bug Fix, auto-merge

#2660 Replace opIn_r with opBinaryRight in hashtab.d
  src/rt/util/container/hashtab.d
Labels: auto-merge

#2661 Fix Issue 20026 - retrying while pthread_cond_signal/pthread_cond_broadcast…
  src/core/sync/condition.d
Labels: Bug Fix, auto-merge

#2651 Remove the newly-added core.internal.traits.isStaticArray
  src/core/internal/traits.d
  src/object.d
Labels: auto-merge

#2326 Move non-standard DragonflyBSD AF and PF constants to core.sys.dragonflybsd
  src/core/sys/dragonflybsd/sys/socket.d
  src/core/sys/posix/sys/socket.d
Labels: auto-merge

#2663 Add common base for core.experimental
  posix.mak
  win32.mak
  win64.mak
Labels: auto-merge

#2665 Add all missing symbols to `loader.d`
  changelog/darwin-loader.dd
  src/core/sys/darwin/mach/loader.d
Labels: Blocking Other Work, Bug Fix, auto-merge

#2658 Add support for pthread_condattr_setclock/pthread_condattr_getclock
  src/core/sys/posix/pthread.d
Labels: auto-merge

#2667 Move _d_arraysetlengthT* into a template to always instantiate both
  src/object.d
  src/rt/array/capacity.d
Labels: auto-merge

#2670 Issue 20034 [Reg 2.087.0] hashOf of a non-scalar enum doesn't compile
  src/core/internal/hash.d
  test/hash/src/test_hash.d
Labels: auto-merge

#2655 Translate _d_array{,set}ctor to templates
  mak/COPY
  mak/DOCS
  mak/SRCS
  mak/WINDOWS
  src/object.d
  src/rt/array/construction.d
Labels: auto-merge

#2668 Link to 32-bit inode symbols on FreeBSD
  src/core/sys/freebsd/sys/event.d
  src/core/sys/freebsd/sys/mount.d
  src/core/sys/posix/dirent.d
  src/core/sys/posix/sys/stat.d
  src/core/sys/posix/sys/statvfs.d
Labels: auto-merge

#2648 Add templated _d_arraycatnTX with tests
  mak/COPY
  mak/DOCS
  mak/SRCS
  mak/WINDOWS
  src/object.d
  src/rt/array/concatenation.d
Labels: auto-merge-squash

#2675 Fix issue 20048: Unittest printing fails on Windows when using msvcr100.dll
  src/core/runtime.d
Labels: Bug Fix, Enhancement, auto-merge

#2674 Fix issue 20049 - object.destroy doesn't propagate attributes
  src/object.d
Labels: Enhancement, auto-merge

#2678 Make the UDA visible in the generated docs
  src/core/attribute.d
Labels: auto-merge

#2681 Move rt.array to core.internal.array
  mak/COPY
  mak/DOCS
  mak/SRCS
  mak/WINDOWS
  posix.mak
  src/core/internal/array/capacity.d
  src/core/internal/array/casting.d
  src/core/internal/array/comparison.d
  src/core/internal/array/concatenation.d
  src/core/internal/array/construction.d
  src/core/internal/array/equality.d
  src/core/internal/array/utils.d
  src/core/internal/util/array.d
  src/core/thread.d
  src/object.d
  src/rt/arrayassign.d
  src/rt/arraycat.d
  test/profile/mytrace.def.exp
Labels: auto-merge

#2682 core.internal.array: Fix "Source code" links in docs
  src/core/internal/array/capacity.d
  src/core/internal/array/casting.d
  src/core/internal/array/comparison.d
  src/core/internal/array/concatenation.d
  src/core/internal/array/construction.d
  src/core/internal/array/equality.d
  src/core/internal/array/utils.d
Labels: auto-merge

#2680 Replace `in` with `const scope` in `core.stdc`
  src/core/stdc/fenv.d
  src/core/stdc/inttypes.d
  src/core/stdc/locale.d
  src/core/stdc/stdio.d
  src/core/stdc/wchar_.d
  src/core/stdc/wctype.d
Labels: auto-merge

#2684 Replace `in` with `const scope` in `core.sys.darwin`
  src/core/sys/darwin/dlfcn.d
  src/core/sys/darwin/mach/dyld.d
  src/core/sys/darwin/mach/getsect.d
  src/core/sys/darwin/pthread.d
  src/rt/sections_osx_x86.d
  src/rt/sections_osx_x86_64.d
Labels: auto-merge

#2686 Renamed HookTraceImpl to _d_HookTraceImpl
  src/core/internal/array/capacity.d
  src/core/internal/array/concatenation.d
  src/core/internal/array/utils.d
Labels: auto-merge

#2632 Translate _d_arrayappend{T,cTX} to templates
  mak/COPY
  mak/DOCS
  mak/SRCS
  mak/WINDOWS
  src/core/internal/array/appending.d
  src/core/internal/array/utils.d
  src/object.d
  src/rt/lifetime.d
Labels: auto-merge-squash

#2691 Test fix for 19831
  src/rt/dwarfeh.d
Labels: auto-merge

#2693 Replace some usages of `in` with `const scope` for object.d and rt/dmain2.d
  src/object.d
  src/rt/dmain2.d
Labels: auto-merge

#2694 Replace `in` with `const scope` for src/core/sys/linux
  src/core/sys/linux/dlfcn.d
  src/core/sys/linux/sys/xattr.d
Labels: auto-merge

#2695 Replace `in` with `const scope` for src/core/sys/solaris
  src/core/sys/solaris/dlfcn.d
  src/core/sys/solaris/libelf.d
  src/core/sys/solaris/link.d
Labels: auto-merge

#2698 Replace `in` with `const scope` for src/core/sys/posix/arpa|net|netinet
  src/core/sys/posix/arpa/inet.d
  src/core/sys/posix/net/if_.d
  src/core/sys/posix/netinet/in_.d
Labels: auto-merge

#2697 Replace `in` with `const scope` for src/core/sys/posix/sys
  src/core/sys/posix/sys/ipc.d
  src/core/sys/posix/sys/mman.d
  src/core/sys/posix/sys/resource.d
  src/core/sys/posix/sys/select.d
  src/core/sys/posix/sys/shm.d
  src/core/sys/posix/sys/socket.d
  src/core/sys/posix/sys/stat.d
  src/core/sys/posix/sys/time.d
  src/core/sys/posix/sys/uio.d
Labels: auto-merge

#2699 Replace `in` with `const scope` for src/core/sys/posix
  src/core/sys/posix/dirent.d
  src/core/sys/posix/dlfcn.d
  src/core/sys/posix/fcntl.d
  src/core/sys/posix/grp.d
  src/core/sys/posix/iconv.d
  src/core/sys/posix/inttypes.d
  src/core/sys/posix/pthread.d
  src/core/sys/posix/pwd.d
  src/core/sys/posix/sched.d
  src/core/sys/posix/semaphore.d
  src/core/sys/posix/signal.d
  src/core/sys/posix/stdio.d
  src/core/sys/posix/stdlib.d
  src/core/sys/posix/termios.d
  src/core/sys/posix/time.d
  src/core/sys/posix/ucontext.d
  src/core/sys/posix/unistd.d
  src/core/sys/posix/utime.d
Labels: auto-merge

#2700 windows: cleanup copied import folders
  mak/WINDOWS
Labels: auto-merge

#2701 [Windows] rt.dmain2: Add _d_wrun_main for wide C entry points
  src/rt/dmain2.d
Labels: auto-merge

#2702 Replace `in` with `const` and `const scope` for src/core/internal
  src/core/internal/array/construction.d
  src/core/internal/arrayop.d
  src/core/internal/parseoptions.d
  src/core/internal/utf.d
  src/core/internal/util/array.d
Labels: auto-merge

#2703 Refactor stdcpp tests makefile
  test/common.mak
  test/stdcpp/Makefile
Labels: auto-merge

#2696 Replace `in` with `const` and `const scope` for src/core/sys/windows
  src/core/sys/windows/stacktrace.d
  src/core/sys/windows/winldap.d
  src/core/sys/windows/winreg.d
  src/core/sys/windows/winuser.d
Labels: auto-merge

#2704 Replace `in` with `const` and `const scope` in core
  src/core/bitop.d
  src/core/gc/gcinterface.d
  src/core/internal/utf.d
  src/core/memory.d
  src/core/runtime.d
  src/core/time.d
Labels: auto-merge

#2448 std::vector
  changelog/std_vector.dd
  mak/COPY
  mak/DOCS
  mak/SRCS
  mak/WINDOWS
  src/core/stdcpp/vector.d
  test/stdcpp/Makefile
  test/stdcpp/src/vector.cpp
  test/stdcpp/src/vector_test.d
  test/stdcpp/win64.mak
Labels: auto-merge

#2707 Enable C++17 tests
  setmscver.bat
  src/core/stdcpp/new_.d
  test/stdcpp/src/new_test.d
  test/stdcpp/win64.mak
Labels: auto-merge

#2706 Replace `in` with `const scope` for gc implementations
  src/core/gc/gcinterface.d
  src/core/memory.d
  src/gc/impl/conservative/gc.d
  src/gc/impl/manual/gc.d
  src/gc/impl/proto/gc.d
  src/gc/proxy.d
  test/init_fini/src/custom_gc.d
Labels: Attributes, auto-merge
