Repository dlang/druntime, pull requests merged in 2019-06, with the labels that each got.

#2622 Issue 19561 - Enable array ops in betterC
  src/core/internal/arrayop.d
  test/betterc/Makefile
  test/betterc/src/test19561.d
Labels: auto-merge

#2627 [Trivial] Fix indentation in core.simd
  src/core/simd.d
Labels: Trivial, auto-merge

#2629 gc: Remove resetThreadLocalStats()
  src/core/gc/gcinterface.d
  src/core/memory.d
  src/gc/impl/conservative/gc.d
  src/gc/impl/manual/gc.d
  src/gc/impl/proto/gc.d
  src/gc/proxy.d
  src/rt/tracegc.d
  test/init_fini/src/custom_gc.d
Labels: auto-merge

#2630 Add a sponsorship button
  .github/FUNDING.yml
Labels: auto-merge

#2625 Add pthread/math libraries to a couple more rules
  posix.mak
Labels: auto-merge

#2631 Fix link (improper use of LINK2 macro).
  src/core/thread.d
Labels: auto-merge

#2635 Remove unnecessary copy in hashOf(T) for enum
  src/core/internal/hash.d
Labels: auto-merge

#2640 Merge remote-tracking branch 'upstream/stable' into merge_stable
  src/core/sys/windows/winldap.d
  src/core/sys/windows/winnt.d
  src/gc/impl/conservative/gc.d
  src/object.d
  src/rt/dwarfeh.d
  test/exceptions/Makefile
  test/exceptions/src/catch_in_finally.d
Labels: Bug Fix

#2641 Issue 19975 - object.opEquals(Object lhs, Object rhs) can skip typeid comparison when !lhs.opEquals(rhs)
  src/object.d
Labels: auto-merge

#2634 Refactor object.d: Move __cmp and __equals to rt
  mak/COPY
  mak/SRCS
  mak/WINDOWS
  src/object.d
  src/rt/array/comparison.d
  src/rt/array/equality.d
  test/profile/mytrace.def.exp
Labels: auto-merge

#2644 object.d: Move __ArrayEq to rt
  src/object.d
  src/rt/array/equality.d
Labels: auto-merge

#2643 Refactor object.d: Move __ArrayCast to rt
  mak/COPY
  mak/SRCS
  mak/WINDOWS
  src/object.d
  src/rt/array/casting.d
Labels: auto-merge

#2645 Add documentation, example, and make code for defaultTraceHandler more readable
  src/core/runtime.d
Labels: auto-merge

#2647 Refactor objectd: Move array capacity functions to rt/array/capacity.d
  mak/COPY
  mak/DOCS
  mak/SRCS
  mak/WINDOWS
  posix.mak
  src/object.d
  src/rt/array/capacity.d
Labels: auto-merge

#2649 Refactor object.d: Move isStaticArray to core.internal.traits
  src/core/internal/traits.d
  src/object.d
Labels: auto-merge

#2650 Do not execute commands from any .gdbinit initialization files
  test/exceptions/Makefile
Labels: auto-merge

#2653 Add documentation for array runtime lowerings for the internal API docs
  mak/DOCS
  posix.mak
  src/object.d
Labels: auto-merge, documentation

#2654 Remove a bunch of old deprecated symbols
  changelog/atomic-msync.dd
  changelog/clock-monotonic.dd
  changelog/dlfcn-posix.dd
  changelog/exception-hiddenfunc.dd
  changelog/exception-setasserthandler.dd
  changelog/fiber-call.dd
  changelog/netinet-tcp.dd
  changelog/runtime-initerm.dd
  mak/COPY
  mak/SRCS
  mak/WINDOWS
  src/core/atomic.d
  src/core/exception.d
  src/core/runtime.d
  src/core/sys/linux/sys/netinet/tcp.d
  src/core/sys/posix/dlfcn.d
  src/core/sys/posix/time.d
  src/core/thread.d
Labels: Deprecation, auto-merge

#2642 Issue 19976 - Simplify std.internal.convert.toUbyte CTFE path for float and double
  src/core/internal/convert.d
Labels: Enhancement, auto-merge

#2620 fix Issue 19861 - core.cpuid reports the wrong number of threads
  posix.mak
  src/core/cpuid.d
  test/cpuid/Makefile
  test/cpuid/src/cpuid.d
  test/cpuid/win64.mak
  win32.mak
  win64.mak
Labels: Bug Fix, auto-merge

#2638 Implement druntime side of DIP1014
  src/core/internal/traits.d
  src/object.d
Labels: auto-merge-squash
