Repository dlang/druntime, pull requests merged in 2019-01, with the labels that each got.

#2431 Add CPU_COUNT
  changelog/cpu_count.dd
  src/core/sys/linux/sched.d
Labels: auto-merge

#2430 GC: keep track of the size of contiguous free pages to avoid loops
  src/gc/impl/conservative/gc.d
Labels: auto-merge

#2434 Merge remote-tracking branch 'upstream/stable' into merge_stable
  changelog/array.dd
  changelog/crt_externs.dd
  changelog/destroy_noinit.dd
  changelog/string_view.dd
  src/core/runtime.d
  test/shared/src/loadlibwin.d
  win64.mak
Labels: Bug Fix, auto-merge

#2437 fix spurious crashes/freezes due to corruption in GC.realloc caused by #2430
  src/gc/impl/conservative/gc.d
Labels: auto-merge

#2436 fix Issue 11393 - [GC] GC realloc and free don't ignore interior pointers
  changelog/gc_realloc.dd
  src/core/memory.d
  src/gc/impl/conservative/gc.d
  src/rt/lifetime.d
Labels: Bug Fix, auto-merge

#2439 Add C++ type_traits
  mak/COPY
  mak/DOCS
  mak/SRCS
  mak/WINDOWS
  src/core/stdcpp/type_traits.d
Labels: auto-merge

#2398 Move `emplace` to druntime for symmetry with `destroy`.
  changelog/emplace.dd
  mak/COPY
  mak/DOCS
  mak/SRCS
  mak/WINDOWS
  src/core/internal/traits.d
  src/core/lifetime.d
Labels: auto-merge

#2332 Add access to GC runtime profile stats
  changelog/core-memory-gc-profile-stats.dd
  mak/COPY
  mak/SRCS
  src/core/memory.d
  src/core/sys/freebsd/pthread_np.d
  src/gc/gcinterface.d
  src/gc/impl/conservative/gc.d
  src/gc/impl/manual/gc.d
  src/gc/impl/proto/gc.d
  src/gc/proxy.d
Labels: Enhancement, GC, auto-merge

#2091 zero class storage when initializer is null
  src/core/thread.d
Labels: auto-merge

#2445 Don't avoid sign-extension when hashing byte/short/int
  src/core/internal/hash.d
  src/rt/typeinfo/ti_byte.d
  src/rt/typeinfo/ti_cent.d
  src/rt/typeinfo/ti_int.d
  src/rt/typeinfo/ti_long.d
  src/rt/typeinfo/ti_short.d
Labels: auto-merge

#2451 Fix Issue 19562 - core.internal.hash.hashOf array of pointers or delegates should be `@safe`
  src/core/internal/convert.d
  test/hash/src/test_hash.d
Labels: Bug Fix, auto-merge

#2452 dmangle.d: add 'return' to constructor args
  src/core/demangle.d
Labels: Blocking Other Work, auto-merge

#2440 GC cleanup can now be configured as a DRT GC option
  changelog/gc_cleanup.dd
  src/gc/config.d
  src/gc/proxy.d
Labels: 72h no objection -> merge, needs spec PR

#2454 Support nothrow new
  src/core/stdcpp/new_.d
Labels: auto-merge

#2457 Tidied `core.stdcpp.array` a bit.
  src/core/stdcpp/array.d
Labels: auto-merge

#2458 Fix issue 19571
  src/core/sys/windows/commctrl.d
Labels: auto-merge

#2455 Overhaul of std::exception
  mak/SRCS
  src/core/stdcpp/exception.d
  src/core/stdcpp/new_.d
Labels: auto-merge

#2413 _d_assert_fail: Add formatting for Assertion errors
  changelog/assert.dd
  mak/COPY
  mak/SRCS
  mak/WINDOWS
  src/core/internal/dassert.d
  src/object.d
  test/exceptions/Makefile
  test/exceptions/src/assert_fail.d
Labels: auto-merge

#2453 Fix Issue 19568 - hashOf should not unnecessarily call a struct's fields' postblits & dtors in CTFE
  src/core/internal/convert.d
  test/hash/src/test_hash.d
Labels: Bug Fix, auto-merge

#2459 Move assert changelog entry to DMD
  changelog/assert.dd
Labels: Trivial, auto-merge

#2460 core.stdc.limits: Define some common filesystem limits
  src/core/stdc/limits.d
Labels: System Headers, auto-merge

#2461 Make core.internal.convert.toUbyte in CTFE for arrays work with reference type elements and not call postblits/dtors
  src/core/internal/convert.d
  test/hash/src/test_hash.d
Labels: Bug Fix, auto-merge

#2462 Add constants for file system limits for Darwin
  src/core/stdc/limits.d
Labels: auto-merge

#2465 rt: Remove side-effects from 'p[0..ci.initializer.length] = ci.initializer[]'
  src/rt/ehalloc.d
  src/rt/lifetime.d
Labels: auto-merge

#2470 core.sys.posix.aio: Use version Darwin instead of OSX
  src/core/sys/posix/aio.d
Labels: System Headers, auto-merge

#2468 gc: move debug code to the bottom of the source
  src/gc/impl/conservative/gc.d
Labels: auto-merge

#2471 [dmd-cxx] Backport: Do not include padding when hashing floating point types
  src/core/internal/convert.d
  src/core/internal/hash.d
Labels: Trivial, auto-merge

#2472 Basic NetBSD support needed to build GDC
  src/core/stdc/assert_.d
  src/core/stdc/wchar_.d
  src/core/sys/netbsd/dlfcn.d
Labels: auto-merge

#2474 [Solaris] core/stdc/wchar_.d: Move alias for mbstate_t here
  src/core/stdc/stdio.d
  src/core/stdc/wchar_.d
Labels: System Headers, auto-merge

#2475 Remove leading whitespaces in object.d
  src/object.d
Labels: auto-merge

#2477 [dmd-cxx] Backport some more binding and portability fixes
  src/core/stdc/limits.d
  src/rt/arrayassign.d
  src/rt/sections_elf_shared.d
  src/rt/sections_osx_x86.d
  src/rt/sections_osx_x86_64.d
  src/rt/sections_solaris.d
  src/rt/sections_win32.d
  src/rt/sections_win64.d
Labels: Enhancement, System Headers, auto-merge

#2478 [uClibc][trivial] add missing declaration, fix build
  src/core/sys/posix/spawn.d
Labels: auto-merge
