Repository dlang/druntime, pull requests merged in 2019-03, with the labels that each got.

#2499 Quote variables in win64.mak
  win64.mak
Labels: auto-merge

#2500 Revert "Quote variables in win64.mak"
  win64.mak
Labels: auto-merge

#2501 Disable OSX-32 on the auto-tester (build)
  posix.mak
Labels: auto-merge

#2503 Merge remote-tracking branch 'upstream/stable' into merge_stable
  changelog/core-memory-gc-profile-stats.dd
  changelog/cpp_new.dd
  changelog/cpu_count.dd
  changelog/cpu_isset.dd
  changelog/emplace.dd
  changelog/gc_cleanup.dd
  changelog/gc_precise.dd
  changelog/gc_realloc.dd
  changelog/gc_registry.dd
  changelog/std_allocator.dd
  changelog/zero_init.dd
Labels: auto-merge

#2491 move modules necessary to implement a GC to core.gc
  mak/COPY
  mak/DOCS
  mak/SRCS
  mak/WINDOWS
  posix.mak
  src/core/gc/config.d
  src/core/gc/gcinterface.d
  src/core/gc/registry.d
  src/gc/impl/conservative/gc.d
  src/gc/impl/manual/gc.d
  src/gc/impl/proto/gc.d
  src/gc/proxy.d
  test/init_fini/src/custom_gc.d
Labels: auto-merge

#2438 fix quoting in win64.mak: add them only when invoking command
  win64.mak
Labels: auto-merge

#2502 [stable] gc.impl.conservative.gc: Fix fwd declaration signature
  src/gc/impl/conservative/gc.d
  src/rt/lifetime.d
Labels: auto-merge

#2507 fix Issue 19723: wrong time values in GC.profileStats
  src/gc/impl/conservative/gc.d
Labels: Bug Fix, auto-merge

#2479 Fix Issue 19635 - -checkaction=context not working with attributes
  src/core/internal/dassert.d
  src/core/internal/traits.d
  src/object.d
  test/exceptions/src/assert_fail.d
Labels: 72h no objection -> merge, Bug Fix

#2511 [uClibc][core.sys.posix.fcntl] add O_CLOEXEC
  src/core/sys/posix/fcntl.d
Labels: auto-merge

#2510 [uClibc][core.sys.posix.sys.socket]
  src/core/sys/posix/sys/socket.d
Labels: auto-merge

#2516 fix typo in abort message
  src/core/sync/mutex.d
Labels: Trivial, auto-merge

#2515 core.sys.windows.threadaux: apply @nogc to helper functions
  src/core/sys/windows/threadaux.d
Labels: auto-merge

#2518 [stable] Get rid of superfluous 2nd global variable in object.RTInfoImpl
  src/object.d
Labels: auto-merge

#2517 add core.sync.event to be used as Windows events
  changelog/core_sync_event.dd
  mak/COPY
  mak/DOCS
  mak/SRCS
  mak/WINDOWS
  src/core/sync/config.d
  src/core/sync/event.d
Labels: auto-merge-squash

#2521 Merge remote-tracking branch 'upstream/stable' into merge_stable
  src/core/internal/dassert.d
  src/core/internal/traits.d
  src/gc/impl/conservative/gc.d
  src/object.d
  src/rt/lifetime.d
  test/exceptions/src/assert_fail.d
Labels: Bug Fix, auto-merge

#2526 [CircleCi] Fix build by using Ubuntu 18.04 as base
  .circleci/config.yml
  .circleci/run.sh
Labels: auto-merge

#2527 [CircleCi-stable] Fix build by using Ubuntu 18.04 as base
  .circleci/config.yml
  .circleci/run.sh
Labels: auto-merge

#2528 Add missing cast(string) in _d_assert_fail
  src/object.d
Labels: auto-merge

#2525 Windows: not all import folders created
  mak/WINDOWS
Labels: auto-merge

#2529 Fix implicit cast issue in stdcpp.array
  src/core/stdcpp/array.d
Labels: auto-merge

#2524 GC: optimize alloc of small object by keeping track of unused pages
  src/gc/impl/conservative/gc.d
Labels: auto-merge

#2523 GC: optimize sweeping
  src/gc/impl/conservative/gc.d
Labels: auto-merge

#2519 add lowlevel thread support
  src/core/sys/windows/dll.d
  src/core/thread.d
Labels: auto-merge

#2532 fix issue 12330 - array.reserve at compile time too
  src/object.d
Labels: Enhancement, auto-merge

#2531 Fix object.__ArrayCast error message generation so it works with CTFE
  src/object.d
Labels: auto-merge
