Repository dlang/druntime, pull requests merged in 2020-05, with the labels that each got.

#3040 [stable] Refactor core.stdc.stdarg & add support for ARM, PowerPC and MIPS (AArch64: Apple only)
  mak/COPY
  mak/SRCS
  src/core/internal/vararg/sysv_x64.d
  src/core/stdc/stdarg.d
  src/core/vararg.d
Labels: auto-merge

#3085 core.sys.posix.sys.stat: Fix typo from #3084
  src/core/sys/posix/sys/stat.d
Labels: Bug Fix, Trivial, auto-merge

#3087 Remove superflous semicolons
  src/core/internal/array/utils.d
  src/core/stdc/errno.d
  src/core/stdc/fenv.d
  src/core/stdc/stdio.d
  src/core/sys/darwin/netinet/in_.d
  src/core/sys/dragonflybsd/dlfcn.d
  src/core/sys/dragonflybsd/netinet/in_.d
  src/core/sys/dragonflybsd/sys/link_elf.d
  src/core/sys/freebsd/dlfcn.d
  src/core/sys/freebsd/netinet/in_.d
  src/core/sys/freebsd/sys/link_elf.d
  src/core/sys/linux/elf.d
  src/core/sys/linux/ifaddrs.d
  src/core/sys/linux/netinet/in_.d
  src/core/sys/linux/sys/prctl.d
  src/core/sys/netbsd/dlfcn.d
  src/core/sys/netbsd/sys/link_elf.d
  src/core/sys/openbsd/sys/link_elf.d
  src/core/sys/posix/poll.d
  src/core/sys/posix/pthread.d
  src/core/sys/posix/setjmp.d
  src/core/sys/posix/signal.d
  src/core/sys/posix/sys/socket.d
  src/core/sys/posix/sys/stat.d
  src/core/sys/posix/syslog.d
  src/core/sys/posix/ucontext.d
  src/core/sys/solaris/link.d
  src/core/sys/windows/commctrl.d
  src/core/sys/windows/mmsystem.d
  src/core/sys/windows/mshtml.d
  src/core/sys/windows/oleauto.d
  src/core/sys/windows/richole.d
  src/core/sys/windows/shlobj.d
  src/core/sys/windows/wingdi.d
  src/core/sys/windows/winnt.d
  src/core/sys/windows/wtypes.d
  src/rt/deh_win32.d
Labels: auto-merge

#3088 Fix DDOC comments in core/stdc/errno.d
  src/core/stdc/errno.d
Labels: auto-merge

#3086 [stable] core.{stdc.stdarg,vararg}: Add support for non-Apple AArch64
  mak/COPY
  mak/SRCS
  src/core/internal/vararg/aarch64.d
  src/core/internal/vararg/sysv_x64.d
  src/core/stdc/stdarg.d
  src/core/vararg.d
Labels: auto-merge

#3089 rt.backtrace.dwarf: Fix printf format for debug (DwarfDebugMachine)
  src/rt/backtrace/dwarf.d
Labels: Trivial, auto-merge

#3093 [stable] Fix regressions crept in with core.stdc.stdarg refactoring
  src/core/internal/vararg/aarch64.d
  src/core/stdc/stdarg.d
Labels: auto-merge

#3090 Start to refactor and document `rt.backtrace.dwarf`
  src/rt/backtrace/dwarf.d
Labels: auto-merge

#3092 MMapRegion: Split between typed and untyped, handle error
  src/core/internal/elf/io.d
Labels: auto-merge

#3096 TypedMMapRegion: Remove wrong duplicated assignment
  src/core/internal/elf/io.d
Labels: auto-merge

#3082 merge stable
  mak/COPY
  mak/SRCS
  mak/WINDOWS
  src/core/cpuid.d
  src/core/internal/lifetime.d
  src/core/internal/vararg/aarch64.d
  src/core/internal/vararg/sysv_x64.d
  src/core/math.d
  src/core/stdc/stdarg.d
  src/core/vararg.d
  src/object.d
  win32.mak
  win64.mak
Labels: auto-merge

#3097 Fix simd.prefetch comment
  src/core/simd.d
Labels: auto-merge

#2786 Add std::pair<>
  src/core/stdcpp/utility.d
  test/stdcpp/Makefile
  test/stdcpp/src/utility.cpp
  test/stdcpp/src/utility_test.d
  test/stdcpp/win64.mak
Labels: stdcpp

#3099 switch_.d: remove use of typesafe variadic functions
  src/core/internal/switch_.d
Labels: Refactoring

#3102 merge stable
  changelog/isbaseof.dd
  changelog/page_size.dd
Labels: auto-merge

#3105 add scope and const to variadic functions
  src/core/stdc/stdio.d
  src/core/stdc/wchar_.d
Labels: auto-merge

#3106 Fix issue 20832 - Fix ioctl request for TCSETS2
  src/core/sys/posix/sys/ioctl.d
Labels: Bug Fix, auto-merge

#3107 [dmd-cxx] fix Issue 19861 - core.cpuid reports the wrong number of threads
  src/core/cpuid.d
Labels: Bug Fix

#3108 Deprecate `object.selector`
  changelog/depercate_object_selector.dd
  src/object.d
Labels: auto-merge

#3076 Add module core.sys.darwin.sys.attr with getattrlist, setattrlist, searchfs, and related definitions
  src/core/sys/darwin/sys/attr.d
Labels: Enhancement, auto-merge

#3042 Change LCG in garbage collector treap to use full 64 bits of state instead of 48
  src/rt/util/container/treap.d
  src/rt/util/random.d
Labels: Enhancement, auto-merge

#3110 Update setup-dlang action to v1
  .github/workflows/cxx.yml
Labels: CI, auto-merge

#3112 Add explicit @system attribute to extern functions
  src/core/internal/parseoptions.d
  src/rt/config.d
  test/exceptions/src/rt_trap_exceptions.d
Labels: auto-merge

#2981 add exit_group to core.sys.linux.unistd
  changelog/add_exit_group.dd
  src/core/sys/linux/unistd.d
Labels: auto-merge

#3113 Fix issue 20852: core.sys.posix.sys.wait missing definitions on FreeBSD
  src/core/sys/posix/sys/wait.d
Labels: Bug Fix, auto-merge

#3114 Add overloads of core.sync.rwmutex.ReadWriteMutex.Reader/Writer.tryLock that take a timeout duration
  src/core/sync/rwmutex.d
Labels: Enhancement, auto-merge

#3115 Fix issue 20852: core.sys.posix.sys.wait missing definitions on FreeBSD
  src/core/sys/posix/sys/wait.d
Labels: Bug Fix

#3118 Port more efficient Filter & staticMap from dlang/phobos#7490
  src/core/internal/traits.d
Labels: auto-merge

#3111 Upstream a few things from LDC to reduce the diff
  src/core/atomic.d
  src/core/runtime.d
  src/core/simd.d
  src/core/thread/osthread.d
  src/rt/backtrace/dwarf.d
  src/rt/sections_android.d
  src/rt/sections_darwin_64.d
  src/rt/sections_elf_shared.d
  src/rt/sections_osx_x86_64.d
  src/rt/sections_win64.d
Labels: auto-merge

#3109 Fix Issue 20844 - Insufficient alignment check for 16-bytes CAS on x86_64
  src/core/atomic.d
Labels: Enhancement, auto-merge

#3065 [DIP1014] __move_post_blt: recursively call on fields that are static arrays & do not recursively call on non-field members
  src/core/internal/moving.d
Labels: Bug Fix, auto-merge

#3116 Followup to #3076: make core.sys.darwin.sys.attr.attrlist usable in betterC
  src/core/sys/darwin/sys/attr.d
Labels: auto-merge

#3119 core.stdc.[tg]math: Revise for FreeBSD
  src/core/stdc/math.d
  src/core/stdc/tgmath.d
Labels: auto-merge
