Repository dlang/druntime, pull requests merged in 2020-06, with the labels that each got.

#3121 Github CI: Update action name
  .github/workflows/cxx.yml
Labels: Trivial, auto-merge

#3122 merge stable
  src/core/sys/posix/sys/ioctl.d
Labels: Bug Fix, auto-merge

#3124 cannot inline setPointerBitmapSmall()
  src/gc/impl/conservative/gc.d
Labels: Blocking Other Work, auto-merge

#3126 fix signed multiply overflow detection
  src/core/checkedint.d
Labels: Blocking Other Work, auto-merge

#3127 [dmd-cxx] Rename foreach variable to get rid of shadowing
  src/rt/util/utf.d
Labels: auto-merge

#3120 Store memory-related GC options in bytes instead of megabytes.
  changelog/gc_suffixes.dd
  src/core/gc/config.d
  src/core/internal/parseoptions.d
  src/core/internal/traits.d
  src/gc/impl/conservative/gc.d
Labels: auto-merge

#3132 add return annotations to pure functions
  src/rt/cast_.d
  src/rt/lifetime.d
Labels: auto-merge

#3129 Fix issue 20910: fix misleading unittest runner messages.
  src/rt/dmain2.d
  test/unittest/Makefile
Labels: Bug Fix, auto-merge

#3136 core.sys.posix.ucontext: Add new ucontext_t field to save shadow stack (CET)
  src/core/sys/posix/ucontext.d
Labels: System Headers, auto-merge

#3135 Split osthread.d
  mak/COPY
  mak/SRCS
  src/core/thread/fiber.d
  src/core/thread/osthread.d
  src/core/thread/package.d
  src/core/thread/threadbase.d
  src/core/thread/threadgroup.d
  src/core/thread/types.d
Labels: auto-merge

#3140 Remove FUNDING.yml
  .github/FUNDING.yml
Labels: Trivial, auto-merge

#3146 core.thread.osthread: Re-add import gcc.builtins
  src/core/thread/osthread.d
Labels: Regression, auto-merge
