Repository dlang/druntime, pull requests merged in 2020-02, with the labels that each got.

#2921 Merge remote-tracking branch 'upstream/stable' into merge_stable
  src/core/internal/traits.d
  src/core/stdc/stdint.d
  test/shared/src/load_13414.d
Labels: Bug Fix, auto-merge

#2920 Add missing pthread_attr_init
  src/core/thread/osthread.d
Labels: auto-merge

#2922 Added missing pthread_attr_destroy one more
  changelog/add_missing_pthread_attr_destroy.dd
  src/core/thread/osthread.d
Labels: auto-merge

#2925 Don't use a priority cache per member
  src/core/thread/osthread.d
Labels: Trivial, auto-merge

#2927 Fix issue 20559: AA.clear segfault when used with alias this
  src/object.d
Labels: Bug Fix, auto-merge

#2930 Update and fix SDKDDKVERs
  src/core/sys/windows/w32api.d
Labels: auto-merge

#2929 Fix Issue 16658: Default IE version set to 6.0
  src/core/sys/windows/w32api.d
Labels: Bug Fix, auto-merge

#2928 Fix Issue 15322 - Correct versioning PENUM_PAGE_FILE_CALLBACK
  src/core/sys/windows/psapi.d
Labels: Bug Fix, auto-merge

#2919 Fix Issue 20550 - Use fixed seeds for treaps in GC
  src/gc/impl/conservative/gc.d
  src/rt/util/container/treap.d
  src/rt/util/random.d
Labels: Enhancement, auto-merge

#2933 fix Issue 20567 - GC should not start threads for parallel marking in simple programs
  src/gc/impl/conservative/gc.d
  test/gc/Makefile
  test/gc/nocollect.d
  test/gc/win64.mak
Labels: Enhancement, auto-merge

#2934 Adjust minimal stack size for thread-local storage in Glibc
  src/core/thread/osthread.d
Labels: auto-merge

#2935 Merge remote-tracking branch 'upstream/stable' into merge_stable
  src/object.d
Labels: Bug Fix, auto-merge

#2936 [Trivial] fix comment location
  src/core/thread/osthread.d
Labels: Trivial, auto-merge

#2941 [stable] Add missing core.thread to documentation
  mak/DOCS
  posix.mak
Labels: auto-merge, documentation

#2914 Add TFD_TIMER_CANCEL_ON_SET
  changelog/tfd_timer_cancel_on_set.dd
  src/core/sys/linux/timerfd.d
Labels: auto-merge

#2940 Fix #20577: Add windows symbols
  mak/COPY
  mak/SRCS
  mak/WINDOWS
  src/core/sys/windows/sdkddkver.d
  src/core/sys/windows/winbase.d
  src/core/sys/windows/winnt.d
  src/core/sys/windows/winver.d
Labels: Enhancement, auto-merge

#2942 Fix Issue 19218 - object.destroy should check for classes for static …
  src/object.d
Labels: Enhancement, auto-merge

#2944 runbench: add -mcpu=native by default
  benchmark/runbench.d
Labels: auto-merge

#2910 Add support for iOS, tvOS and watchOS
  mak/DOCS
  mak/SRCS
  src/core/stdc/assert_.d
  src/core/stdc/stdint.d
  src/core/stdcpp/string.d
  src/core/sys/darwin/mach/port.d
  src/core/sys/darwin/mach/thread_act.d
  src/core/sys/posix/locale.d
  src/core/sys/posix/sys/filio.d
  src/core/sys/posix/sys/ioccom.d
  src/core/sys/posix/sys/ttycom.d
  src/core/sys/posix/sys/types.d
  src/core/thread/osthread.d
  src/core/threadasm.S
  src/rt/dmain2.d
  src/rt/sections_darwin_64.d
  src/rt/sections_osx_x86_64.d
Labels: auto-merge

#2330 Refactor ELF utils from rt.backtrace.elf and rt.sections_elf_shared to core.internal.elf.{dl,io}
  mak/COPY
  mak/SRCS
  mak/WINDOWS
  posix.mak
  src/core/internal/elf/dl.d
  src/core/internal/elf/io.d
  src/rt/backtrace/dwarf.d
  src/rt/backtrace/elf.d
  src/rt/backtrace/macho.d
  src/rt/sections_elf_shared.d
Labels: Bug Fix, auto-merge

#2945 Print source file directory in stack traces
  src/rt/backtrace/dwarf.d
Labels: Bug Fix, auto-merge

#2948 Disable FPU fast mode for Apple ARM in test runner
  src/test_runner.d
Labels: auto-merge

#2947 fix printf format
  src/gc/impl/conservative/gc.d
  test/exceptions/src/line_trace.d
Labels: Blocking Other Work, auto-merge

#2950 long_backtrace_trunc.d: printf formats
  test/exceptions/src/long_backtrace_trunc.d
Labels: Blocking Other Work, auto-merge

#2951 more printf format fixes
  test/exceptions/src/assert_fail.d
  test/exceptions/src/chain.d
  test/exceptions/src/future_message.d
Labels: Blocking Other Work, auto-merge

#2954 Fix typo in atomic.ValidateStruct
  src/core/atomic.d
Labels: auto-merge

#2952 Add `pageSize` and `defaultPageSize`
  changelog/page_size.dd
  src/core/memory.d
Labels: auto-merge

#2961 Fiber: restore usage of VirtualAlloc
  src/core/thread/fiber.d
Labels: auto-merge

#2960 GC tests: recoverfree and nocollect should not run unittests but main
  test/gc/Makefile
  test/gc/win64.mak
Labels: auto-merge

#2956 Merge remote-tracking branch 'upstream/stable' into merge_stable
  mak/DOCS
  posix.mak
Labels: auto-merge

#2962 Fix 20613 - String switch in -betterC fails for 7+ labels
  src/core/internal/switch_.d
  test/betterc/Makefile
  test/betterc/src/test20613.d
Labels: Bug Fix, auto-merge
