Repository dlang/druntime, pull requests merged in 2020-08, with the labels that each got.

#3178 Recognize immutable in core.internal.traits : hasUnsharedIndirections
  src/core/internal/traits.d
Labels: Bug Fix, auto-merge

#3179 rt.backtrace.dwarf: Slightly refactor reading directories and source list
  src/rt/backtrace/dwarf.d
Labels: Refactoring, auto-merge

#3183 Add demangling support for 'in' storage class
  src/core/demangle.d
Labels: auto-merge

#3182 Trivial: Improve error message on mangling error
  src/core/demangle.d
Labels: auto-merge

#3095 Refactor core.atomic : cas into a two-level template
  src/core/atomic.d
Labels: Blocking Other Work, Refactoring, auto-merge

#3163 Fix issue 21055 - core.stdc.stdarg is not nogc
  src/core/stdc/stdarg.d
Labels: 72h no objection -> merge, Bug Fix

#3187 Backtrace: Change address from size_t to const(void)*
  src/rt/backtrace/dwarf.d
Labels: auto-merge

#3186 DWARF: Fix some versioned-out debug code
  src/rt/backtrace/dwarf.d
Labels: Trivial, auto-merge

#3188 Fixup PR3183: Also recognize 'in ref' in demangler
  src/core/demangle.d
Labels: auto-merge

#3185 Fix issue 21116 - Do not squirrel stack pointers away in AssertErrors.
  src/core/internal/array/casting.d
Labels: Bug Fix, auto-merge

#3191 Github Actions: Drop testing for LLVM < v6.0.0
  .github/workflows/cxx.yml
Labels: auto-merge

#3193 merge stable
  src/core/sys/linux/sys/inotify.d
  src/core/sys/linux/sys/mman.d
  src/core/sys/linux/sys/signalfd.d
  src/core/sys/linux/sys/xattr.d
  src/core/sys/posix/signal.d
Labels: auto-merge

#3194 fix bad size of operand in inline asm
  src/core/cpuid.d
Labels: Blocking Other Work, auto-merge

#3196 remove deprecated usage of a class alocator in gc benchs
  benchmark/gcbench/vdparser.extra/vdc/ast/node.d
Labels: auto-merge

#3197 Bump HOST_DMD_VERSION on Azure to avoid the gc segfault
  azure-pipelines.yml
Labels: auto-merge

#3195 Fix issue 19554 - Confusing message - Warning: struct Foo has method …
  src/core/internal/hash.d
Labels: Bug Fix, auto-merge

#3181 Reduce trait template use in core.time
  src/core/time.d
Labels: auto-merge

#3180 Reduce trait template usage in core.internal.hash core.internal.convert
  src/core/internal/convert.d
  src/core/internal/hash.d
Labels: auto-merge

#3173 unsignedToTempString no longer needs to always size the buffer for radix 2
  src/core/internal/string.d
Labels: auto-merge

#3164 Fix issue 21070: -profile=gc makes the program much slower
  changelog/faster_profilegc.dd
  src/core/gc/gcinterface.d
  src/core/memory.d
  src/gc/impl/conservative/gc.d
  src/gc/impl/manual/gc.d
  src/gc/impl/proto/gc.d
  src/gc/proxy.d
  src/rt/tracegc.d
  test/init_fini/src/custom_gc.d
Labels: 72h no objection -> merge, Enhancement, auto-merge
