Repository dlang/druntime, pull requests merged in 2020-12, with the labels that each got.

#3297 Fix TypeInfo_Enum.destroy and TypeInfo_Enum.postblit not calling destroy and postblit of base type
  src/object.d
  test/typeinfo/Makefile
  test/typeinfo/src/enum_.d
Labels: Bug Fix, auto-merge

#3298 core.sys.posix.stdio: Conditionally declare getdelim and getline, add missing L_ctermid
  src/core/sys/posix/stdio.d
Labels: System Headers, auto-merge

#3301 Fix 21442: Do not call shrink for AA in finalizers
  src/rt/aaA.d
  test/aa/src/test_aa.d
Labels: Bug Fix, auto-merge

#3302 core.sys.posix.ucontext: Define mcontext_t and ucontext_t for Darwin
  src/core/sys/posix/ucontext.d
Labels: System Headers, auto-merge

#3304 Separate string-formatting of backtrace into `Location.toString` and add documentation
  src/rt/backtrace/dwarf.d
  test/exceptions/long_backtrace_trunc.exp
Labels: Refactoring, auto-merge

#3306 Cirrus, Github CI: Use HOST_DMD instead of HOST_DC
  .cirrus.yml
  .github/workflows/cxx.yml
Labels: auto-merge

#3310 Move rt.backtrace to core.internal.backtrace
  mak/COPY
  mak/DOCS
  mak/SRCS
  posix.mak
  src/core/internal/backtrace/dwarf.d
  src/core/internal/backtrace/elf.d
  src/core/internal/backtrace/macho.d
  src/core/internal/container/array.d
  src/core/internal/container/common.d
  src/core/internal/container/hashtab.d
  src/core/internal/container/treap.d
  src/core/internal/qsort.d
  src/core/runtime.d
  src/gc/impl/conservative/gc.d
  src/gc/impl/manual/gc.d
  src/gc/impl/proto/gc.d
  src/rt/minfo.d
  src/rt/profilegc.d
  src/rt/sections_elf_shared.d
  src/rt/sections_osx_x86.d
  src/rt/sections_osx_x86_64.d
  src/rt/util/random.d
Labels: Refactoring, auto-merge

#3309 Fix inscrutable template error when core.stdcpp.vector of a struct with a core.stdcpp.vector field is referenced before the struct's definition
  src/core/stdcpp/vector.d
  test/stdcpp/src/vector_test.d
Labels: Bug Fix, auto-merge

#3312 Document and expose core.internal.dassert
  mak/DOCS
  src/core/internal/dassert.d
Labels: auto-merge, documentation

#3270 freebsd: Don't use versioned symbols with GDC
  src/core/sys/freebsd/sys/event.d
  src/core/sys/freebsd/sys/mount.d
  src/core/sys/posix/dirent.d
  src/core/sys/posix/sys/stat.d
  src/core/sys/posix/sys/statvfs.d
Labels: auto-merge

#3284 core.stdcpp.new_.cpp_delete unnecessarily requires destruction to be @nogc
  src/core/stdcpp/new_.d
  test/stdcpp/src/new_test.d
Labels: Enhancement, auto-merge

#3314 Fix 21484: Infinite loop in core.memory : GC.{get,set,clr}Attr(const scope void*...)
  src/core/memory.d
  test/gc/Makefile
  test/gc/attributes.d
Labels: Bug Fix, auto-merge

#3307 Darwin: more fixes for ucontext_t implementation of core.thread.Fiber
  src/core/sys/posix/ucontext.d
  src/core/thread/fiber.d
Labels: auto-merge

#3315 merge stable
  src/core/atomic.d
  src/core/memory.d
  src/core/stdcpp/new_.d
  src/core/stdcpp/vector.d
  src/object.d
  src/rt/aaA.d
  src/rt/sections_elf_shared.d
  test/aa/src/test_aa.d
  test/gc/Makefile
  test/gc/attributes.d
  test/stdcpp/src/new_test.d
  test/stdcpp/src/vector_test.d
  test/typeinfo/Makefile
  test/typeinfo/src/enum_.d
Labels: Enhancement, auto-merge, stable -> master

#3316 fix Issue 8046 - simd.d needs some documentation
  src/core/simd.d
Labels: Bug Fix, auto-merge, documentation

#3317 Add @nogc to core.sys.linux.execinfo
  src/core/sys/linux/execinfo.d
Labels: auto-merge

#3170 Remove unnecessary trusted lambdas
  src/object.d
Labels: auto-merge

#3236 core.memory: Add moveToGC() to promote values to new GC allocations
  src/core/memory.d
  src/rt/lifetime.d
Labels: auto-merge
