Repository dlang/druntime, pull requests merged in 2020-10, with the labels that each got.

#3225 core/threadasm.S: Fix assembly for MIPS I ISA
  src/core/threadasm.S
Labels: auto-merge

#3226 [macOS Big Sur] libc symbols for both ARM Mac and x86_64 Mac
  src/core/stdc/math.d
  src/core/sys/posix/dirent.d
  src/core/sys/posix/sys/stat.d
Labels: auto-merge

#3223 Convert rt/msvc*.c to D
  mak/SRCS
  src/core/thread/osthread.d
  src/rt/msvc.c
  src/rt/msvc.d
  src/rt/msvc_math.c
  src/rt/msvc_math.d
  win64.mak
Labels: auto-merge

#3215 Added getifaddrs OSX bindings
  src/core/sys/darwin/ifaddrs.d
Labels: auto-merge

#3227 core.stdcpp.utility was not being copied to imports
  mak/SRCS
Labels: auto-merge

#3231 win**.mak: Use explicit path when running unittests
  win32.mak
  win64.mak
Labels: auto-merge

#3233 Fix Azure CI regression
  azure-pipelines.yml
  src/rt/msvc.d
Labels: auto-merge

#3200 Make tryLock(Duration) more efficient at slight expense of verbosity
  src/core/sync/rwmutex.d
Labels: auto-merge

#3237 Fix Issue 21315 - TypeInfo_StaticArray.swap is broken
  src/object.d
Labels: Bug Fix, auto-merge

#3228 merge stable
  src/core/internal/array/casting.d
  src/core/thread/threadbase.d
  src/object.d
Labels: Bug Fix, auto-merge

#3240 rt.critical_: Implement _d_criticalenter2 library helper
  src/rt/critical_.d
Labels: Blocking Other Work, auto-merge

#3242 time unittest fix for fast boot devices
  src/core/time.d
Labels: auto-merge

#3239 core.lifetime: Add copyEmplace() to simulate copy-construction
  src/core/internal/array/appending.d
  src/core/internal/array/construction.d
  src/core/lifetime.d
Labels: auto-merge

#3234 Sync Azure CI script with DMD's
  azure-pipelines.yml
Labels: auto-merge

#3244 rt.critical_: Use atomics to read from/write to the _d_criticalenter2 parameter
  src/rt/critical_.d
Labels: auto-merge

#3235 Add Cirrus CI
  .cirrus.yml
Labels: auto-merge

#3243 sem_timedwait should use CLOCK_REALTIME
  src/core/sync/semaphore.d
Labels: auto-merge

#3248 [dmd-cxx] rt.critical_: Implement _d_criticalenter2 library helper
  src/rt/critical_.d
Labels: auto-merge

#3245 Fix Issue 14226 - Don't initialize/overwrite global trace handler with each thread
  src/core/runtime.d
  src/core/sys/windows/stacktrace.d
Labels: Bug Fix, auto-merge

#3250 rt.critical_: Add casts to shared for _d_criticalenter2
  src/rt/critical_.d
Labels: auto-merge

#3251 Compilation for embedded ARM fix
  src/core/threadasm.S
Labels: auto-merge

#3252 [stable] Fix stdcpp integration test for g++/libstdc++ 10
  test/stdcpp/src/array.cpp
  test/stdcpp/src/string_view.cpp
Labels: auto-merge

#3238 Fix: core.stdcpp.vector cannot have core.stdcpp.vector as element
  src/core/stdcpp/vector.d
  test/stdcpp/src/vector_test.d
Labels: Bug Fix, auto-merge

#3221 Add UDA for optional Objective-C interface methods
  src/core/attribute.d
Labels: Enhancement, auto-merge

#3258 Adds out of memory check
  src/gc/os.d
Labels: auto-merge

#3259 MEMSTOMP debug is not compatible with this GC unittest
  src/core/memory.d
Labels: auto-merge

#3255 Fix - core.stdcpp.vector.vector does not implement opEquals
  src/core/stdcpp/vector.d
  test/stdcpp/src/vector_test.d
Labels: Bug Fix, auto-merge

#3257 Adds stack scan assertions
  src/core/thread/threadbase.d
Labels: auto-merge
