Repository dlang/druntime, pull requests merged in 2020-01, with the labels that each got.

#2831 core/atomic.d: Add GDC atomic support code
  src/core/atomic.d
  src/core/internal/atomic.d
Labels: auto-merge

#2892 Fix Issue 20476 - chainTogether leaks exception with -dip1008
  src/object.d
  test/exceptions/Makefile
  test/exceptions/src/refcounted.d
Labels: Bug Fix, auto-merge

#2891 Fix DDoc REF macro link for GC.inFinalizer
  changelog/gc_in_finalizer.dd
Labels: Trivial, auto-merge, documentation

#2888 Removed version(unittest) blocks because they introduce big overhead
  src/core/sync/barrier.d
  src/core/sync/condition.d
  src/core/sync/semaphore.d
  src/core/sys/posix/sys/select.d
  src/etc/linux/memoryerror.d
Labels: auto-merge

#2895 fix Issue 20447 - [REG 2.089] importing core.thread exposes unistd, hidin…
  src/core/thread/osthread.d
  test/thread/Makefile
  test/thread/src/test_import.d
Labels: Bug Fix, auto-merge

#2890 Fix issue 20468 - `emplace` should forward argument lvalueness correctly
  src/core/internal/lifetime.d
  src/core/lifetime.d
Labels: Bug Fix, auto-merge

#2900 Remove redundant selective import of MAP_ANON
  src/core/thread/fiber.d
  src/gc/os.d
Labels: auto-merge

#2896 More version(unittest) blocks removed
  src/core/demangle.d
  src/core/internal/convert.d
  src/core/lifetime.d
Labels: 72h no objection -> merge

#2894 Much more complete core.sys.windows.security
  changelog/expanded_windows_security_bindings.dd
  src/core/sys/windows/security.d
Labels: auto-merge-squash

#2899 stable: Fix broken 'stat' definitions for ARM, AArch64 & more
  src/core/sys/posix/fcntl.d
  src/core/sys/posix/semaphore.d
  src/core/sys/posix/sys/stat.d
  src/core/sys/posix/sys/types.d
Labels: auto-merge

#2904 fix Issue 20497 - thread with limited stackspace crashes depending on…
  src/core/thread/osthread.d
  src/rt/sections_elf_shared.d
  test/thread/Makefile
  test/thread/src/tlsstack.d
Labels: Bug Fix, auto-merge

#2903 [stable] Small follow-up to core.internal.execinfo refactoring
  src/core/internal/execinfo.d
  src/rt/backtrace/dwarf.d
Labels: auto-merge

#2880 Merge remote-tracking branch 'upstream/stable' into merge_stable
  changelog/gc_in_finalizer.dd
  changelog/platform_dependent_execinfo.dd
  changelog/to-prec.dd
  changelog/unittest-default.dd
  src/core/exception.d
Labels: auto-merge

#2905 Remove obsolete pragma(mangle, ...) from entrypoint.d
  src/core/internal/entrypoint.d
Labels: auto-merge

#2906 Merge branch 'stable' into 'master'
  src/core/internal/execinfo.d
  src/core/sys/posix/fcntl.d
  src/core/sys/posix/semaphore.d
  src/core/sys/posix/sys/stat.d
  src/core/sys/posix/sys/types.d
  src/core/thread/osthread.d
  src/rt/backtrace/dwarf.d
  src/rt/sections_elf_shared.d
  test/thread/Makefile
  test/thread/src/test_import.d
  test/thread/src/tlsstack.d
Labels: Bug Fix, auto-merge

#2907 core.demangle: Add fast path for obvious non-D names
  src/core/demangle.d
Labels: auto-merge

#2908 Fix issue 19909: core.stdc.errno missing POSIX error code on Windows
  src/core/stdc/errno.d
Labels: Bug Fix, auto-merge

#2909 Fix Issue 20512, 20513 - Return type of memchr/wmemchr should be inout(void)*/inout(wchar_t)* rather than void*/wchar_t*
  src/core/stdc/string.d
  src/core/stdc/wchar_.d
Labels: Bug Fix, auto-merge

#2911 Fix issue 19902 - hasElaborateCopyConstructor doesn't know about copy…
  src/core/internal/traits.d
Labels: Bug Fix, auto-merge

#2912 Add missing files to makefiles in 'mak/'
  mak/COPY
  mak/SRCS
  mak/WINDOWS
Labels: auto-merge

#2913 Update docs to reflect current unittest algorithm defaults.
  src/core/runtime.d
Labels: documentation

#2916 [stable] Musl: Fix definitions for [u]int_fast{16,32}_t
  src/core/stdc/stdint.d
Labels: Bug Fix, auto-merge

#2915 Be sure to call pthread_attr_destroy
  src/core/thread/osthread.d
Labels: auto-merge

#2918 Musl: Disable test/shared load_13414 on Musl
  test/shared/src/load_13414.d
Labels: auto-merge
