Repository dlang/druntime, pull requests merged in 2020-07, with the labels that each got.

#3149 fix test for issue 11393 introduced by #2436
  src/core/memory.d
Labels: auto-merge

#3069 Add publictests test checker to druntime (reboot of #2087)
  .circleci/config.yml
  .circleci/run.sh
  posix.mak
  src/core/demangle.d
  src/core/time.d
Labels: auto-merge

#3150 fix Issue 21026 - add core.bitop.bswap(ushort)
  src/core/bitop.d
Labels: Bug Fix, Enhancement, auto-merge

#3151 Remove __ArrayEq which the compiler no longer uses as of https://github.com/dlang/dmd/pull/11212
  src/core/internal/array/equality.d
  src/object.d
Labels: Bug Fix, auto-merge

#3153 Add nogc attributes to linux/sys
  src/core/sys/linux/sys/inotify.d
  src/core/sys/linux/sys/mman.d
  src/core/sys/linux/sys/signalfd.d
  src/core/sys/linux/sys/xattr.d
Labels: auto-merge

#3154 merge stable
  changelog/add_exit_group.dd
  changelog/darwin_bindings.dd
  changelog/depercate_object_selector.dd
  changelog/gc_suffixes.dd
Labels: auto-merge

#3156 core.internal.array.operations: Add explicit cast from __vector(void[]) to return type
  src/core/internal/array/operations.d
Labels: Blocking Other Work, auto-merge

#3157 Revert #1900 - Add overrides for __simd intrinsics
  src/core/simd.d
Labels: auto-merge

#3158 TypeInfo_Enum: Fix equals/compare signature
  src/object.d
Labels: auto-merge

#3161 core.bitop: use recognized pattern for rotates
  src/core/bitop.d
Labels: Refactoring, auto-merge

#3142 Revise core.internal.array.equality
  changelog/array_equality.dd
  src/core/internal/array/equality.d
Labels: auto-merge

#3166 fabs: make it pure, match it to std.math.fabs
  src/core/math.d
Labels: auto-merge

#3165 No need for dstrcmp in object.d
  src/object.d
Labels: auto-merge-squash

#3168 Revert "EASY: Move radix to template parameter in unsignedToTempString"
  src/core/demangle.d
  src/core/internal/abort.d
  src/core/internal/string.d
  src/core/internal/util/array.d
  src/core/time.d
  src/object.d
Labels: auto-merge

#3169 (un)signedToTempString: Make radix a template parameter to avoid inte…
  src/core/demangle.d
  src/core/internal/abort.d
  src/core/internal/string.d
  src/core/internal/util/array.d
  src/core/time.d
  src/object.d
Labels: auto-merge

#3171 Remove old (un)signedToTempString functions
  src/core/internal/string.d
Labels: auto-merge

#3175 sys.posix.signal: SIGRT{MIN,MAX} is platform specific, not runtime
  src/core/sys/posix/signal.d
Labels: Bug Fix
