Repository dlang/druntime, pull requests merged in 2020-04, with the labels that each got.

#3014 object: Fix punctuation in example comment
  src/object.d
Labels: Trivial, auto-merge

#3016 Turn on markdown for druntime doc build
  posix.mak
  src/core/sys/darwin/mach/getsect.d
  src/rt/dwarfeh.d
Labels: auto-merge, documentation

#3018 [stable] core.internal.dassert: Fix miniFormat for structs with non-copyable fields
  src/core/internal/dassert.d
Labels: auto-merge

#3015 [SystemZ] Fix layout of struct sigaction_t
  src/core/sys/posix/signal.d
Labels: System Headers, auto-merge

#3020 [dmd-cxx] [SystemZ] Fix layout of struct sigaction_t
  src/core/sys/posix/signal.d
Labels: System Headers, Trivial

#3022 Fix UnDecorateSymbolNameFunc from dbghelp
  src/core/sys/windows/dbghelp.d
Labels: auto-merge

#3023 Add CPU_ALLOC and CPU_FREE
  src/core/sys/linux/sched.d
Labels: auto-merge

#3027 Add CPU_ALLOC_SIZE
  src/core/sys/linux/sched.d
Labels: auto-merge

#3028 Add CPU_COUNT_S
  src/core/sys/linux/sched.d
Labels: auto-merge

#3025 C++ interop tests: Test on Windows + MSVC 2019
  .github/workflows/cxx.yml
Labels: auto-merge

#3029 Fix Issue 20731 - checkaction=context fails for structs with 'alias <slice> this'
  src/core/internal/dassert.d
  test/exceptions/src/assert_fail.d
Labels: Bug Fix, auto-merge

#3031 add pragma printf and scanf annotations to stdio.d
  src/core/stdc/stdio.d
Labels: Blocking Other Work

#3032 Prepare for stack-allocated array literals passed to scope slice params
  src/core/internal/dassert.d
  src/core/internal/destruction.d
Labels: auto-merge

#3033 Github actions: Restore accidentally removed boilerplate
  .github/workflows/cxx.yml
Labels: auto-merge

#2301 Flags for send and recv on socket fd.
  src/core/sys/linux/sys/socket.d
Labels: System Headers, auto-merge

#2770 Give TypeInfo_Class/TypeInfo_Interface.isBaseOf like C#/Java isAssignableFrom
  changelog/isbaseof.dd
  src/object.d
  src/rt/cast_.d
  test/typeinfo/Makefile
  test/typeinfo/src/isbaseof.d
Labels: 72h no objection -> merge, Enhancement, auto-merge

#3039 core.stdc.stdarg: Refactor with alignUp() helper
  src/core/stdc/stdarg.d
Labels: auto-merge

#3041 merge stable
  src/core/internal/dassert.d
  src/core/internal/string.d
  test/exceptions/Makefile
  test/exceptions/src/assert_fail.d
Labels: Bug Fix, auto-merge

#3043 Enable tests on Linux+Clang
  .github/workflows/cxx.yml
Labels: auto-merge

#3036 Musl: add more stdlib definitions and enable HaveMemstream
  src/core/sys/posix/stdio.d
  src/core/sys/posix/stdlib.d
Labels: auto-merge-squash

#3044 Fix Issue 20748 - Deprecation for assert using shared type and checka…
  src/core/internal/dassert.d
  test/exceptions/src/assert_fail.d
Labels: Bug Fix, auto-merge

#3045 Fix Issue 20750 - checkaction=context segfaults for null references
  src/core/internal/dassert.d
  test/exceptions/src/assert_fail.d
Labels: Bug Fix, auto-merge

#3046 Merge stable into master
  src/core/internal/dassert.d
  test/exceptions/src/assert_fail.d
Labels: Bug Fix, auto-merge

#3035 [stable] Fix code bloat regressions wrt. core.internal.lifetime.emplaceInitializer
  src/core/internal/lifetime.d
  src/object.d
Labels: auto-merge

#3026 use D tool to copy imports instead of explicit list of rules
  mak/WINDOWS
  mak/copyimports.d
  win32.mak
  win64.mak
Labels: auto-merge

#3037 Add method TypeInfo.argTypes() for non-Apple AArch64 targets
  src/object.d
  src/rt/typeinfo/ti_cdouble.d
  src/rt/typeinfo/ti_cfloat.d
  src/rt/typeinfo/ti_creal.d
Labels: auto-merge

#3034 `dup`, `idup`, `keys`, `values`: if a type is known to have a postblit do not emit code for the non-postblit path and vice versa
  src/object.d
Labels: Enhancement, auto-merge

#3048 [core.cpuid] LDC uses GNU style asm
  src/core/cpuid.d
Labels: Trivial, auto-merge

#3053 clean up test/thread/src/fiber_guard_page
  test/thread/src/fiber_guard_page.d
Labels: auto-merge

#3056 [rt.trace] AArch64 implementation and LDC reposition
  src/rt/trace.d
Labels: auto-merge

#3058 Fix Issue 20760 - checkaction=context doesnt print floating point num…
  src/core/internal/dassert.d
  test/exceptions/src/assert_fail.d
Labels: Bug Fix, auto-merge

#3047 Extend _d_assert_fail for unary expressions
  src/core/internal/dassert.d
  test/exceptions/src/assert_fail.d
Labels: auto-merge

#3062 Add 64-bit SIMD aliases, remove D_AVX condition.
  src/core/simd.d
Labels: auto-merge

#3063 [dmd-cxx] Backport internal.convert, toPrec, SIMD aliases.
  src/core/internal/convert.d
  src/core/math.d
  src/core/simd.d
Labels: Enhancement

#3060 Trivial: Tabify mak/DOCS
  mak/DOCS
Labels: Build System, Trivial, auto-merge

#3064 core.demangle: add FuncAttrLive
  src/core/demangle.d
Labels: auto-merge

#3061 Fix Issue 20763 - checkaction=context does not format pointers
  src/core/internal/dassert.d
  test/exceptions/src/assert_fail.d
Labels: Bug Fix, auto-merge

#3059 Add `core.sys.darwin.mach.{nlist,stab}` bindings
  changelog/darwin_bindings.dd
  mak/COPY
  mak/DOCS
  mak/SRCS
  src/core/sys/darwin/mach/nlist.d
  src/core/sys/darwin/mach/stab.d
Labels: auto-merge

#2943 Fix Issue 18011 - core.sys.condition cannot be used as shared
  src/core/sync/condition.d
Labels: Bug Fix, auto-merge-squash

#2997 Split core.stdc.time to Posix and Windows versions
  mak/COPY
  mak/SRCS
  src/core/stdc/time.d
  src/core/sys/posix/stdc/time.d
  src/core/sys/windows/stdc/time.d
Labels: System Headers, auto-merge

#3066 core.internal.convert: Correct documentation on layout of DoubleDouble
  src/core/internal/convert.d
Labels: Trivial, auto-merge

#3067 [dmd-cxx] core.internal.convert: Correct documentation on layout of DoubleDouble
  src/core/internal/convert.d
Labels: Trivial, auto-merge

#3070 Some minors import / constant cleanup
  src/core/thread/fiber.d
  src/gc/impl/conservative/gc.d
  src/rt/backtrace/macho.d
  src/rt/deh_win64_posix.d
Labels: Refactoring, auto-merge

#2926 Factorise Thread and Fiber
  mak/COPY
  mak/SRCS
  src/core/thread/context.d
  src/core/thread/fiber.d
  src/core/thread/osthread.d
  src/core/thread/package.d
Labels: Refactoring, auto-merge

#3071 core.sys.posix.netdb: Fix SPARC32/Solaris declaration of addrinfo
  src/core/sys/posix/netdb.d
Labels: System Headers, auto-merge

#3072 core.sys.posix.sys.stat: Fix SPARC32/Solaris declaration of stat32_t
  src/core/sys/posix/sys/stat.d
Labels: System Headers, auto-merge

#2871 core.math: Re-enable disabled tests and update toPrec comment
  src/core/math.d
Labels: Bug Fix, auto-merge

#2135 Druntime part of fix for 18559
  src/core/math.d
Labels: auto-merge

#3073 [dmd-cxx] Merge stdc bindings from master into dmd-cxx
  mak/COPY
  mak/SRCS
  mak/WINDOWS
  src/core/math.d
  src/core/stdc/assert_.d
  src/core/stdc/errno.d
  src/core/stdc/stdint.d
  src/core/stdc/string.d
  src/core/sys/darwin/mach/port.d
  src/core/sys/darwin/mach/thread_act.d
  src/core/sys/freebsd/dlfcn.d
  src/core/sys/freebsd/execinfo.d
  src/core/sys/linux/config.d
  src/core/sys/linux/link.d
  src/core/sys/linux/sys/netinet/tcp.d
  src/core/sys/linux/sys/socket.d
  src/core/sys/linux/timerfd.d
  src/core/sys/posix/config.d
  src/core/sys/posix/dlfcn.d
  src/core/sys/posix/inttypes.d
  src/core/sys/posix/netdb.d
  src/core/sys/posix/signal.d
  src/core/sys/posix/stdio.d
  src/core/sys/posix/stdlib.d
  src/core/sys/posix/sys/filio.d
  src/core/sys/posix/sys/ioccom.d
  src/core/sys/posix/sys/resource.d
  src/core/sys/posix/sys/select.d
  src/core/sys/posix/sys/socket.d
  src/core/sys/posix/sys/stat.d
  src/core/sys/posix/sys/ttycom.d
  src/core/sys/posix/sys/types.d
  src/core/sys/posix/sys/uio.d
  src/core/sys/posix/syslog.d
  src/core/sys/posix/time.d
  src/core/sys/posix/unistd.d
Labels: System Headers

#3075 forward and use -m$(MODEL) when building tools with host dmd
  mak/WINDOWS
  win32.mak
  win64.mak
Labels: auto-merge

#3068 [stable] core.cpuid: Slightly adapt GDC-style inline asm
  src/core/cpuid.d
Labels: auto-merge

#3055 upstream LDC changes for test/exceptions/Makefile
  test/exceptions/Makefile
Labels: auto-merge

#3077 core.sys.posix.sys.stat: Fix previous SPARC32/Solaris change.
  src/core/sys/posix/sys/stat.d
Labels: System Headers, Trivial, auto-merge

#3079 core.thread.osthread: Remove version ExternStackShell
  src/core/thread/osthread.d
  src/core/threadasm.S
Labels: Bug Fix, auto-merge

#3078 [dmd-cxx] core.sys.posix.sys.stat: Fix previous SPARC32/Solaris change.
  src/core/sys/posix/sys/stat.d
Labels: System Headers, Trivial

#3081 test: Force Fiber guardPageSize to be same as stackSize
  test/thread/src/fiber_guard_page.d
Labels: Bug Fix, auto-merge

#3080 core.internal.convert: Handle ireal types on PPC
  src/core/internal/convert.d
Labels: Bug Fix, auto-merge

#3083 [dmd-cxx] Backport PPC fixes
  src/core/internal/convert.d
  src/core/thread.d
  src/core/threadasm.S
  test/thread/src/fiber_guard_page.d
Labels: Bug Fix, auto-merge
