Repository dlang/druntime, pull requests merged in 2020-03, with the labels that each got.

#2968 Fix fprintf arg types
  src/rt/profilegc.d
  src/rt/trace.d
Labels: auto-merge

#2970 fix azure pipeline
  azure-pipelines.yml
Labels: auto-merge

#2965 Merge remote-tracking branch 'upstream/stable' into merge_stable
  src/core/internal/switch_.d
  src/core/thread/fiber.d
  test/betterc/Makefile
  test/betterc/src/test20613.d
Labels: Bug Fix, auto-merge

#2971 Fix Issue 20629 - atomicStore does not compile for struct using -m64
  src/core/atomic.d
  src/core/internal/atomic.d
Labels: Bug Fix, auto-merge

#2963 core.memory: Fix mangle name of core.memory.initialize
  src/core/memory.d
Labels: Regression, auto-merge

#2973 fix azure pipeline: building with LDC now needs DMD as a host compile…
  azure-pipelines.yml
Labels: auto-merge

#2974 rt/trace: Some refactorings & code cleanup
  src/rt/trace.d
Labels: Refactoring, auto-merge

#2957 Add sched_getcpu
  src/core/sys/linux/sched.d
Labels: auto-merge

#2980 [stable] Fix problematic macro in core/threadasm.S
  src/core/threadasm.S
Labels: auto-merge

#2979 [stable] core.internal.convert: Localize newly added core.math import
  src/core/internal/convert.d
Labels: auto-merge

#2978 [stable] Fix test_runner regression for LDC
  src/test_runner.d
Labels: auto-merge

#2972 Fix printf arg. types 2
  src/core/internal/dassert.d
  src/gc/impl/conservative/gc.d
Labels: auto-merge

#2878 The rest of std::string's API
  src/core/internal/lifetime.d
  src/core/internal/traits.d
  src/core/stdcpp/allocator.d
  src/core/stdcpp/string.d
  src/core/stdcpp/xutility.d
  test/stdcpp/src/string_test.d
Labels: auto-merge

#2982 remove wrong @safe attributes
  src/core/stdcpp/string.d
Labels: auto-merge

#2621 Issue 19924 - Make core.bitop.bswap(ulong) work in betterC
  src/core/bitop.d
  test/betterc/Makefile
  test/betterc/src/test19924.d
Labels: Enhancement, auto-merge

#2975 Merge remote-tracking branch 'upstream/stable' into merge_stable
  changelog/add_missing_pthread_attr_destroy.dd
  changelog/expanded_windows_security_bindings.dd
  changelog/std_unique_ptr.dd
  changelog/tfd_timer_cancel_on_set.dd
  src/core/atomic.d
  src/core/internal/atomic.d
  src/core/internal/convert.d
  src/core/threadasm.S
  src/test_runner.d
Labels: Bug Fix, auto-merge

#2985 core.cpuid: Surround gcc-iasm operands with parentheses.
  src/core/cpuid.d
Labels: auto-merge

#2986 [dmd-cxx] core.cpuid: Surround gcc-iasm operands with parentheses.
  src/core/cpuid.d
Labels: auto-merge

#2987 Unused code remove
  src/core/sync/barrier.d
Labels: auto-merge

#2983 core.internal.elf: Improve usability
  src/core/internal/elf/dl.d
  src/core/internal/elf/io.d
  src/core/sys/linux/config.d
  src/core/sys/linux/link.d
  src/core/sys/posix/config.d
  src/rt/backtrace/elf.d
Labels: auto-merge

#2990 Add compiler-recognized UDA for Itanium ABI's abi-tags
  src/core/attribute.d
  src/object.d
Labels: Blocking Other Work, auto-merge

#2724 Use `backtrace` on POSIX when available
  src/core/runtime.d
  src/rt/deh.d
  src/rt/deh_win32.d
  src/rt/deh_win64_posix.d
  src/rt/dwarfeh.d
Labels: auto-merge

#2992 pure functions imply scope attribute, but not return attribute 2
  src/core/demangle.d
Labels: auto-merge

#2993 pure functions infer scope, but not return 3
  src/core/demangle.d
Labels: auto-merge

#2999 abort() msg parameter escapes
  src/core/internal/abort.d
Labels: Blocking Other Work, auto-merge

#3012 Fix Issue 20711 - object.update requires the "update" callback to was…
  src/object.d
Labels: Enhancement, auto-merge

#3013 Remove redundant '@system' in core.sys.posix.string
  src/core/sys/posix/string.d
Labels: auto-merge

#3011 Implement Github actions to test `core.stdcpp`
  .github/workflows/cxx.yml
  posix.mak
  test/common.mak
  test/stdcpp/Makefile
Labels: auto-merge, stdcpp
