Repository dlang/druntime, pull requests merged in 2020-09, with the labels that each got.

#3204 Enable -preview=dtorfields for druntime
  posix.mak
  win32.mak
  win64.mak
Labels: auto-merge

#3205 Remove deprecated -preview=markdown flag
  posix.mak
Labels: auto-merge

#3206 Simplified TypeInfo, take 2: factor common code in
  mak/DOCS
  mak/SRCS
  posix.mak
  src/core/internal/array/operations.d
  src/rt/typeinfo/ti_Acdouble.d
  src/rt/typeinfo/ti_Acfloat.d
  src/rt/typeinfo/ti_Acreal.d
  src/rt/typeinfo/ti_Adouble.d
  src/rt/typeinfo/ti_Afloat.d
  src/rt/typeinfo/ti_Ag.d
  src/rt/typeinfo/ti_Aint.d
  src/rt/typeinfo/ti_Along.d
  src/rt/typeinfo/ti_Areal.d
  src/rt/typeinfo/ti_Ashort.d
  src/rt/typeinfo/ti_C.d
  src/rt/typeinfo/ti_byte.d
  src/rt/typeinfo/ti_cdouble.d
  src/rt/typeinfo/ti_cent.d
  src/rt/typeinfo/ti_cfloat.d
  src/rt/typeinfo/ti_char.d
  src/rt/typeinfo/ti_creal.d
  src/rt/typeinfo/ti_dchar.d
  src/rt/typeinfo/ti_delegate.d
  src/rt/typeinfo/ti_double.d
  src/rt/typeinfo/ti_float.d
  src/rt/typeinfo/ti_idouble.d
  src/rt/typeinfo/ti_ifloat.d
  src/rt/typeinfo/ti_int.d
  src/rt/typeinfo/ti_ireal.d
  src/rt/typeinfo/ti_long.d
  src/rt/typeinfo/ti_n.d
  src/rt/typeinfo/ti_ptr.d
  src/rt/typeinfo/ti_real.d
  src/rt/typeinfo/ti_short.d
  src/rt/typeinfo/ti_ubyte.d
  src/rt/typeinfo/ti_ucent.d
  src/rt/typeinfo/ti_uint.d
  src/rt/typeinfo/ti_ulong.d
  src/rt/typeinfo/ti_ushort.d
  src/rt/typeinfo/ti_void.d
  src/rt/typeinfo/ti_wchar.d
  src/rt/util/typeinfo.d
Labels: auto-merge-squash

#3207 Add comments for VS2019.
  win64.mak
Labels: auto-merge

#3152 Reduce template function instantiations related to array equality
  src/core/internal/array/equality.d
Labels: Enhancement, auto-merge

#3210 make cimag() and creal() inlineable
  src/core/stdc/complex.d
Labels: auto-merge

#3133 Backport move(Emplace) fixes from Phobos
  src/core/lifetime.d
Labels: Enhancement, auto-merge

#3213 Avoid import of core.internal.convert when unneeded
  src/core/internal/hash.d
Labels: auto-merge

#3214 Mark osthread.resume nogc
  src/core/thread/osthread.d
  src/core/thread/threadbase.d
Labels: auto-merge

#3216 [stable] core.internal.array.casting: Prevent superfluous slice copy checks
  src/core/internal/array/casting.d
Labels: auto-merge

#3220 Deduplicate interface methods declarations for IShellFolder2
  src/core/sys/windows/shlobj.d
Labels: auto-merge

#3217 merge stable
  changelog/array_equality.dd
  changelog/faster_profilegc.dd
Labels: auto-merge
