Repository dlang/druntime, pull requests merged in 2020-11, with the labels that each got.

#3246 core.lifetime: Fix copyEmplace() wrt. shared/mutability qualifiers
  src/core/internal/traits.d
  src/core/lifetime.d
Labels: Blocking Other Work, auto-merge

#3264 TypeInfo.swap must not allow reachable memory to be freed if interrupted by a garbage collection pass
  src/object.d
Labels: Bug Fix, auto-merge

#3254 Fix - core.stdcpp.string.basic_string does not implement opEquals
  src/core/stdcpp/string.d
  test/stdcpp/src/string_test.d
Labels: Bug Fix, auto-merge

#3261 Rename ProtoGC.term()
  src/gc/impl/proto/gc.d
  src/gc/proxy.d
Labels: auto-merge

#3189 Update `LineNumberProgram` up to DWARF v5
  src/rt/backtrace/dwarf.d
Labels: auto-merge

#3269 merge stable
  src/core/stdcpp/string.d
  src/core/stdcpp/vector.d
  src/object.d
  test/stdcpp/src/string_test.d
  test/stdcpp/src/vector_test.d
Labels: Bug Fix, auto-merge

#3266 core.internal.convert: Add support for FreeBSD x86 reals
  src/core/internal/convert.d
  src/rt/dmain2.d
Labels: auto-merge

#3276 GH Actions: Use new syntax for set-env / add-path
  .github/workflows/cxx.yml
Labels: CI, auto-merge

#3275 CRuntime_Musl: Support v1.2.0 for 32 bits
  changelog/musl-32bits.dd
  src/core/sys/posix/sys/types.d
Labels: auto-merge

#3277 GH Action: Check out the correct branch after merge
  .github/workflows/cxx.yml
Labels: CI, auto-merge

#3278 Merge branch stable into master (fix Github CI)
  .github/workflows/cxx.yml
  changelog/musl-32bits.dd
  src/core/sys/posix/sys/types.d
Labels: auto-merge

#3274 thread.d unittest: assertion added
  src/core/thread/osthread.d
Labels: auto-merge

#3279 let everybody load core.sys.darwin.mach.loader
  src/core/sys/darwin/mach/loader.d
Labels: auto-merge

#3268 Adds out of memory check
  src/core/thread/threadbase.d
Labels: auto-merge

#3282 core.sys.posix.sys.stat: Update all stat_t helper functions with correct attributes
  src/core/sys/posix/sys/stat.d
Labels: System Headers, auto-merge

#3283 merge stable
  changelog/musl-32bits.dd
Labels: auto-merge

#3271 Issue 17596: Version bindings so that they work for both FreeBSD 11 and 12
  .cirrus.yml
  mak/COPY
  src/core/sys/freebsd/config.d
  src/core/sys/freebsd/sys/event.d
  src/core/sys/freebsd/sys/mount.d
  src/core/sys/posix/dirent.d
  src/core/sys/posix/sys/stat.d
  src/core/sys/posix/sys/types.d
Labels: Bug Fix, System Headers, auto-merge

#3285 Remove support for extern(Pascal)
  benchmark/gcbench/vdparser.extra/vdc/parser/mod.d
  benchmark/gcbench/vdparser.extra/vdc/util.d
  src/core/demangle.d
Labels: auto-merge

#3287 [dmd-cxx] Remove support for extern(Pascal)
  benchmark/gcbench/vdparser.extra/vdc/parser/mod.d
  benchmark/gcbench/vdparser.extra/vdc/util.d
  src/core/demangle.d
Labels: auto-merge

#3286 [dmd-cxx] Update bindings for FreeBSD 12 support
  mak/COPY
  mak/WINDOWS
  src/core/internal/convert.d
  src/core/sys/freebsd/config.d
  src/core/sys/freebsd/sys/event.d
  src/core/sys/freebsd/sys/mount.d
  src/core/sys/posix/dirent.d
  src/core/sys/posix/sys/stat.d
  src/core/sys/posix/sys/types.d
  src/rt/dmain2.d
Labels: System Headers, auto-merge

#3288 [dmd-cxx] Remove another extern(Pascal) test from druntime
  src/core/demangle.d
Labels: Trivial, auto-merge

#3289 dup, idup, keys, values: call postblits directly instead of via TypeInfo function pointer
  src/object.d
Labels: Enhancement, auto-merge

#3290 Minor improvement to PR #3289
  src/object.d
Labels: auto-merge

#3292 core.sys.posix.ucontext: Use (u)long for X86_64 definitions of ucontext_t that use 'long long'
  src/core/sys/posix/ucontext.d
Labels: System Headers

#3293 [dmd-cxx] Update ucontext_t definitions for CET and X32 support
  src/core/sys/posix/ucontext.d
Labels: System Headers

#3291 Make publicly-exposed {suspend,resume}SignalNumber private
  changelog/accidentally-exposed-sigs.dd
  src/core/thread/osthread.d
Labels: Refactoring, auto-merge

#3294 Reduce LDC diff a bit
  src/core/sys/freebsd/execinfo.d
  src/rt/aaA.d
  src/rt/dwarfeh.d
  src/rt/sections_android.d
Labels: auto-merge

#3296 core.cpuid: Use .byte sequence instead of xgetbv instruction
  src/core/cpuid.d
Labels: auto-merge
