Repository dlang/druntime, pull requests merged in 2021-04, with the labels that each got.

#3423 core.demangle: Fix mangling ambiguity, follow-up to #3408
  src/core/demangle.d
Labels: auto-merge

#3421 Fix Issue 21789: Let umask prune permissions of coverage lst files
  src/rt/cover.d
Labels: Enhancement, auto-merge

#3427 On OpenBSD, __fpclassifyd is named __fpclassify
  src/core/stdc/math.d
Labels: auto-merge

#3426 -checkaction=context: Mark context pointer of structs
  src/core/internal/dassert.d
  test/exceptions/src/assert_fail.d
Labels: auto-merge

#3431 [dmd-cxx] object: Don't set WithArgTypes on GNU+AArch64 targets
  src/object.d
Labels: Trivial

#3430 object: Don't set WithArgTypes on GNU+AArch64 targets
  src/object.d
Labels: Trivial, auto-merge

#3432 rt.util: Define D complex types, use them in rt instead of the C complex types
  src/rt/memset.d
  src/rt/util/typeinfo.d
  src/rt/util/utility.d
Labels: Blocking Other Work, auto-merge

#3433 Remove -transition=complex from the Makefiles
  posix.mak
  win32.mak
  win64.mak
Labels: Deprecation

#3428 core.stdc.config: Fix magic __c_complex_* enums for Windows
  src/core/stdc/config.d
  src/rt/util/typeinfo.d
Labels: auto-merge

#3435 Move __ctfeWrite to core.builtins
  mak/COPY
  src/core/builtins.d
  src/object.d
Labels: auto-merge

#3437 Remove legacy comment from _ctfeWrite import
  src/object.d
Labels: Trivial, auto-merge

#3438 core.sys.windows: Use 'extern(Windows)' instead of System
  src/core/sys/windows/com.d
  src/core/sys/windows/dbghelp.d
Labels: System Headers, Trivial, auto-merge

#3440 core.stdc.tgmath: Declare fabsf and fabsl aliases on MinGW
  src/core/stdc/tgmath.d
Labels: System Headers, auto-merge

#3434 merge stable
  src/core/atomic.d
  src/core/internal/atomic.d
  src/core/lifetime.d
  src/core/stdcpp/allocator.d
  src/core/thread/osthread.d
  src/rt/cover.d
  test/stdcpp/src/allocator.cpp
  test/stdcpp/src/allocator_test.d
  test/thread/Makefile
  test/thread/src/join_detach.d
Labels: Enhancement, auto-merge

#3441 core.stdc.math: MinGW is a sub-target of CRuntime_Microsoft
  src/core/stdc/math.d
Labels: System Headers, auto-merge

#3443 Fix (mostly) OpenBSD runtime, take 2
  src/core/internal/backtrace/elf.d
  src/core/internal/elf/dl.d
  src/core/internal/elf/io.d
  src/core/sys/openbsd/sys/link_elf.d
  src/rt/sections.d
  src/rt/sections_solaris.d
Labels: auto-merge

#3442 core.sys.posix.stdio: Add flockfile and other related POSIX declarations for more targets
  src/core/sys/posix/stdio.d
Labels: System Headers, auto-merge

#3444 core.stdc.stdio: Add 'under-the-hood' C I/O functions for DigitalMars, Microsoft, and Glibc runtimes
  src/core/stdc/stdio.d
Labels: System Headers, auto-merge

#3449 core.bitop: Add deprecated note for volatileLoad and volatileStore
  src/core/bitop.d
Labels: Deprecation, Easy Review

#3445 Remove extra exception message on unittest failure
  src/core/runtime.d
Labels: auto-merge

#3452 object.d: Remove if-statement whose condition is always true
  src/object.d
Labels: auto-merge

#3451 Temporarily disable join_detach test
  test/thread/Makefile
Labels: auto-merge

#3453 Merge stable
  test/thread/Makefile
Labels: auto-merge

#3450 TypeInfo_Array.compare can give wrong result when either array exceeds 2GB
  src/object.d
Labels: Bug Fix

#3455 Turn checkedint unittests into public examples and tag @betterC
  src/core/checkedint.d
Labels: auto-merge

#3454 Fix 19783 - Fail to emplace struct with betterC
  src/core/lifetime.d
Labels: Bug Fix, auto-merge
