Repository dlang/druntime, pull requests merged in 2021-06, with the labels that each got.

#3490 merge stable
  src/core/exception.d
  src/core/internal/dassert.d
  src/core/internal/lifetime.d
  src/core/sys/posix/stdio.d
  test/allocations/Makefile
  test/allocations/src/alloc_from_assert.d
Labels: auto-merge

#3491 arpa/inet: Deduplicate INET[6]_ADDRSTRLEN
  src/core/sys/posix/arpa/inet.d
Labels: auto-merge

#3493 Fix 21996 - Skip message formatting for checkaction=context in finalizer
  src/core/internal/dassert.d
  test/exceptions/src/assert_fail.d
Labels: Bug Fix, auto-merge

#3492 Mark GC.addrOf as trusted
  src/core/memory.d
Labels: auto-merge

#3497 [stable] hashOf does not work on enum types whose base type is a SIMD vector
  src/core/internal/hash.d
  test/hash/src/test_hash.d
Labels: Bug Fix

#3499 Fix 22026 - Catch exceptions thrown by user-defined toString methods...
  src/core/internal/dassert.d
  test/exceptions/src/assert_fail.d
Labels: Bug Fix, auto-merge

#3483 Fix 21983 - Initialize remaining elements in a partially dup'ed array if postblit/copy ctor throws
  src/object.d
Labels: Bug Fix, auto-merge

#3500 Remove empty template parameter list from checktion=context tests
  test/exceptions/src/assert_fail.d
Labels: auto-merge

#3501 [stable] hashOf(S) can segfault if S.toHash is forwarded via 'alias this' to a receiver which may be null
  src/core/internal/hash.d
  test/hash/src/test_hash.d
Labels: Bug Fix, auto-merge

#3502 [stable] Fix Issue 22081 - Utterly broken DWARF v5 support
  src/core/internal/backtrace/dwarf.d
Labels: Bug Fix

#3503 Fix 22085 - Format members of extern(C++) classes without toString
  src/core/internal/dassert.d
  test/exceptions/src/assert_fail.d
Labels: Bug Fix, auto-merge

#3504 Use core.lifetime.emplace() building block instead of manual reinventions
  src/core/exception.d
  src/core/internal/container/common.d
  src/core/internal/gc/impl/conservative/gc.d
  src/core/internal/gc/impl/manual/gc.d
  src/core/sync/mutex.d
  src/core/thread/threadbase.d
  src/rt/sections_elf_shared.d
Labels: auto-merge
