Repository dlang/druntime, pull requests merged in 2021-11, with the labels that each got.

#1573 Add documentation to GC struct (Alt)
  src/core/internal/gc/impl/conservative/gc.d
Labels: GC, auto-merge-squash

#1834 Unify Makefile variables for dlang.org: Rename DOCDIR -> DOC_OUTPUT_DIR, DOCFMT -> STDDOC
  posix.mak
Labels: auto-merge-squash

#1968 core.sys.linux.sys.mman: Remove commit hash reference from urls
  src/core/sys/linux/sys/mman.d
Labels: 72h no objection -> merge

#3610 Fix Issue 22485 - OpenBSD: Fix core.sys.openbsd.unistd imports
  src/core/sys/openbsd/unistd.d
Labels: auto-merge, Bug Fix

#3612 fix Issue 21919 - darwin: SEGV in core.thread tests on OSX 11
  src/core/thread/fiber.d
Labels: auto-merge, Bug Fix, core.thread

#3613 [stable] cirrus: Switch to big-sur image
  .cirrus.yml
Labels: auto-merge, Continuous Integration

#3615 Merge `stable` in `mater`
  mak/COPY
  mak/SRCS
  posix.mak
  src/core/demangle.d
  src/core/internal/dassert.d
  src/core/runtime.d
  src/core/sys/openbsd/pthread_np.d
  src/core/sys/openbsd/stdlib.d
  src/core/sys/openbsd/string.d
  src/core/sys/openbsd/sys/mman.d
  src/core/sys/openbsd/sys/sysctl.d
  src/core/sys/openbsd/unistd.d
  src/core/sys/posix/netdb.d
  src/core/sys/posix/sys/mman.d
  src/core/sys/posix/time.d
  src/core/thread/fiber.d
  test/exceptions/src/assert_fail.d
Labels: auto-merge, Bug Fix, Enhancement, stable -> master

#3616 ci: Re-introduce "cirrus: switch to big-sur image"
  .cirrus.yml
Labels: auto-merge, Continuous Integration, Easy Review

#3619 core.internal.backtrace.libunwind: Restrict usage to just DRuntime_Use_Libunwind, same as its only importer
  src/core/internal/backtrace/libunwind.d
Labels: auto-merge

#3620 core.sys.linux.perf_event: Remove import of std.bitmanip
  src/core/sys/linux/perf_event.d
Labels: auto-merge

#3618 Fix issue 22210 - Partially revert #3459 and #3463
  posix.mak
  src/core/internal/traits.d
  test/traits/Makefile
  test/traits/src/all_satisfy.d
Labels: Bug Fix, Enhancement

#3622 FreeBSD version 13.0-CURRENT
  src/core/sys/freebsd/config.d
Labels: auto-merge

#3623 fix deprecated automatic type conversion
  src/core/thread/osthread.d
Labels: auto-merge

#1949 add aligned_alloc
  src/core/stdc/stdlib.d
Labels: System Headers, auto-merge-squash

#3626 Prefer __traits(initSymbol) over TypeInfo.initializer()
  src/core/demangle.d
  src/core/internal/lifetime.d
  src/core/lifetime.d
  src/core/sync/mutex.d
  src/core/thread/osthread.d
  src/core/thread/threadbase.d
  src/object.d
  src/rt/aaA.d
Labels: auto-merge

#3628 Fix 22523 - Ensure that `rt_cmdlineOption` stops at `--`
  src/rt/config.d
  test/config/Makefile
  test/config/src/test22523.d
Labels: Bug Fix

#3627 [SAoC] Declare array returned by _d_arrayctor in union
  src/core/internal/array/construction.d
Labels: auto-merge

#3630 Use `-preview=dip1000` instead of `-dip1000`
  posix.mak
  src/core/lifetime.d
  test/common.mak
  win32.mak
  win64.mak
Labels: auto-merge

#3631 Add return ref ambiguity workaround for toUbyte
  src/core/internal/convert.d
Labels: auto-merge

#3633 Fix Issue 22542 - Explicitly cast backtrace results to int
  src/core/runtime.d
Labels: auto-merge

#3634 remove unnecessary scope keyword
  src/core/sys/darwin/mach/nlist.d
Labels: Blocking Other Work, auto-merge

#3635 Fix Issue 22545 - OpenBSD: Always use system backtrace
  src/core/sys/openbsd/execinfo.d
Labels: auto-merge, Enhancement

#3624 fix some compatibility issues for Solaris systems
  src/core/internal/backtrace/elf.d
  src/core/stdcpp/exception.d
  src/core/sys/posix/signal.d
  src/core/sys/solaris/sys/elf.d
  src/core/sys/solaris/sys/elf_386.d
  src/core/sys/solaris/sys/elf_SPARC.d
Labels: auto-merge
