Repository dlang/druntime, pull requests merged in 2021-09, with the labels that each got.

#3563 [stable] core.sys.linux.fs: Fix compilability for Bionic and Musl C runtimes
  src/core/sys/linux/fs.d
Labels: auto-merge

#3562 [stable] core.exception: Add slice-versions of _d_arraybounds_{slice,index}
  src/core/exception.d
Labels: auto-merge

#3566 test/exceptions: Facilitate troubleshooting by printing stderr output
  test/exceptions/Makefile
Labels: auto-merge

#3565 Define remaining symbols in core.sys.windows.ddeml.
  src/core/sys/windows/ddeml.d
Labels: auto-merge

#3567 Add ioctls for OpenBSD.
  changelog/openbsd_ioctls.dd
  src/core/sys/posix/sys/filio.d
  src/core/sys/posix/sys/ioccom.d
  src/core/sys/posix/sys/ioctl.d
  src/core/sys/posix/sys/ttycom.d
Labels: auto-merge

#3568 Backport Fix Issue 15425 to druntime
  src/core/internal/traits.d
Labels: Blocking Other Work, auto-merge

#1756 Add `imported` for inline imports
  src/object.d
Labels: auto-merge-squash

#3569 Fix core.internal.traits.Fields implementation for interfaces
  src/core/internal/traits.d
Labels: auto-merge

#3570 [stable] Slightly tweak dynamiccast integration test
  test/shared/Makefile
  test/shared/src/dynamiccast.d
Labels: auto-merge

#3571 Fix issue 22328: Specific D types are used instead of Windows type aliases
  src/core/sys/windows/dll.d
Labels: auto-merge, Bug Fix

#3574 Fix issue 22336 - betterC move of non zero structs
  src/core/lifetime.d
  test/betterc/Makefile
  test/betterc/src/test22336.d
Labels: auto-merge, Bug Fix

#3137 Fix Issue 20936 - core.sync.rwmutex should have shared overloads (and make it usable in @safe code)
  src/core/sync/rwmutex.d
Labels: Enhancement, auto-merge-squash

#3575 Merge two calls to rangeMsgPut
  src/core/exception.d
Labels: auto-merge

#3576 merge stable
  src/core/exception.d
  src/core/sys/linux/fs.d
  test/shared/Makefile
  test/shared/src/dynamiccast.d
Labels: auto-merge, stable -> master
