Repository dlang/druntime, pull requests merged in 2021-10, with the labels that each got.

#3577 Sync OpenBSD dlfcn.
  src/core/sys/openbsd/dlfcn.d
Labels: auto-merge

#3578 core.sys.linux.perf_event: Add missing D runtime linux ports
  src/core/sys/linux/perf_event.d
Labels: Bug Fix, System Headers

#3608 Fix Issue 22457 - OpenBSD: enableDwarf in opApply in runtime.d
  src/core/runtime.d
Labels: Enhancement

#3606 Remove useless conditional assignment of DISABLED_TESTS
  posix.mak
Labels: auto-merge, Bug Fix

#3607 Fix Issue 22456 - OpenBSD: timer_* functions don't exist on OpenBSD
  src/core/sys/posix/time.d
Labels: Bug Fix

#3604 Fix Issue 22453 - OpenBSD: Add a dummy value for AI_V4MAPPED
  src/core/sys/posix/netdb.d
Labels: Bug Fix

#3605 Fix Issue 22454 - OpenBSD: Add prototypes for pthread_np.h
  mak/COPY
  mak/SRCS
  src/core/sys/openbsd/pthread_np.d
Labels: Enhancement

#3609 Trivial: Remove duplicated documentation / copyright notice in `rt.aApplyR`
  src/rt/aApplyR.d
Labels: auto-merge
