Repository dlang/druntime, pull requests merged in 2021-08, with the labels that each got.

#3529 rt.lifetime: Call library functions directly instead of using deprecated 'delete' keyword
  src/rt/lifetime.d
Labels: Blocking Other Work, Easy Review

#3526 [DSSv3] Fix Issue 9799 - add missing druntime imports
  changelog/improve_posix_imports.dd
  src/core/sys/linux/sys/procfs.d
  src/core/sys/posix/fcntl.d
Labels: Bug Fix, auto-merge

#3527 TypeInfo_Struct: Switch to stored mangled name & demangle lazily (with per-thread cache)
  .cirrus.yml
  azure-pipelines.yml
  changelog/UniqueTypeInfoNames.md
  src/core/internal/gc/impl/conservative/gc.d
  src/object.d
  src/rt/aaA.d
  src/rt/util/typeinfo.d
Labels: auto-merge

#3525 Fix Issue 22143 - Throwable ctor doesn't increment chained exception's ref count
  src/object.d
  test/exceptions/src/refcounted.d
Labels: Bug Fix, auto-merge

#3514 #2604 rebased - fork() based garbage collector
  changelog/forkgc.dd
  src/core/exception.d
  src/core/gc/config.d
  src/core/internal/gc/bits.d
  src/core/internal/gc/impl/conservative/gc.d
  src/core/internal/gc/os.d
  test/gc/Makefile
  test/gc/hospital.d
Labels: auto-merge-squash

#3532 [stable] OpenBSD core.sys.posix.semaphore: sem_t should be a pointer to an opaque struct
  src/core/sys/posix/semaphore.d
Labels: Bug Fix, auto-merge

#3531 [stable] On OpenBSD and Android make core.sys.posix.arpa.inet: htonl, htons, ntohl, & ntohs work correctly on big endian architectures
  src/core/sys/posix/arpa/inet.d
Labels: Bug Fix, auto-merge

#3533 [stable] Fix non-compiling ELF32_M_INFO & ELF64_M_INFO in core.sys.*.sys.elf32 & core.sys.*.sys.elf64 for DragonFlyBSD, FreeBSD, NetBSD, & OpenBSD
  src/core/sys/dragonflybsd/sys/elf32.d
  src/core/sys/dragonflybsd/sys/elf64.d
  src/core/sys/freebsd/sys/elf32.d
  src/core/sys/freebsd/sys/elf64.d
  src/core/sys/netbsd/sys/elf32.d
  src/core/sys/netbsd/sys/elf64.d
  src/core/sys/openbsd/sys/elf32.d
  src/core/sys/openbsd/sys/elf64.d
Labels: Bug Fix, Trivial, auto-merge

#3534 Mark as pure core.sys.posix.string: memccpy, stpcpy, stpncpy, strnlen
  src/core/sys/posix/string.d
Labels: Enhancement, auto-merge

#3535 Merge branch 'stable' into merge_master
  src/core/sys/dragonflybsd/sys/elf32.d
  src/core/sys/dragonflybsd/sys/elf64.d
  src/core/sys/freebsd/sys/elf32.d
  src/core/sys/freebsd/sys/elf64.d
  src/core/sys/netbsd/sys/elf32.d
  src/core/sys/netbsd/sys/elf64.d
  src/core/sys/openbsd/sys/elf32.d
  src/core/sys/openbsd/sys/elf64.d
  src/core/sys/posix/arpa/inet.d
  src/core/sys/posix/semaphore.d
Labels: Bug Fix, Easy Review, auto-merge, stable -> master

#3536 core.time: fix capitalization typo, it's MonoTime [trivial, NFC]
  src/core/time.d
Labels: Trivial

#3537 account for name mangling adjustment
  src/core/demangle.d
Labels: auto-merge

#3538 Fix 22178: fpclassify is pure on Musl too
  src/core/stdc/math.d
Labels: Bug Fix, auto-merge

#3539 Fix 22179: core.stdcpp.utility is missing from release
  mak/COPY
Labels: Bug Fix, auto-merge

#3528 Fix Issue 14439 - aa's keys, values not usable in @safe context
  src/object.d
Labels: Bug Fix, auto-merge

#3267 Fix Issue 21110 - OOB memory access, safety violation
  src/core/internal/array/operations.d
Labels: auto-merge, Bug Fix

#3540 merge stable
  mak/COPY
  src/core/internal/array/operations.d
  src/core/stdc/math.d
Labels: auto-merge, Bug Fix

#3542 Fix Cirrus CI (bump Ubuntu to 18.04)
  .cirrus.yml
Labels: auto-merge

#3544 TypeInfo_Class: Make 2 superfluously virtual functions final
  src/object.d
Labels: auto-merge

#3547 Cirrus CI: Add FreeBSD 11 pipeline
  .cirrus.yml
  src/object.d
Labels: auto-merge, Continuous Integration

#3549 Revert "Revert "TypeInfo_Class: Make 2 superfluously virtual functions final""
  src/object.d
Labels: auto-merge

#3548 Cirrus CI: Bump FreeBSD version to 12.2
  .cirrus.yml
Labels: auto-merge, Continuous Integration

#3543 Fix Issue 22218 - Dynamic casts across binary boundaries can easily fail
  src/rt/cast_.d
  test/shared/Makefile
  test/shared/src/dynamiccast.d
  test/shared/win64.mak
Labels: Bug Fix

#3551 core.attribute: Add weak enum for tagging symbols that should have weak linkage
  src/core/attribute.d
  src/core/internal/gc/proxy.d
  src/core/stdcpp/exception.d
  src/core/stdcpp/typeinfo.d
  src/rt/lifetime.d
Labels: auto-merge, Attributes

#3553 core.exception: Remove dead comment about ModuleInfo functions
  src/core/exception.d
Labels: Trivial, auto-merge

#3550 Add test case for issue 22124
  src/core/thread/osthread.d
Labels: Bug Fix

#3555 Add tests for TypeInfo_Struct xopEqual and xopCmp
  src/core/internal/qsort.d
  src/rt/adi.d
Labels: auto-merge, Easy Review

#3556 core.internal.backtrace.unwind: Align _Unwind_Exception to 16 on 32-bit
  src/core/internal/backtrace/unwind.d
Labels: Blocking Other Work, auto-merge, Bug Fix

#3557 core.stdcpp.typeinfo: Add implementation of typeinfo for CppRuntime_Clang
  src/core/stdcpp/typeinfo.d
Labels: Blocking Other Work, auto-merge, Bug Fix, stdcpp, core.stdcpp

#3558 core.stdcpp.exception: Add separate implemention of exception for CppRuntime_DigitalMars
  src/core/stdcpp/exception.d
Labels: Blocking Other Work, auto-merge, Bug Fix, stdcpp, core.stdcpp

#3559 core.stdcpp.typeinfo: Use extern(C++, class) struct for the internal class type_info for CppRuntime_Gcc
  src/core/stdcpp/typeinfo.d
Labels: Blocking Other Work, auto-merge, Bug Fix, stdcpp, core.stdcpp

#3552 core.stdcpp: Upstream differences between dmd and gdc/ldc druntimes
  mak/SRCS
  src/core/stdcpp/exception.d
  src/core/stdcpp/typeinfo.d
  test/stdcpp/Makefile
  test/stdcpp/src/exception.cpp
  test/stdcpp/src/exception_test.d
  test/stdcpp/src/typeinfo.cpp
  test/stdcpp/src/typeinfo_test.d
Labels: auto-merge, stdcpp, core.stdcpp

#3100 atomic.d: remove use of typesafe variadic functions
  src/core/internal/atomic.d
Labels: auto-merge, Refactoring

#3147 Speed up hashOf for associative arrays
  src/core/internal/hash.d
  src/rt/aaA.d
Labels: auto-merge, Enhancement

#3098 time.d: remove use of typesafe variadic functions
  src/core/time.d
Labels: auto-merge, Refactoring
