Repository dlang/druntime, pull requests merged in 2021-01, with the labels that each got.

#3320 merge stable
  changelog/accidentally-exposed-sigs.dd
Labels: auto-merge, stable -> master

#3322 Refactor some backtrace code to make it possible to use libunwind
  src/core/internal/backtrace/dwarf.d
Labels: Refactoring, auto-merge

#3323 Minor refactoring / documentation to the backtrace code
  src/core/internal/backtrace/dwarf.d
Labels: Refactoring, auto-merge

#3324 core.stdc.stdarg: Don't import core.internal.vararg when using GDC
  src/core/stdc/stdarg.d
Labels: auto-merge

#3321 Add experimental support for libunwind-based stack trace printing
  changelog/libunwind.dd
  mak/COPY
  mak/DOCS
  mak/SRCS
  src/core/internal/backtrace/dwarf.d
  src/core/internal/backtrace/handler.d
  src/core/internal/backtrace/libunwind.d
  src/core/runtime.d
Labels: Enhancement, auto-merge

#3325 [stable] Android: Fix compilability regression wrt. missing __USE_FILE_OFFSET64
  src/core/sys/posix/config.d
Labels: auto-merge

#3326 Move rt.unwind to core.internal.backtrace
  mak/COPY
  mak/DOCS
  mak/SRCS
  src/core/internal/backtrace/unwind.d
  src/rt/dwarfeh.d
Labels: auto-merge

#3327 Removed redundant or unused private functions from core.time
  src/core/time.d
Labels: auto-merge

#3328 backtrace: Look for _d_throwdwarf instead of skipping frames
  src/core/internal/backtrace/dwarf.d
  src/core/internal/backtrace/handler.d
  src/core/runtime.d
Labels: auto-merge

#3329 backtrace: Get rid of traceHandlerOpApplyImpl2 redundancy
  src/core/internal/backtrace/dwarf.d
  src/core/internal/backtrace/handler.d
  src/core/runtime.d
Labels: auto-merge

#3330 Temporarily comment one test
  src/core/lifetime.d
Labels: Blocking Other Work

#3331 core.internal.backtrace.libunwind: Tiny fixup for Android i686
  src/core/internal/backtrace/libunwind.d
  src/core/runtime.d
Labels: auto-merge

#3332 Little core.internal.lifetime.emplaceRef() CTFE fix/workaround
  src/core/internal/lifetime.d
Labels: Blocking Other Work

#3333 Musl: Add some missing AT_* in fcntl
  src/core/sys/posix/fcntl.d
Labels: auto-merge

#3335 Fix dladdr definition for Darwin and CRuntime_Musl
  src/core/sys/posix/dlfcn.d
Labels: auto-merge

#3337 object: calculate size_t and ptrdiff_t instead of use version block
  src/object.d
Labels: Refactoring, auto-merge

#3338 object: improve code style consistency
  src/object.d
Labels: Trivial, auto-merge

#3339 git: prevent *.lst file being tracked by adding to .gitignore
  .gitignore
Labels: auto-merge

#3340 rt: monitor_: simplify _d_setSameMutex logic
  src/rt/monitor_.d
Labels: auto-merge

#3336 Fix 21544 - -checkaction=context formats enum members as their base type
  src/core/internal/dassert.d
Labels: Bug Fix

#3344 rt: cover: complete documentation for _d_cover_register2 hook
  src/rt/cover.d
Labels: auto-merge, documentation

#3341 Fix Issue 14790: rt: cover: coverage merge should detect changed source code
  src/rt/cover.d
  test/coverage/Makefile
  test/coverage/src-merge_override.lst_1.exp
  test/coverage/src-merge_override.lst_2.exp
  test/coverage/src/merge_override.d
Labels: Enhancement, auto-merge

#3343 Fix issue 21578 - core.atomic.atomicFetchSub for pointers incorrectly…
  src/core/atomic.d
Labels: Bug Fix, auto-merge

#3345 Fix issue 21309 along with other dead links on dlang.org
  mak/DOCS
  posix.mak
  src/core/internal/elf/dl.d
  src/core/internal/util/array.d
  src/core/sys/posix/mqueue.d
  src/object.d
  src/rt/aApplyR.d
  src/rt/aaA.d
  src/rt/cast_.d
  src/rt/cmath2.d
  src/rt/critical_.d
  src/rt/ehalloc.d
  src/rt/invariant.d
  src/rt/memset.d
  src/rt/monitor_.d
  src/rt/msvc.d
  src/rt/tlsgc.d
  src/rt/tracegc.d
  src/rt/util/typeinfo.d
Labels: Bug Fix, auto-merge

#3349 Remove tests for complex and imaginary types
  src/core/internal/array/comparison.d
  src/rt/util/typeinfo.d
Labels: Deprecation, auto-merge

#3347 object.d: Improve coverage by adding some missing unittests
  src/object.d
Labels: auto-merge

#3351 core.internal.convert: Deprecate complex toUbyte
  src/core/internal/convert.d
Labels: Deprecation, auto-merge

#3350 Remove some more tests for complex and imaginary types
  src/core/internal/convert.d
  test/exceptions/src/assert_fail.d
Labels: auto-merge

#3352 core.lifetime.emplace(): Properly forward r/lvalue-ness of arguments
  src/core/lifetime.d
Labels: Blocking Other Work

#3346 Remove duplicated definitions for .min() and .max() functions
  mak/COPY
  mak/DOCS
  mak/SRCS
  src/core/internal/util/math.d
  src/core/time.d
  src/rt/aaA.d
  src/rt/cover.d
Labels: 72h no objection -> merge

#3356 core.sys.posix.locale: Fix definitions for Musl, Bionic,OpenBSD and Solaris
  src/core/sys/posix/locale.d
Labels: System Headers, auto-merge

#3354 DragonFly/OpenBSD: Fix pthread_once_t and PTHREAD_ONCE_INIT definitions
  src/core/sys/posix/pthread.d
  src/core/sys/posix/sys/types.d
Labels: System Headers, auto-merge
