Repository dlang/druntime, pull requests merged in 2021-03, with the labels that each got.

#3385 Remove usage of 'in' on _d_newitemU
  src/core/memory.d
  src/rt/lifetime.d
Labels: auto-merge

#3386 sigqueue: sigval argument is not scope
  src/core/sys/posix/signal.d
Labels: auto-merge

#3376 [REG 2.084] hashOf will fail to compile for some structs/unions that recursively contain shared enums
  src/core/internal/convert.d
  test/hash/src/test_hash.d
Labels: Bug Fix, Enhancement, Regression, auto-merge

#3388 merge stable
  src/core/internal/convert.d
  test/hash/src/test_hash.d
Labels: Bug Fix, auto-merge

#3389 Fix 21666 - Remove deprecations w.r.t. real formatting for checkaction=context
  src/core/internal/dassert.d
Labels: Bug Fix, auto-merge

#3201 Remove bodies of D functions that are trivial wrappers of C functions
  src/core/memory.d
  src/core/runtime.d
  src/core/stdc/errno.d
  src/core/stdc/math.d
  src/core/stdc/stdio.d
  src/core/stdc/wchar_.d
Labels: auto-merge

#3390 Simplify destroy!(bool,T) template constraint for static arrays
  src/object.d
Labels: auto-merge

#3396 Github CI: Drop Ubuntu 16.04 and clang < 8
  .github/workflows/cxx.yml
Labels: auto-merge-squash

#3398 Merge stable
  .github/workflows/cxx.yml
  changelog/callStructDtorsDuringGC.dd
  changelog/freebsd-statvfs.dd
  changelog/libunwind.dd
  src/core/internal/dassert.d
Labels: Bug Fix, auto-merge

#3395 fix issue 21712 - [REG 2.096.0] sometimes coverage *.lst files are corrupted
  src/rt/cover.d
Labels: Bug Fix, auto-merge

#3399 core.lifetime: Tag -betterC compatible unittests
  src/core/lifetime.d
Labels: @betterC, auto-merge

#3392 Fix Issue 21701 - casWeak is not implemented
  src/core/atomic.d
  src/core/internal/atomic.d
Labels: Bug Fix, auto-merge, core.atomic

#3265 core.stdcpp.allocator: _Adjust_manually_vector_aligned checks for sentinel unconditionally (Windows only)
  src/core/stdcpp/allocator.d
  test/stdcpp/src/allocator.cpp
  test/stdcpp/src/allocator_test.d
Labels: Bug Fix, auto-merge

#3403 Fix invalid test in test_aa.d
  test/aa/src/test_aa.d
Labels: auto-merge

#3404 core.sys.posix.unistd: Add non-standard environ variable
  src/core/sys/posix/unistd.d
Labels: System Headers, auto-merge

#3406 object docs: Group symbol links in a table
  src/object.d
Labels: auto-merge, documentation

#3405 core.sys.windows.malloc: New bindings module for malloc.h
  mak/COPY
  mak/DOCS
  mak/SRCS
  src/core/sys/windows/stdc/malloc.d
Labels: System Headers, auto-merge

#3408 core.demangle: parse struct literal with function literal member as t…
  src/core/demangle.d
Labels: auto-merge

#3410 Remove legacy _d_assert_fail overload
  src/core/internal/dassert.d
  test/exceptions/src/assert_fail.d
Labels: auto-merge

#3411 Fix 21764 - checkaction=context doesn't work for empty tuples
  src/core/internal/dassert.d
  test/exceptions/src/assert_fail.d
Labels: Bug Fix, auto-merge

#3412 dassert: Avoid copying the key type
  src/core/internal/dassert.d
Labels: Trivial, auto-merge

#3414 Begin OpenBSD unistd.d extension module with plegde and unveil.
  src/core/sys/openbsd/unistd.d
  src/core/sys/posix/unistd.d
Labels: System Headers, auto-merge

#3415 Make profile tests independent of semantic evaluation order
  test/profile/Makefile
Labels: auto-merge

#3416 Sync OpenBSD errno from -current sys/errno.h
  src/core/stdc/errno.d
Labels: auto-merge

#3418 Fix Issue 21784: Allow detached threads to be joined
  src/core/thread/osthread.d
  test/thread/Makefile
  test/thread/src/join_detach.d
Labels: Enhancement, auto-merge

#3420 stdcpp test: build memory.cpp with std=c++11
  test/stdcpp/Makefile
Labels: Build System, auto-merge, core.stdcpp
