Repository dlang/druntime, pull requests merged in 2021-07, with the labels that each got.

#3505 Issue 21488 - Always compile druntime library with -fPIC on POSIX targets
  posix.mak
Labels: Bug Fix, Build System

#3496 core.checkedint.addu: Faster (like subu: only one compare-and-branch).
  src/core/checkedint.d
Labels: auto-merge

#3511 Revert "core.checkedint.addu: Faster (like subu: only one compare-and-branch)."
  src/core/checkedint.d
Labels: auto-merge

#3509 Fix Issue 22107 - [scope][dip1000] Can't .dup an array of structs wit…
  src/object.d
Labels: Bug Fix

#3508 core.sys.posix.sys: Remove executable flag from ioccom.d and ttycom.d
  src/core/sys/posix/sys/ioccom.d
  src/core/sys/posix/sys/ttycom.d
Labels: Trivial, auto-merge

#3512 azure-pipelines.yml: Reduce timeout time to 60 minutes
  azure-pipelines.yml
Labels: Continuous Integration, auto-merge

#3510 Make `move` -dip1000 compatible
  src/core/lifetime.d
Labels: auto-merge

#3506 core.atomic: Allow 128-bit CAS operations if runtime has128BitCAS
  src/core/internal/atomic.d
Labels: Blocking Other Work, auto-merge

#3517 Add informative range errors for arrays
  src/core/exception.d
Labels: auto-merge

#3522 Fix 22126 - Don't print overlapped fields with -checkaction=context
  src/core/internal/dassert.d
  test/exceptions/src/assert_fail.d
Labels: Bug Fix

#3515 merge stable
  posix.mak
  src/core/internal/backtrace/dwarf.d
  src/core/internal/dassert.d
  src/core/internal/hash.d
  test/exceptions/src/assert_fail.d
  test/hash/src/test_hash.d
Labels: Bug Fix, auto-merge

#3524 Improve documentation in dassert.d
  src/core/internal/dassert.d
Labels: Trivial
