Repository dlang/druntime, pull requests merged in 2021-02, with the labels that each got.

#3358 core.stdc.stdio: Fix "read-modify-write operations are not allowed for shared variables" on OpenBSD
  src/core/stdc/stdio.d
Labels: System Headers, auto-merge

#3357 Add platform-specific sysctl declarations
  mak/COPY
  mak/SRCS
  src/core/sys/darwin/sys/sysctl.d
  src/core/sys/dragonflybsd/sys/sysctl.d
  src/core/sys/freebsd/sys/sysctl.d
  src/core/sys/netbsd/sys/sysctl.d
  src/core/sys/openbsd/sys/sysctl.d
Labels: System Headers, auto-merge

#3355 Add platform-specific getprogname/setprogname function declarations
  mak/COPY
  mak/SRCS
  src/core/sys/bionic/stdlib.d
  src/core/sys/darwin/stdlib.d
  src/core/sys/dragonflybsd/stdlib.d
  src/core/sys/freebsd/stdlib.d
  src/core/sys/netbsd/stdlib.d
  src/core/sys/openbsd/stdlib.d
  src/core/sys/solaris/stdlib.d
Labels: System Headers, auto-merge

#3359 core.thread.osthread: Remove duplicate version scope
  src/core/thread/osthread.d
Labels: Trivial, auto-merge

#3360 core.sys.darwin.mach.dyld: Add NS functions from dyld.h
  src/core/sys/darwin/mach/dyld.d
Labels: System Headers, auto-merge

#3361 Remove expired deprecations from druntime
  changelog/callStructDtorsDuringGC.dd
  changelog/freebsd-statvfs.dd
  src/core/sys/posix/sys/statvfs.d
  src/rt/lifetime.d
Labels: Deprecation, Trivial, auto-merge

#3362 [dmd-cxx] Fix fiber_guard_page test
  .github/workflows/dmd-cxx.yml
  posix.mak
  src/rt/bss_section.c
  test/shared/Makefile
  test/shared/src/link_mod_collision.d
  test/shared/src/load_mod_collision.d
  test/thread/src/fiber_guard_page.d
Labels: Trivial, auto-merge

#3353 [stable] rt.sections_elf_shared: Upstream MIPS/RISC-V fix wrt. .so dependency names from GDC
  src/rt/sections_elf_shared.d
Labels: 72h no objection -> merge

#3363 [dmd-cxx] Synchronize bindings with upstream druntime master
  mak/COPY
  mak/SRCS
  src/core/internal/attributes.d
  src/core/stdc/stdio.d
  src/core/sys/bionic/stdlib.d
  src/core/sys/darwin/mach/dyld.d
  src/core/sys/darwin/stdlib.d
  src/core/sys/darwin/sys/sysctl.d
  src/core/sys/dragonflybsd/stdlib.d
  src/core/sys/dragonflybsd/sys/sysctl.d
  src/core/sys/freebsd/stdlib.d
  src/core/sys/freebsd/sys/sysctl.d
  src/core/sys/netbsd/stdlib.d
  src/core/sys/netbsd/sys/sysctl.d
  src/core/sys/openbsd/stdlib.d
  src/core/sys/openbsd/sys/sysctl.d
  src/core/sys/posix/locale.d
  src/core/sys/posix/mqueue.d
  src/core/sys/posix/pthread.d
  src/core/sys/posix/sys/statvfs.d
  src/core/sys/posix/sys/types.d
  src/core/sys/solaris/stdlib.d
Labels: System Headers, Trivial, auto-merge

#3365 core.sys.posix.locale: Complete the Solaris bindings
  src/core/sys/posix/locale.d
Labels: System Headers, auto-merge

#3366 [dmd-cxx] Backport intrinsics modules from master, couple more Solaris fixes.
  mak/COPY
  mak/SRCS
  src/core/bitop.d
  src/core/checkedint.d
  src/core/cpuid.d
  src/core/internal/traits.d
  src/core/math.d
  src/core/simd.d
  src/core/sys/posix/locale.d
  src/core/thread/osthread.d
  src/core/vararg.d
  src/core/volatile.d
  src/rt/lifetime.d
Labels: System Headers, Trivial, auto-merge-squash

#3367 Deprecate cfloat/cdouble/creal stdc bindings
  src/core/stdc/complex.d
  src/core/stdc/tgmath.d
Labels: System Headers, auto-merge

#3371 [Stable] Darwin: Add missing files to DOCS / SRCS
  mak/COPY
  mak/DOCS
  mak/SRCS
Labels: Build System, auto-merge

#3370 Move gc package to core.internal
  CODEOWNERS
  mak/COPY
  mak/DOCS
  mak/SRCS
  posix.mak
  src/core/internal/gc/bits.d
  src/core/internal/gc/impl/conservative/gc.d
  src/core/internal/gc/impl/manual/gc.d
  src/core/internal/gc/impl/proto/gc.d
  src/core/internal/gc/os.d
  src/core/internal/gc/pooltable.d
  src/core/internal/gc/proxy.d
  test/gc/Makefile
  test/gc/win64.mak
Labels: 72h no objection -> merge, GC, Pay-as-you-go Runtime, Refactoring

#3374 merge stable
  mak/COPY
  mak/SRCS
  src/core/atomic.d
  src/core/sys/posix/config.d
  src/core/sys/posix/dlfcn.d
  src/rt/sections_elf_shared.d
Labels: Bug Fix

#3318 Fix 21472 (1/2) - Add tuple formatting to _d_assert_fail`
  src/core/internal/dassert.d
  test/exceptions/src/assert_fail.d
Labels: auto-merge

#3378 test_hash: Remove hashOf tests for complex types
  test/hash/src/test_hash.d
Labels: Trivial, auto-merge

#3377 core.stdc.config: Add `c_complex_float`, `c_complex_double`, and `c_complex_real` aliases
  src/core/stdc/config.d
  src/rt/memset.d
Labels: auto-merge

#3380 Remove a few uses of fully qualified names that rely on a DMD bug
  src/core/sys/windows/com.d
Labels: auto-merge

#3379 rt.util.typeinfo: Deprecate typeinfo for built-in complex and imaginary types
  posix.mak
  src/core/stdc/config.d
  src/rt/util/typeinfo.d
  win32.mak
  win64.mak
Labels: Deprecation, auto-merge, auto-merge-squash

#3368 sys/linux/epoll: add EPOLLWAKEUP constant, epoll_pwait() call and add documentation
  src/core/sys/linux/epoll.d
Labels: auto-merge

#3381 DIP1034 add noreturn to object, abort, exit, _Exit
  src/core/stdc/stdlib.d
  src/object.d
Labels: Enhancement

#3382 core.internal.backtrace.dwarf: Fix segfault regression in case executable cannot be opened
  src/core/internal/backtrace/dwarf.d
Labels: Bug Fix, auto-merge
