Repository dlang/druntime, pull requests merged in 2021-05, with the labels that each got.

#3457 Fix Issue 21363 - [REG2.094] Implementation of core.bitop.ror(x,0) is…
  src/core/bitop.d
Labels: Bug Fix, Enhancement, auto-merge

#3456 Consistently compare ints with `(a > b) - (a < b)`
  src/core/internal/array/comparison.d
  src/core/internal/string.d
  src/core/time.d
  src/object.d
  src/rt/trace.d
  src/rt/util/typeinfo.d
Labels: auto-merge

#3436 core.{attribute,builtins}: Publicly import GDC and LDC builtins and attributes.
  src/core/attribute.d
  src/core/builtins.d
Labels: Enhancement, Needs Decision

#3459 Simplify anySatisfy, allSatisfy, maxAlignment
  src/core/internal/traits.d
Labels: auto-merge

#3460 Add non-posix search for dlsym
  src/core/sys/darwin/dlfcn.d
Labels: auto-merge

#3461 Faster and smaller Unqual
  src/core/internal/traits.d
Labels: auto-merge

#3464 Remove unnecessary extern (D) blocks in cmath
  src/core/stdc/math.d
Labels: auto-merge

#3465 Remove unnecessary !isunordered from cmath isgreater etc.
  src/core/stdc/math.d
Labels: auto-merge

#3462 Even smaller and simpler Unqual
  src/core/internal/traits.d
Labels: auto-merge

#3463 Simplify anySatisfy and allSatisfy further
  src/core/internal/traits.d
Labels: auto-merge

#3468 merge stable
  src/core/bitop.d
  src/core/sys/darwin/dlfcn.d
  src/object.d
Labels: Bug Fix

#3469 dlfcn.d: Fix static asserts for dlopen symbols
  src/core/sys/dragonflybsd/dlfcn.d
  src/core/sys/freebsd/dlfcn.d
  src/core/sys/netbsd/dlfcn.d
  src/core/sys/posix/dlfcn.d
Labels: System Headers, auto-merge

#3470 [dmd-cxx] dlfcn.d: Fix static asserts for dlopen symbols
  src/core/sys/dragonflybsd/dlfcn.d
  src/core/sys/freebsd/dlfcn.d
  src/core/sys/netbsd/dlfcn.d
  src/core/sys/posix/dlfcn.d
Labels: Easy Review, System Headers, auto-merge

#3471 Annotate `toThread` parameter `t` with `return scope`
  src/core/thread/osthread.d
Labels: auto-merge

#3472 Add scope to invertCompToken
  src/core/internal/dassert.d
Labels: auto-merge

#3473 Libunwind: Use dladdr to get function name (+ fix gc_inFinalizer)
  src/core/internal/backtrace/handler.d
Labels: auto-merge

#3475 Merge stable
  src/core/internal/backtrace/handler.d
  src/core/internal/dassert.d
  src/core/thread/osthread.d
Labels: auto-merge

#3477 rt/dwarfeh: Improve error message on uncaught exception
  src/rt/dwarfeh.d
Labels: auto-merge

#3478 Fix lambda syntax in core.internal.convert test
  src/core/internal/convert.d
Labels: auto-merge

#3467 Fix Issue 21097 - prevent stack allocation when destroying large aggregates
  posix.mak
  src/core/internal/lifetime.d
  test/lifetime/Makefile
  test/lifetime/src/large_aggregate_destroy_21097.d
Labels: Bug Fix, auto-merge

#3409 windows: Move rt_loadLibrary and rt_unloadLibrary to rt.sections
  src/rt/dmain2.d
  src/rt/sections_win32.d
  src/rt/sections_win64.d
Labels: auto-merge

#3400 Platform-independant definitions out of version blocks in core.stdc.stdint
  src/core/stdc/stdint.d
Labels: auto-merge

#3474 Rewrite `object.dup` to work with `scope` and copy constructors
  src/object.d
Labels: auto-merge

#3480 Annotate pure functions with return/scope
  src/core/atomic.d
  src/core/demangle.d
  src/core/gc/gcinterface.d
  src/core/internal/array/appending.d
  src/core/internal/array/casting.d
  src/core/internal/array/concatenation.d
  src/core/internal/convert.d
  src/core/internal/gc/impl/conservative/gc.d
  src/core/internal/gc/impl/manual/gc.d
  src/core/internal/gc/impl/proto/gc.d
  src/core/internal/gc/proxy.d
  src/core/lifetime.d
  src/core/memory.d
  src/object.d
  src/rt/lifetime.d
  src/rt/tracegc.d
  test/hash/src/test_hash.d
  test/init_fini/src/custom_gc.d
Labels: auto-merge

#3476 core/exception: Use staticError when throwing Exception
  src/core/exception.d
  test/allocations/Makefile
  test/allocations/src/alloc_from_assert.d
Labels: auto-merge

#3482 merge stable
  posix.mak
  src/core/internal/lifetime.d
  src/rt/dwarfeh.d
  test/lifetime/Makefile
  test/lifetime/src/large_aggregate_destroy_21097.d
Labels: Bug Fix, auto-merge

#3484 [stable] core.internal.lifetime: Fix recent regressions for emplaceInitializer()
  src/core/internal/lifetime.d
Labels: auto-merge

#3486 [stable] core.internal.dassert: Add support for vectors in miniFormat()
  src/core/internal/dassert.d
Labels: auto-merge

#3487 [stable] core.sys.posix.stdio: Add missing flockfile() etc. for Android/Bionic
  src/core/sys/posix/stdio.d
Labels: auto-merge
