Repository dlang/druntime, pull requests merged in 2021-12, with the labels that each got.

#3639 Translate _d_delstruct to template
  src/core/lifetime.d
  src/object.d
Labels: auto-merge

#3587 Make _d_arrayctor weakly pure
  src/core/internal/array/construction.d
Labels: auto-merge-squash

#3640 core.internal.elf.io: Fix segfaults after mmap errors
  src/core/internal/elf/io.d
Labels: auto-merge, Bug Fix, Enhancement

#3646 Revert "linux: add system call bindings"
  mak/COPY
  mak/SRCS
  src/core/sys/linux/syscalls.d
  src/core/sys/linux/unistd.d
Labels: Regression, auto-merge

#3645 Pass the correct dmd to the benchmark run
  posix.mak
Labels: auto-merge

#3648 merge stable
  posix.mak
  src/core/internal/elf/io.d
  src/core/internal/traits.d
  src/core/runtime.d
  src/core/sys/openbsd/execinfo.d
  test/traits/Makefile
  test/traits/src/all_satisfy.d
Labels: auto-merge, Bug Fix, Enhancement

#3643 Fix Issue 21656 - Read correct ELF executable for DWARF file/line infos
  src/core/internal/backtrace/elf.d
  src/core/internal/elf/io.d
  test/exceptions/Makefile
Labels: Bug Fix

#3649 core.sys.posix.sys.stat: Fix shape of stat_t on MIPS N32 and N64 targets
  src/core/sys/posix/sys/stat.d
Labels: auto-merge, System Headers, Easy Review

#3650 Localize imports in moveEmplaceImpl
  src/core/lifetime.d
Labels: auto-merge

#3651 Fix `_d_delstruct` unittest - correctly mark destructor as `nothrow`
  src/core/lifetime.d
Labels: auto-merge

#3652 Add missing core_thread.html to the list - previously nothing depende…
  mak/DOCS
Labels: auto-merge, Bug Fix

#2562 Lower dmd CmpExp between classes to __cmp call
  src/object.d
Labels: auto-merge

#3655 Fix Issue 22064 - Missing docs for core.builtins
  mak/DOCS
  posix.mak
  src/core/builtins.d
Labels: Bug Fix

#3657 merge stable
  src/core/internal/backtrace/elf.d
  src/core/internal/elf/io.d
  test/exceptions/Makefile
Labels: auto-merge, Bug Fix

#3659 fix call of `sizeof` in `thisExePath` on Illumos/Solaris
  src/core/internal/elf/io.d
Labels: auto-merge

#3660 Azure: Replace deprecated vs2017-win2016 image with windows-2019
  azure-pipelines.yml
Labels: auto-merge, Continuous Integration
