Repository dlang/druntime, pull requests merged in 2022-04, with the labels that each got.

#3793 merge stable
  mak/COPY
  mak/SRCS
  src/core/sys/openbsd/pwd.d
  src/core/thread/context.d
  src/rt/dmain2.d
  test/exceptions/Makefile
  test/exceptions/src/message_with_null.d
Labels: Bug Fix, Enhancement

#3794 copy core/int128.d to import directory
  mak/COPY
Labels: Blocking Other Work, auto-merge, Easy Review

#3798 core.int128: Match Cent layout on BigEndian targets
  src/core/int128.d
Labels: auto-merge, Refactoring, Easy Review

#3799 Fix Issue 22766 - copyEmplace does not work with copy constructor and @disable this()
  src/core/lifetime.d
Labels: auto-merge, Enhancement

#3800 Add `scope` to __aaGet functions
  src/object.d
  src/rt/aaA.d
Labels: auto-merge, DIP25 / DIP1000

#3801 core/exception: annotate @nogc on AssertError ctors
  src/core/exception.d
Labels: Trivial, Refactoring, Easy Review

#3804 Fix issue 22763 - importing std.utf fails in BetterC
  src/core/exception.d
Labels: auto-merge, Bug Fix

#3807 Add explicit `_d_arrayappendTTrace` hook
  src/core/internal/array/appending.d
  src/core/internal/array/utils.d
  src/object.d
Labels: Blocking Other Work, auto-merge

#3810 Mark gcRanges() with return attribute
  src/rt/sections_solaris.d
Labels: auto-merge, Bug Fix

#3808 add clarifying examples of SIMD usage
  src/core/simd.d
Labels: documentation

#3813 fix Issue 23065: importC: __builtin_expect should use c_long
  src/__builtins.di
Labels: auto-merge, Bug Fix

#3797 add nothrow to windows files
  src/core/sys/windows/objbase.d
  src/core/sys/windows/unknwn.d
Labels: Blocking Other Work, Easy Review

#3812 Fix issue 23060: MacOS: core.sys.posix.sys.socket missing some definitions
  src/core/sys/posix/sys/socket.d
Labels: auto-merge-squash

#3815 Improve documentation for thread_attachThis / thread_detachThis
  src/core/memory.d
  src/core/thread/osthread.d
  src/core/thread/threadbase.d
Labels: auto-merge
