Repository dlang/druntime, pull requests merged in 2022-02, with the labels that each got.

#3718 Fix Issue 22717 - TypeInfo_Struct.equals swaps lhs and rhs parameters
  src/object.d
Labels: Bug Fix

#3711 core.sys.posix.config: Deprecate non-standard __USE manifest constants
  src/core/internal/elf/dl.d
  src/core/sys/linux/config.d
  src/core/sys/linux/dlfcn.d
  src/core/sys/linux/errno.d
  src/core/sys/linux/netinet/in_.d
  src/core/sys/linux/string.d
  src/core/sys/linux/sys/mman.d
  src/core/sys/posix/aio.d
  src/core/sys/posix/config.d
  src/core/sys/posix/spawn.d
  src/core/sys/posix/sys/mman.d
  src/core/sys/posix/sys/stat.d
  src/core/sys/posix/sys/statvfs.d
Labels: System Headers, Refactoring, Deprecation

#3719 Add aliases for Visual C built in types extension
  src/__builtins.di
Labels: auto-merge

#3702 fix Issue 22535 - ImportC: gcc/clang math intrinsics are rejected
  src/__builtins.di
Labels: Bug Fix, ImportC

#3720 fix Issue 22721 - importC: some gnu builtins are rejected
  src/__builtins.di
Labels: auto-merge, Easy Review, ImportC

#3721 fix Issue 22735 - __builtins.di does not implement __builtin_bswap64 …
  src/__builtins.di
Labels: auto-merge, Bug Fix, Easy Review, ImportC

#3724 core.sys.posix.sys.mman: Fix definition of mmap64 for UClibc
  src/core/sys/posix/sys/mman.d
Labels: auto-merge, System Headers, Easy Review

#3725 core.stdc.stdio: Don't import off_t for either Bionic or UClibc
  src/core/stdc/stdio.d
Labels: auto-merge, System Headers, Easy Review

#3723 sys.posix.aio: Remove inaccurate bindings for uClibc
  src/core/sys/posix/aio.d
Labels: auto-merge, System Headers, Easy Review

#3727 Fix comment for core.runtime.Runtime.traceHandler wrt. setting to null
  src/core/runtime.d
Labels: auto-merge

#3722 core.sys.posix.config: Ensure _GNU/DEFAULT/ATFILE_SOURCE is defined for all CRuntimes
  src/core/sys/posix/config.d
Labels: auto-merge, System Headers, Easy Review

#3726 core.sys.posix.sys.shm: Add bindings for Bionic runtime
  src/core/sys/posix/sys/shm.d
Labels: auto-merge, System Headers, Easy Review

#3728 core.int128: Fix linter warning 'variable C20_0 is never used'
  src/core/int128.d
Labels: auto-merge, Easy Review

#3707 win32.mak: Explicitly use 32omf instead of $(MODEL)
  win32.mak
Labels: auto-merge

#3729 fix Issue 22741 - importC: Error: bswap isn.t a template
  src/__builtins.di
Labels: auto-merge, Bug Fix, Easy Review, ImportC

#3731 Make core.attribute.mustuse lower-case
  src/core/attribute.d
Labels: auto-merge

#3733 fix Issue 22553 - ImportC: undefined identifier __uint128_t
  src/__builtins.di
Labels: Bug Fix, Easy Review, ImportC

#3732 fix Issue 22744 - ImportC: builtins defined in __builtins.di cause un…
  src/__builtins.di
Labels: auto-merge, Bug Fix, Easy Review, ImportC

#3734 fix Issue 22721 - importC: some gnu and clang builtins are rejected
  src/__builtins.di
Labels: auto-merge, Bug Fix, Easy Review, ImportC

#3730 add src/importc.h
  mak/COPY
  posix.mak
  src/importc.h
Labels: auto-merge, Easy Review, ImportC

#3735 fix Issue 22598 - importC: Add support for __extension__ keyword
  src/importc.h
Labels: auto-merge, Bug Fix, Easy Review, ImportC

#3736 fix Issue 22756 - ImportC: no __builtin_offsetof
  src/importc.h
Labels: auto-merge, Bug Fix, Easy Review, ImportC

#3738 Merge branch 'stable' into merge_stable
  src/core/math.d
  src/core/sys/posix/sys/socket.d
Labels: auto-merge, Bug Fix, Enhancement

#3740 fix issue 19933 and 18816: MSVC: Undefined std{in,out,err} with -betterC
  src/core/stdc/stdio.d
  src/rt/msvc.d
  test/betterc/Makefile
  test/betterc/src/test19933.d
  test/betterc/win64.mak
  win64.mak
Labels: Enhancement

#3743 core: Remove declarations with expired deprecations
  src/core/bitop.d
  src/core/internal/convert.d
Labels: auto-merge, Deprecation, Easy Review

#3744 [stable] Fix TODO wrt. first 2.099 tag
  src/object.d
Labels: auto-merge

#3747 Add explicit `return ref` to test_hash
  test/hash/src/test_hash.d
Labels: auto-merge

#3739 fix Issue 22756 - ImportC: no __builtin_offsetof
  src/importc.h
Labels: Bug Fix, Easy Review, ImportC

#3748 core.sys.posix.sys.ipc: Add missing bindings for Darwin and Solaris targets
  src/core/sys/posix/sys/ipc.d
  src/core/sys/posix/sys/types.d
Labels: auto-merge, System Headers, Easy Review

#3749 Mark _d_arrayappend return ref instead of return scope
  src/core/internal/array/appending.d
Labels: auto-merge

#3750 Allow `_d_newThrowable` to be pure
  src/core/lifetime.d
Labels: auto-merge

#3741 Make Throwable.message safe and nothrow
  src/object.d
Labels: auto-merge

#3752 Make `core.time : Duration.toString` work with sink delegates
  src/core/time.d
Labels: auto-merge

#3753 use explicit return instead of inferring from inout for _Get_data() and _Getal() methods
  src/core/stdcpp/string.d
Labels: auto-merge

#3754 add return scope to as_array()
  src/core/stdcpp/string.d
Labels: auto-merge

#3756 Add DDOC for `core.time : Duration.toString` `sink` parameter
  src/core/time.d
Labels: auto-merge

#3757 add return scope to as_array()
  src/core/stdcpp/string.d
Labels: auto-merge

#3760 Put attributes on core.time : Duration.toString unittest
  src/core/time.d
Labels: auto-merge

#3759 [stable] core.stdcpp: Make constructors extern(D) and methods @nogc
  src/core/stdcpp/exception.d
  src/core/stdcpp/typeinfo.d
Labels: auto-merge

#3762 fix Issue 22822 - core.sys.posix.sys.stat: PPC stat_t bindings corrupt
  src/core/sys/posix/sys/stat.d
Labels: auto-merge, Bug Fix, System Headers

#3758 `core.memory`: Make GC.[profile]stats safe/nothrow/nogc
  src/core/gc/gcinterface.d
  src/core/internal/gc/impl/conservative/gc.d
  src/core/internal/gc/proxy.d
  src/core/memory.d
Labels: auto-merge
