Repository dlang/druntime, pull requests merged in 2022-05, with the labels that each got.

#3811 fix Issue 23046 - [REG][CODEGEN] __simd(XMM.LODLPS) bad codegen
  src/core/simd.d
Labels: Bug Fix

#3817 merge stable
  src/core/simd.d
  src/rt/sections_solaris.d
Labels: auto-merge, Bug Fix, stable -> master

#3818 cirrus.yml: Use an alternative mirror for FreeBSD 11
  .cirrus.yml
Labels: auto-merge

#3819 fix Issue 23067 - importC: offsetof macro assumes size_t is defined
  src/importc.h
Labels: auto-merge, Bug Fix, ImportC

#3822 no // comments in .h files
  src/importc.h
Labels: Blocking Other Work, auto-merge, ImportC

#3820 Use new __traits(classInstanceAlignment)
  src/core/internal/traits.d
  src/core/lifetime.d
  src/core/thread/osthread.d
  src/core/thread/threadbase.d
  test/init_fini/src/custom_gc.d
Labels: auto-merge, Refactoring

#3821 Don't re-initialize D class instances in destroy!false()
  src/object.d
Labels: auto-merge, Bug Fix

#3617 [trivial] Move SIGUSR1/SIGUSR2 to SIGRT for GC
  changelog/posix_gc_signals.dd
  src/core/memory.d
  src/core/thread/osthread.d
Labels: Trivial, auto-merge, Bug Fix

#3825 Object.getHash() shouldn't be casting away const
  src/core/thread/fiber.d
  src/core/thread/threadbase.d
  src/object.d
Labels: Blocking Other Work, auto-merge

#3827 Get hash2
  src/object.d
Labels: auto-merge

#3824 Optimise template `_d_arrayappendT`
  src/core/internal/array/appending.d
Labels: auto-merge

#3829 core.sys.solaris.sys.link: Move shared ELF values to core.sys.elf
  src/core/sys/dragonflybsd/sys/elf32.d
  src/core/sys/dragonflybsd/sys/elf64.d
  src/core/sys/elf/package.d
  src/core/sys/freebsd/sys/elf32.d
  src/core/sys/freebsd/sys/elf64.d
  src/core/sys/linux/elf.d
  src/core/sys/netbsd/sys/elf32.d
  src/core/sys/netbsd/sys/elf64.d
  src/core/sys/openbsd/sys/elf32.d
  src/core/sys/openbsd/sys/elf64.d
  src/core/sys/solaris/sys/elftypes.d
  src/core/sys/solaris/sys/link.d
Labels: auto-merge, Bug Fix, System Headers

#3823 Do not call throwable's ctor from `_d_newThrowable`
  src/core/lifetime.d
Labels: 72h no objection -> merge
