Repository dlang/druntime, pull requests merged in 2022-03, with the labels that each got.

#3764 merge stable
  src/core/memory.d
  src/core/stdcpp/exception.d
  src/core/stdcpp/typeinfo.d
  src/object.d
Labels: auto-merge, Bug Fix

#3768 core.sys.posix.locale: Fix DragonFlyBSD condition
  src/core/sys/posix/locale.d
Labels: auto-merge, System Headers, Easy Review

#3765 fix Issue 22829 - [REG master] Undefined symbol stderr first referenced in file test19933.o
  src/core/stdc/stdio.d
Labels: auto-merge, Bug Fix, System Headers

#3766 Fix issue 22832 - Can't destroy class with overloaded opCast
  src/object.d
Labels: auto-merge, Bug Fix

#3770 core.stdc.fenv: Fix missing import on linux/SPARC
  src/core/stdc/fenv.d
Labels: auto-merge, Bug Fix, Easy Review

#3769 fix Issue 22834 - core.stdc.stdint aliases are not platform independent
  src/core/stdc/stdint.d
Labels: auto-merge, Bug Fix, System Headers

#3772 core.stdc.stdint: Fix fast16_t definitions on MinGW
  src/core/stdc/stdint.d
Labels: auto-merge, System Headers, Easy Review

#3773 Prevent buffer overread in core.internal.gc.bits
  src/core/internal/gc/bits.d
Labels: auto-merge

#3763 fix Issue 22777 - stat struct in core.sys.windows.stat assumes CRunti…
  src/core/sys/windows/stat.d
Labels: Bug Fix, 72h no objection -> merge

#3774 fix Issue 22844 - [REG 2.089] SIGBUS, Bus error in _d_newitemU
  src/rt/lifetime.d
Labels: auto-merge, Bug Fix

#3775 fix Issue 22846 - [REG 2.066] SIGBUS, Bus error in _d_newarrayiT
  src/rt/lifetime.d
Labels: auto-merge, Bug Fix

#3776 Remove trailing semicolons from core.stdc[pp] bindings
  src/core/stdc/config.d
  src/core/stdcpp/new_.d
Labels: auto-merge, Easy Review

#3781 Add core.sys.openbsd.pwd module.
  mak/COPY
  mak/SRCS
  src/core/sys/openbsd/pwd.d
Labels: auto-merge, Enhancement

#3783 Fix return scope -> return ref in as_array()
  src/core/stdcpp/string.d
Labels: auto-merge, DIP25 / DIP1000

#3787 Fix 20778 - Ensure that _d_print_throwable prints the entire message
  src/rt/dmain2.d
  test/exceptions/Makefile
  test/exceptions/src/message_with_null.d
Labels: Regression, Bug Fix

#3785 fix Issue 22880 - importC: support __restrict__ __signed__ __asm__
  src/importc.h
Labels: auto-merge, Enhancement, ImportC

#3789 fix Issue 18117 - ldiv_t struct in core.stdc.stdlib -- int vs c_long …
  src/core/stdc/stdlib.d
Labels: auto-merge, Bug Fix

#3791 Fix 21086 - Correct link core.thread.context
  src/core/thread/context.d
Labels: auto-merge, Bug Fix, documentation, Easy Review

#3788 fix Issue 22843 - Program hangs on full gc collect with --DRT-gcopt=f…
  .cirrus.yml
  src/core/internal/gc/impl/conservative/gc.d
  test/gc/Makefile
  test/gc/issue22843.d
Labels: auto-merge, Bug Fix, Needs Tests

#3373 core.atomic.cas: add 'const' attribute to local variable 'arg1'
  src/core/atomic.d
Labels: auto-merge, Bug Fix

#3792 Fix confusing message on array cast failure.
  src/core/internal/array/casting.d
Labels: auto-merge, Enhancement
