Repository dlang/druntime, pull requests merged in 2022-01, with the labels that each got.

#3638 Fix Issue 22552 - moveEmplace wipes context pointer of nested struct …
  src/core/lifetime.d
Labels: auto-merge, Bug Fix

#3667 Don't link & run unittests for Win32 + OMF due to OPTLINK issues
  win32.mak
Labels: Continuous Integration

#3666 Cherry-pick Azure upgrade to master
  azure-pipelines.yml
Labels: auto-merge

#3661 Implement templated version of `_d_newThrowable`
  src/core/lifetime.d
  src/object.d
Labels: auto-merge

#3668 Fix Issue 22669 - OpenBSD: Sync socket.d
  src/core/sys/posix/sys/socket.d
Labels: auto-merge, Enhancement

#3669 Add support for the *BSD kqueue-backed inotify shim library.
  src/core/sys/linux/sys/inotify.d
Labels: auto-merge, Enhancement

#3658 Fix Issue 21014 - aa.byKeyValue, byKey, byValue very under-documented
  src/object.d
Labels: auto-merge, Enhancement

#3663 add core.int128
  CODEOWNERS
  mak/DOCS
  mak/SRCS
  src/core/int128.d
Labels: auto-merge

#3673 core.int128: Optimize rol() and ror()
  src/core/int128.d
Labels: auto-merge, Refactoring

#3672 core.int128: Optimize sar()
  src/core/int128.d
Labels: auto-merge, Refactoring

#3674 core.int128: Optimize mul()
  src/core/int128.d
Labels: auto-merge, Refactoring

#3671 optimize int128.d
  src/core/int128.d
Labels: auto-merge, Easy Review

#3676 Remove external reference to rndtonl.
  src/core/math.d
Labels: auto-merge, Bug Fix

#3677 finish __builtins support for stdarg
  src/__builtins.d
Labels: Blocking Other Work, ImportC

#3678 core.sys.posix.dlfcn: Move and remove duplicate dlopen and dladdr arguments
  src/core/sys/darwin/dlfcn.d
  src/core/sys/dragonflybsd/dlfcn.d
  src/core/sys/freebsd/dlfcn.d
  src/core/sys/linux/dlfcn.d
  src/core/sys/netbsd/dlfcn.d
  src/core/sys/openbsd/dlfcn.d
  src/core/sys/posix/dlfcn.d
  src/core/sys/solaris/dlfcn.d
Labels: auto-merge, System Headers, Refactoring

#3680 core.sys.posix.stdio: Fix condition for declaring P_tmpdir
  src/core/sys/posix/stdio.d
Labels: auto-merge, System Headers, Refactoring

#3681 Issue 14892: need to wrap _d_newarrayU as well for -profile=gc.
  src/rt/tracegc.d
Labels: auto-merge

#3679 core.sys.posix.sys.mman: Split mman OS flags from C runtime functions
  src/core/sys/posix/sys/mman.d
Labels: auto-merge, System Headers, Refactoring

#3683 Replace unreachable function call with assert in rt/dwarfeh.d...
  src/rt/dwarfeh.d
Labels: auto-merge

#3689 Issue 22689: core.sys.posix.sys.sched: Separate OS-specific flags and types from C runtime functions
  src/core/sys/posix/sched.d
Labels: auto-merge, System Headers, Refactoring

#3684 Issue 22689: core.sys.posix.sys.dirent: Separate OS dirent struct from C runtime functions and flags
  src/core/sys/posix/dirent.d
Labels: auto-merge, Bug Fix, System Headers, Refactoring

#3690 Issue 22689: core.sys.posix.sys.shm: Separate OS-specific flags and types from C runtime functions
  src/core/sys/posix/sys/shm.d
Labels: auto-merge, System Headers, Refactoring

#3685 Issue 22689: core.sys.posix.fcntl: Separate OS-specific flags and types from C runtime functions
  src/core/sys/posix/fcntl.d
Labels: auto-merge, System Headers, Refactoring

#3686 Issue 22689: core.sys.posix.sys.ipc: Separate OS-specific flags and types from C runtime functions
  src/core/sys/posix/sys/ipc.d
Labels: auto-merge, System Headers, Refactoring

#3687 Issue 22689: core.sys.posix.poll: Separate OS-specific flags from C runtime types and functions
  src/core/sys/posix/poll.d
Labels: auto-merge, System Headers, Refactoring

#3692 Make `_d_newThrowable` return a fully constructed `Throwable`
  src/core/lifetime.d
Labels: auto-merge

#3688 Issue 22689: core.sys.posix.sys.resource: Separate OS-specific flags and types from C runtime types and functions
  src/core/sys/posix/sys/resource.d
Labels: auto-merge, System Headers, Refactoring

#3675 core.int128: Optimize udivmod()
  src/core/int128.d
Labels: Refactoring

#3682 Issue 13416: Remove libthr hack from core.thread.osthread
  src/core/thread/osthread.d
Labels: Blocking Other Work, Easy Review

#3693 core.int128: Add test for udivmod where lower bits of denominator > upper
  src/core/int128.d
Labels: auto-merge, Easy Review

#3698 core.sys.posix.stdc.time: Prefer CRuntime definitions over OS definitions of CLOCKS_PER_SEC
  src/core/sys/posix/stdc/time.d
Labels: auto-merge, System Headers, Refactoring

#3696 Issue 22689: core.sys.posix.sys.stat: Separate OS-specific types and flags from C runtime functions
  src/core/sys/posix/sys/stat.d
Labels: auto-merge, System Headers, Refactoring

#3695 Issue 22689: core.sys.posix.sys.socket: Separate OS-specific types and flags from C runtime functions
  src/core/sys/posix/sys/socket.d
Labels: auto-merge, System Headers, Refactoring

#3694 Issue 22689: core.sys.posix.signal: Separate OS-specific types and flags from C runtime functions
  src/core/sys/posix/signal.d
Labels: auto-merge, Refactoring

#3700 core.sys.posix.sys.wait: Separate OS-specific types and flags from C runtime functions
  src/core/sys/posix/sys/wait.d
Labels: auto-merge, System Headers, Refactoring

#3697 Issue 22689: core.sys.posix.termios: Separate OS-specific types and flags from C runtime functions
  src/core/sys/posix/termios.d
Labels: auto-merge, System Headers, Refactoring

#3699 core.sys.posix.sys.types: Separate OS-specific types from C runtime types
  src/core/sys/posix/sys/types.d
Labels: System Headers, Refactoring

#3030 Replace usages of classinfo with typeid
  benchmark/gcbench/vdparser.extra/vdc/ast/node.d
  benchmark/gcbench/vdparser.extra/vdc/ast/type.d
  benchmark/gcbench/vdparser.extra/vdc/interpret.d
  benchmark/gcbench/vdparser.extra/vdc/logger.d
  src/core/internal/gc/impl/conservative/gc.d
  src/object.d
  src/rt/dmain2.d
  src/rt/dwarfeh.d
Labels: auto-merge

#3703 Make win32.mak compatible with MODEL=32omf
  azure-pipelines.yml
  win32.mak
Labels: Blocking Other Work, auto-merge, Continuous Integration

#3704 Omit -version=CoreUnittest and -checkaction=context for example tests
  posix.mak
Labels: auto-merge, Continuous Integration

#3691 Fix 14892: Add tracing wrappers for core.memory.GC allocation calls.
  src/core/memory.d
  src/rt/tracegc.d
  test/profile/myprofilegc.log.freebsd.32.exp
  test/profile/myprofilegc.log.freebsd.64.exp
  test/profile/myprofilegc.log.linux.32.exp
  test/profile/myprofilegc.log.linux.64.exp
  test/profile/myprofilegc.log.osx.32.exp
  test/profile/myprofilegc.log.osx.64.exp
  test/profile/src/profilegc.d
Labels: auto-merge, Enhancement

#3705 Fix #22702 - make compilant with getLinkage returning System or Obj-C
  src/core/demangle.d
  src/core/lifetime.d
Labels: auto-merge, Bug Fix

#3706 Fix GetICMProfile signature
  src/core/sys/windows/wingdi.d
Labels: auto-merge

#3708 core.stdc.math: Annotate classify functions with pure for UClibc
  src/core/stdc/math.d
Labels: auto-merge, System Headers, Easy Review

#3709 core.sys.posix.sys.ioctl: Separate OS-specific types and flags from C runtime functions
  src/core/sys/posix/sys/ioctl.d
Labels: auto-merge, System Headers, Refactoring, Easy Review

#3710 core.sys.posix.ucontext: Separate OS-specific types from C runtime functions
  src/core/sys/posix/ucontext.d
Labels: auto-merge, System Headers, Refactoring

#3713 core.stdc.math: Fix atan2l for uclibc
  src/core/stdc/math.d
Labels: auto-merge

#3714 win**.mak: Forward DMD for copyDir
  win32.mak
  win64.mak
Labels: auto-merge, Build System

#3712 DIP 1038: add core.attribute.mustUse
  src/core/attribute.d
Labels: auto-merge

#3717 __builtins: Rename to D interface file
  mak/COPY
  mak/SRCS
  src/__builtins.di
Labels: auto-merge

#3715 object: Wrap fake member function calls into delegates
  src/object.d
Labels: auto-merge
