Repository dlang/druntime, pull requests merged in 2022-07, with the labels that each got.

#3868 Fix Issue 23228 - OpenBSD: No SIGRTMIN or SIGRTMAX
  src/core/thread/osthread.d
Labels: auto-merge, Bug Fix

#3865 Issue 23212 - Improve documentation of rt/aApply
  src/rt/aApply.d
  src/rt/aApplyR.d
Labels: auto-merge

#3871 Change `_aaNew` to return `Impl*`, not `AA`
  src/rt/aaA.d
Labels: auto-merge

#3872 fix Issue 23213 - ImportC - variable length array does not compile
  src/importc.h
Labels: Bug Fix, Easy Review, ImportC

#3866 Extract dup and idup to own module
  mak/COPY
  mak/SRCS
  src/core/internal/array/duplication.d
  src/object.d
Labels: 72h no objection -> merge
