Repository dlang/druntime, pull requests merged in 2022-06, with the labels that each got.

#3831 Remove unneeded commas in core.attribute ddoc
  src/core/attribute.d
Labels: auto-merge

#3832 core.stdcpp.xutility: Add C++20 and a bit of documentation
  src/core/stdcpp/xutility.d
Labels: Trivial, auto-merge, documentation, Easy Review

#3836 Fix issue 21781 - Add core/sync/package.d for documentation
  mak/DOCS
  posix.mak
  src/core/sync/package.d
Labels: auto-merge, Bug Fix

#3844 Mark `_d_initMonoTime` `nothrow` `@nogc`
  src/core/time.d
  src/rt/dmain2.d
Labels: auto-merge

#3845 Mark `_d_critical_` and `_d_monitor_` functions `nogc` `nothrow`
  src/rt/critical_.d
  src/rt/dmain2.d
  src/rt/monitor_.d
Labels: auto-merge

#3842 Make `thread_init` and `thread_term` `nothrow`
  src/core/thread/osthread.d
  src/core/thread/threadbase.d
  src/rt/dmain2.d
  src/rt/monitor_.d
Labels: auto-merge

#3846 RISCV: Add some definitions and vararg supports
  src/core/stdc/stdarg.d
  src/core/sys/elf/package.d
  src/core/sys/posix/fcntl.d
  src/core/vararg.d
  src/rt/dwarfeh.d
Labels: auto-merge, System Headers

#3850 makefiles: Remove mak/IMPORTS and header .di generation recipes
  mak/COPY
  mak/IMPORTS
  mak/WINDOWS
  posix.mak
  win32.mak
  win64.mak
Labels: auto-merge, Build System

#3841 Remove `--DRT-oncycle=deprecate` option
  changelog/drt-oncycle-deprecate.dd
  src/rt/minfo.d
  test/cycles/Makefile
Labels: 72h no objection -> merge

#3839 Mark all functions with a @safe interface as @trusted
  src/core/sys/windows/winsock2.d
Labels: Trivial, 72h no objection -> merge

#3851 rt/minfo.d: add `nothrow`
  src/rt/minfo.d
Labels: auto-merge

#3854 RISCV: Fix vararg implementation
  src/core/stdc/stdarg.d
  src/core/vararg.d
Labels: auto-merge

#3855 compile .c files with ImportC
  win32.mak
Labels: ImportC

#3857 compile posix errno_c.c file with ImportC
  posix.mak
Labels: auto-merge, ImportC

#3858 compile src/rt/*.c with ImportC
  posix.mak
Labels: auto-merge, ImportC

#3856 compile mscoff .c files with ImportC
  src/importc.h
  win64.mak
Labels: auto-merge, ImportC

#3859 add documentation to win64.mak
  win64.mak
Labels: auto-merge, documentation, Easy Review

#3864 Remove unused Array struct
  src/rt/lifetime.d
Labels: auto-merge
